Repository element-hq/element-web, pull requests merged in 2020-01, with the labels that each got.

#11810 Updates URL for Electron Command Line Switches
  electron_app/src/electron-main.js
Labels: Community PR

#11926 Fix rageshake post-sourcemaps
  src/vector/rageshakesetup.js
Labels: release-blocker

#11959 Load as little as possible in index.js for the skinner
  src/vector/app.js
  src/vector/index.js
Labels: p2

#12126 Enable cross-signing on /develop
  riot.im/develop/config.json
Labels: cross-signing-sprint, story:1
