Repository element-hq/element-web, pull requests merged in 2020-09, with the labels that each got.

#15114 Support usage of Jitsi widgets with "openidtoken-jwt" auth
  package.json
  src/vector/jitsi/index.html
  src/vector/jitsi/index.ts
  yarn.lock
Labels: Community PR, release-blocker, sponsored

#15190 Add end-user documentation for UI features
  docs/config.md
Labels: blocked, release-blocker

#15196 Replace dummy sw.js with pre-caching and runtime-caching workbox SW
  package.json
  res/sw.js
  scripts/copy-res.js
  src/vector/index.html
  src/vector/index.ts
  webpack.config.js
  yarn.lock
Labels: blocked

#15334 Update Riot -> Element in redeploy.py
  scripts/redeploy.py
Labels: Community PR

#15333 Update Riot -> Element in issues-burndown.pl
  scripts/issues-burndown.pl
Labels: Community PR

#15332 Update Riot -> Element in welcome.html
  res/welcome.html
Labels: Community PR

#15330 Update Riot -> Element in docs/review.md
  docs/review.md
Labels: Community PR

#15329 Update Riot -> Element in VectorEmbeddedPage
  src/components/structures/VectorEmbeddedPage.js
Labels: Community PR

#15328 Update Riot -> Element in VectorAuthFooter
  src/components/views/auth/VectorAuthFooter.js
Labels: Community PR

#15327 Update Riot -> Element in element.io/README.md
  element.io/README
Labels: Community PR

#15325 Update Riot -> Element in docs/feature-flags.md
  docs/feature-flags.md
Labels: Community PR

#15336 Update Riot -> Element in redeploy.py
  scripts/redeploy.py
Labels: Community PR

#15326 Update Riot -> Element in contribute.json
  contribute.json
Labels: Community PR, invalid
