Repository element-hq/element-web, pull requests merged in 2021-09, with the labels that each got.

#18864 Update matrix-widget-api dependency
  package.json
  yarn.lock
Labels: T-Task

#18882 Issue automation: test GitHub's new shiny boards
  .github/workflows/issues_to_projects.yaml
Labels: T-Task, A-Developer-Experience

#18888 Revert "Issue automation: test GitHub's new shiny boards"
  .github/workflows/issues_to_projects.yaml
Labels: T-Task

#18886 Fix invalid yarn.lock
  yarn.lock
Labels: T-Task

#18877 Issue templates: merge expected and actual results
  .github/ISSUE_TEMPLATE/bug-desktop.yml
  .github/ISSUE_TEMPLATE/bug-web.yml
Labels: T-Task

#18920 Move A-Spaces issues to Delight project board GHA
  .github/workflows/issues_to_projects.yaml
Labels: T-Task

#18940 Update changelog generator
  package.json
  yarn.lock
Labels: T-Task

#18896 Issue labelling and process home updates
  .github/workflows/issues_to_projects.yaml
  .github/workflows/triage-priority-bugs.yml
  README.md
Labels: T-Task, A-Developer-Experience

#19056 yarn upgrade
  package.json
  yarn.lock
Labels: T-Task

#19038 Encourage false positives of the error dialog to result in tickets
  .env.example
Labels: T-Task

#19037 Fix space keyboard shortcuts conflicting with native zoom shortcuts
  src/vector/platform/ElectronPlatform.tsx
Labels: T-Enhancement

#18490 Update labs.md based on Spaces being delabsed
  docs/labs.md
  src/vector/platform/ElectronPlatform.tsx
Labels: T-Task

#19080 Fix broken readme link
  docs/translating-dev.md
Labels: T-Task

#18875 Remove accidentally persisted log-level data
  src/vector/index.ts
  src/vector/localstorage-fix.ts
Labels: T-Task

#19165 Convert `/src/usercontent` to TS
  webpack.config.js
Labels: T-Task

#19234 Removed iOS app Jitsi homeserver URL notice in the documentation
  docs/jitsi.md
Labels: T-Task
