Repository element-hq/element-web, pull requests merged in 2021-07, with the labels that each got.

#13138 Use URLSearchParams instead of transitive dependency `querystring`
  package.json
  src/vector/jitsi/index.ts
  src/vector/url_utils.ts
  test/unit-tests/url_utils-test.ts
Labels: T-Task

#18058 Update eslint-plugin-matrix-org
  yarn.lock
Labels: T-Task

#18150 yarn upgrade
  yarn.lock
Labels: T-Task

#18187 Update webpack path for new voice message worker location
  webpack.config.js
Labels: Sponsored, T-Task

#18267 Dismiss electron download toast when clicking Open
  src/vector/platform/ElectronPlatform.tsx
Labels: T-Defect
