Repository element-hq/element-web, pull requests merged in 2021-08, with the labels that each got.

#18166 Remove voice messages labs flag docs
  docs/labs.md
Labels: Sponsored, T-Task

#18362 Bump eslint deps
  yarn.lock
Labels: T-Task

#18395 Properly handle react-sdk's recorder worklet
  package.json
  src/vector/index.html
  webpack.config.js
  yarn.lock
Labels: Sponsored, T-Task

#18407 Fix the decoder-ring
  res/decoder-ring/index.html
Labels: T-Task

#18418 [Labs] Document hidden read receipts
  docs/labs.md
Labels: T-Task

#18441 Add changelog preview action
  .github/workflows/preview_changelog.yaml
Labels: T-Task

#18462 Add Actions for moving tasks on triage workboard
  .github/workflows/triage-incoming.yml
  .github/workflows/triage-needs-info.yml
Labels: A-Developer-Experience

#18471 Issue forms: remove old template
  .github/ISSUE_TEMPLATE.md
Labels: T-Defect, A-Developer-Experience

#18494 Fix dead link in contribution.md
  CONTRIBUTING.md
Labels: T-Task

#18501 Use changelog generator from npm
  package.json
  yarn.lock
Labels: T-Task

#18450 Add partially working HMR for JS/TS/React
  package.json
  webpack.config.js
  yarn.lock
Labels: T-Task, A-Developer-Experience

#18568 Update changelog generator
  package.json
  yarn.lock
Labels: T-Task

#18429 Ask if user has submitted logs in issue forms
  .github/ISSUE_TEMPLATE/bug-desktop.yml
  .github/ISSUE_TEMPLATE/bug-web.yml
Labels: T-Task

#18606 Issue triage: move priority bugs onto team board
  .github/workflows/triage-priority-bugs.yml
Labels: T-Enhancement

#18629 Update README to require node 14
  README.md
Labels: T-Task

#18623 README: link to wiki for issue triage process and labels
  README.md
Labels: T-Task

#18631 Issue triage: update automation for design team
  .github/workflows/issues_to_projects.yaml
Labels: T-Task

#18633 Issue triage: update automation for new labels
  .github/workflows/issues_to_projects.yaml
  .github/workflows/triage-priority-bugs.yml
Labels: T-Task

#18636 Issue triage: move only defects into priority bugs
  .github/workflows/triage-priority-bugs.yml
Labels: T-Task

#18608 Documentation for sentry config
  docs/config.md
Labels: T-Enhancement

#18651 Fix CI using invalid NODE_ENV
  src/vector/app.tsx
  webpack.config.js
Labels: T-Task

#18697 Update PR previews doc post GHA
  docs/pr-previews.md
Labels: T-Task

#18736 yarn upgrade
  yarn.lock
Labels: T-Task

#18774 Disable HMR error page by default
  .env.example
  webpack.config.js
Labels: T-Task
