Repository element-hq/element-web, pull requests merged in 2021-11, with the labels that each got.

#19546 Fix widget-api lockfile reference to avoid dependency conflicts
  yarn.lock
Labels: T-Task, X-Release-Blocker

#19585 Update allchange to 1.0.5
  package.json
  yarn.lock
Labels: T-Task

#19589 Update issue -> board automation
  .github/workflows/issues_to_projects.yaml
  .github/workflows/triage-move-labelled.yml
  .github/workflows/triage-move-unlabelled.yml
  .github/workflows/triage-needs-info.yml
Labels: T-Task

#19597 Reference commits instead of tags in workflows
  .github/workflows/triage-incoming.yml
  .github/workflows/triage-move-labelled.yml
  .github/workflows/triage-move-unlabelled.yml
  .github/workflows/triage-priority-bugs.yml
Labels: T-Task

#19618 Workflow: use our special token instead of github
  .github/workflows/triage-move-labelled.yml
Labels: T-Task

#19626 Workflow: move voice message issues to their board
  .github/workflows/triage-move-labelled.yml
Labels: T-Task

#19641 Workflow: do a better check on X-Needs-Info for unlabelling
  .github/workflows/triage-move-unlabelled.yml
Labels: T-Task

#19647 Update design team workflow to use beta board
  .github/workflows/triage-move-labelled.yml
Labels: T-Task

#19654 Move P1 issues to crypto team board
  .github/workflows/triage-priority-bugs.yml
Labels: T-Task

#19661 Move Spaces issues to new Delight board
  .github/workflows/triage-move-labelled.yml
Labels: T-Task

#19658 Fix conditional check before moving design issues
  .github/workflows/triage-move-labelled.yml
Labels: T-Task

#19670 Actions: use new voice message board for issues
  .github/workflows/triage-move-labelled.yml
Labels: T-Task

#19682 Update triage workflow to fix conditional
  .github/workflows/triage-move-labelled.yml
Labels: T-Task

#19679 Document feature_spaces_metaspaces
  docs/labs.md
  element.io/develop/config.json
Labels: T-Task

#19767 Issue automation workflow updates
  .github/workflows/triage-move-labelled.yml
  .github/workflows/triage-priority-bugs.yml
Labels: T-Other

#19911 Review requests workflow
  .github/workflows/triage-move-review-requests.yml
Labels: T-Task

#19926 Move workflow env sections into steps for PR workflow
  .github/workflows/triage-move-review-requests.yml
Labels: T-Task

#19969 Upgrade allchange to 1.0.6
  package.json
  yarn.lock
Labels: T-Task
