Repository element-hq/element-web, pull requests merged in 2021-12, with the labels that each got.

#19700 Document feature_breadcrumbs_v2
  docs/labs.md
Labels: T-Task

#19976 Issue workflow improvements
  .github/workflows/triage-move-labelled.yml
  .github/workflows/triage-move-unlabelled.yml
  .github/workflows/triage-priority-bugs.yml
Labels: T-Task, A-Developer-Experience

#20023 Fix widget-api dependency with a react-sdk upgrade
  yarn.lock
Labels: T-Task

#20027 Improve platform types
  src/vector/platform/ElectronPlatform.tsx
Labels: T-Task

#20032 Add support for the Indonesian language
  scripts/copy-res.js
Labels: T-Enhancement

#19754 Simple static location sharing
  docs/config.md
  docs/labs.md
  src/vector/index.html
  test/jest-mocks.js
Labels: T-Enhancement

#20112 Update issue automation for the Delight team
  .github/workflows/triage-move-labelled.yml
Labels: T-Task, A-Developer-Experience

#20113 add aria-hidden and alt for preload svg images
  src/vector/index.html
Labels: T-Task

#20117 Add automation to move message bubbles issues to message bubbles board
  .github/workflows/triage-move-labelled.yml
Labels: T-Task, A-Developer-Experience

#20120 Fix graphql warning for wrong types in workflows
  .github/workflows/triage-move-labelled.yml
  .github/workflows/triage-move-review-requests.yml
Labels: T-Task, A-Developer-Experience

#19532 Fix imports to work with new lint rules
  package.json
  src/vector/app.tsx
  src/vector/index.ts
  src/vector/init.tsx
  src/vector/jitsi/index.ts
  src/vector/mobile_guide/index.ts
  src/vector/platform/PWAPlatform.ts
  src/vector/platform/VectorBasePlatform.ts
  src/vector/platform/WebPlatform.ts
  src/vector/rageshakesetup.ts
  yarn.lock
Labels: T-Task

#19699 Document feature_spotlight
  docs/labs.md
Labels: T-Task

#20131 Update yarn.lock
  package.json
  yarn.lock
Labels: T-Task

#20157 Update Typescript to 4.5
  package.json
  yarn.lock
Labels: T-Task

#20160 update olm to 3.2.8
  package.json
  yarn.lock
Labels: T-Task

#20159 Update trigger for PR workflow
  .github/workflows/triage-move-review-requests.yml
Labels: T-Task, A-Developer-Experience

#20029 Include Vietnamese language
  scripts/copy-res.js
Labels: T-Enhancement

#20234 Ensure group audio-only calls don't switch on the webcam on join
  src/vector/jitsi/index.ts
Labels: T-Defect

#20251 add docs for UIFeature.TimelineEnableRelativeDates
  docs/config.md
Labels: T-Task
