Repository element-hq/element-web, pull requests merged in 2022-07, with the labels that each got.

#22714 Fix font preloading causing errors on non-root deployments
  src/vector/index.html
Labels: T-Defect

#21703 Wire up module loading to application startup
  .eslintignore
  .eslintrc.js
  .gitignore
  build_config.sample.yaml
  docs/modules.md
  module_system/BuildConfig.ts
  module_system/installer.ts
  module_system/scripts/install.ts
  package.json
  src/vector/index.ts
  src/vector/init.tsx
  tsconfig.module_system.json
  yarn.lock
Labels: T-Task

#22740 Add node to the tsconfig settings for the module system
  tsconfig.module_system.json
Labels: T-Task

#22286 Enable URL tooltips on hover for Element Desktop
  src/vector/platform/ElectronPlatform.tsx
Labels: T-Enhancement

#22802 Write additional tests
  src/favicon.ts
  src/vector/init.tsx
  src/vector/platform/IPCManager.ts
  src/vector/platform/VectorBasePlatform.ts
  src/vector/platform/WebPlatform.ts
  src/vector/rageshakesetup.ts
  src/vector/routing.ts
  test/unit-tests/vector/getconfig-test.ts
  test/unit-tests/vector/platform/PWAPlatform-test.ts
  test/unit-tests/vector/platform/WebPlatform-test.ts
Labels: T-Task

#22806 Remove the ability to hide yourself in video rooms
  src/vector/jitsi/index.ts
Labels: T-Defect

#22816 Upload artifact from develop build job
  .github/workflows/build_develop.yml
Labels: T-Task

#22810 Hide screenshare button in video rooms on Desktop
  src/vector/jitsi/index.ts
  src/vector/platform/ElectronPlatform.tsx
Labels: T-Enhancement

#22793 Add a script to check for dead code
  package.json
  scripts/analyse_unused_exports.js
  yarn.lock
Labels: T-Task

#22820 To consider develop built, block on static analysis & tests
  .github/workflows/build_develop.yml
Labels: T-Task

#22769 Rename PostCSS files to `.pcss`
  .github/workflows/build.yml
  .github/workflows/static_analysis.yaml
  .stylelintrc.js
  docs/theming.md
  package.json
  res/css/structures/ErrorView.pcss
  src/async-components/structures/CompatibilityView.tsx
  src/async-components/structures/ErrorView.tsx
  src/vector/jitsi/index.pcss
  src/vector/jitsi/index.ts
  webpack.config.js
  yarn.lock
Labels: T-Task

#22818 Add docs for feature_favourite_messages
  docs/labs.md
Labels: T-Task

#22858 Disable tests relying on old room directory
  test/app-tests/joining-test.tsx
Labels: T-Task

#22906 bump olm version to match bump in matrix-js-sdk
  package.json
  yarn.lock
Labels: T-Task

#22829 Improve dead code detection
  scripts/analyse_unused_exports.js
Labels: T-Task

#22937 Move major and critical threads to delight board
  .github/workflows/triage-labelled.yml
Labels: T-Task

#22930 Disallow invalid inline style comments in stylesheets
  package.json
  src/vector/jitsi/index.pcss
  webpack.config.js
  yarn.lock
Labels: T-Task

#22220 Add support for disabling spell check
  src/vector/platform/ElectronPlatform.tsx
Labels: T-Enhancement

#22946 Update jest to v28
  package.json
  yarn.lock
Labels: T-Task

#22948 Improve auth aria attributes and semantics
  src/components/views/auth/VectorAuthFooter.tsx
  src/components/views/auth/VectorAuthHeaderLogo.tsx
Labels: T-Enhancement

#22947 Add webpack react-sdk resolve alias
  webpack.config.js
Labels: T-Task

#22026 Rework dockerhub builds
  .github/workflows/dockerhub.yaml
  Dockerfile
  scripts/docker-link-repos.sh
  scripts/docker-package.sh
Labels: T-Task
