Repository element-hq/element-web, pull requests merged in 2022-04, with the labels that each got.

#21653 Fix typo in translation docs
  docs/translating.md
Labels: T-Task

#21650 Fix stuck persistence of Jitsi widgets
  src/vector/jitsi/index.ts
Labels: T-Defect, X-Release-Blocker

#21665 Avoid flashing the Jitsi prejoin screen at the user before skipping it
  src/vector/jitsi/index.scss
  src/vector/jitsi/index.ts
Labels: T-Defect

#21697 Handle forced disconnects from Jitsi
  src/vector/jitsi/index.ts
Labels: T-Enhancement

#21480 Document `feature_message_right_click_context_menu`
  docs/labs.md
Labels: T-Task

#21746 Show a lobby screen in video rooms
  src/vector/jitsi/index.ts
Labels: T-Enhancement

#21849 Upgrade dependencies
  yarn.lock
Labels: T-Task

#21995 Fix Jitsi Meet getting wedged at startup in some cases
  src/vector/jitsi/index.ts
Labels: T-Defect

#21999 Fix label triage automation
  .github/workflows/triage-labelled.yml
Labels: T-Task
