Repository element-hq/element-web, pull requests merged in 2022-01, with the labels that each got.

#20437 Fix spacing errors
  package.json
  yarn.lock
Labels: T-Task

#20464 Fix git protocol usage for CI
  scripts/fetch-develop.deps.sh
Labels: T-Task

#20471 Print out requested teams in review-request workflow
  .github/workflows/triage-move-review-requests.yml
Labels: T-Task

#20474 In review-request action, treat requested_teams as an array
  .github/workflows/triage-move-review-requests.yml
Labels: T-Task

#20477 Supply team name to review-request action
  .github/workflows/triage-move-review-requests.yml
Labels: T-Task

#20484 Disable Git interactive auth when fetching deps
  scripts/fetch-develop.deps.sh
Labels: T-Task

#20480 Remove extraneous dollar from review-requests action
  .github/workflows/triage-move-review-requests.yml
Labels: T-Task

#20487 Update default Jitsi URLs to meet.element.io
  config.sample.json
  docs/config.md
  docs/jitsi.md
  docs/kubernetes.md
  scripts/build-jitsi.js
Labels: T-Task

#20490 Yarn upgrade
  yarn.lock
Labels: T-Task

#20517 Use published matrix-web-i18n
  package.json
  yarn.lock
Labels: T-Task

#20515 Fix logic for removing Z-Labs tag with issue automation
  .github/workflows/triage-move-unlabelled.yml
Labels: T-Task, Z-Actions

#20405 Documentation for extensible events labs flag
  docs/labs.md
Labels: T-Task

#20539 Enable posthog on app.element.io
  element.io/app/config.json
Labels: T-Enhancement

#20599 Expect /capabilities after startClient in app tests
  test/app-tests/loading-test.tsx
Labels: T-Task

#20583 Update issue and PR automation
  .github/workflows/triage-labelled.yml
  .github/workflows/triage-move-review-requests.yml
  .github/workflows/triage-priority-bugs.yml
  .github/workflows/triage-unlabelled.yml
Labels: T-Task

#20638 Persist jitsi only after meeting is joined
  src/vector/jitsi/index.ts
Labels: T-Enhancement

#20639 Remove the documentation of the Polls labs feature
  docs/labs.md
Labels: T-Task

#20667 Quieten webpack-dev-server output so yarn start is less noisy
  package.json
Labels: T-Task

#20668 New config for maps
  docs/config.md
  docs/labs.md
  element.io/develop/config.json
Labels: T-Task

#20595 Improve the look of the keyboard settings tab
  src/i18n/strings/en_EN.json
  src/vector/platform/ElectronPlatform.tsx
Labels: T-Task

#20722 Add labs docs for right panel default open
  docs/labs.md
Labels: T-Task

#20735 Fix validation error in issue templates
  .github/ISSUE_TEMPLATE/bug-desktop.yml
  .github/ISSUE_TEMPLATE/bug-web.yml
Labels: T-Task

#20737 Update jitsi doc to specify minimum version
  docs/jitsi.md
Labels: T-Task

#20736 Update new issue page on GitHub
  .github/ISSUE_TEMPLATE/config.ylm
Labels: T-Task

#20734 Document use of .well-known for tile server and jitsi
  docs/config.md
Labels: T-Task

#20790 Support a config option to change the default device name
  docs/config.md
  src/vector/app.tsx
Labels: T-Enhancement, Sponsored

#20819 Yarn upgrade
  yarn.lock
Labels: T-Task

#20825 Document jump to date labs feature (MSC3030)
  docs/labs.md
Labels: A-Documentation
