Repository element-hq/element-web, pull requests merged in 2022-03, with the labels that each got.

#21242 labs doc for feature_location_share_pin_drop
  docs/labs.md
Labels: T-Task

#21222 Add docs for `logout_redirect_url`
  docs/config.md
Labels: T-Task, Sponsored

#21188 Add docs for custom_translations_url
  docs/config.md
Labels: T-Task, Sponsored

#21277 Install types for ua-parser-js
  package.json
  yarn.lock
Labels: T-Task

#21179 Add FTUE and WTF label automations to project boards
  .github/workflows/triage-labelled.yml
Labels: T-Task, A-Developer-Experience

#21339 add feature_location_share_live doc
  docs/labs.md
Labels: T-Task

#21364 Add lint for unused locals
  tsconfig.json
Labels: T-Task

#21422 Specified React version 🔧
  .eslintrc.js
Labels: T-Task

#21441 Remove duplicate security policy link from new issues page
  .github/ISSUE_TEMPLATE/config.yml
Labels: T-Task

#21429 Update SdkConfig usage to use new translation layer + update config.md docs
  config.sample.json
  docs/config.md
  docs/kubernetes.md
  docs/theming.md
  src/async-components/structures/CompatibilityView.tsx
  src/components/views/auth/VectorAuthFooter.tsx
  src/components/views/auth/VectorAuthHeaderLogo.tsx
  src/components/views/auth/VectorAuthPage.tsx
  src/vector/app.tsx
  src/vector/getconfig.ts
  src/vector/init.tsx
  src/vector/jitsi/index.ts
  src/vector/platform/ElectronPlatform.tsx
  src/vector/platform/VectorBasePlatform.ts
Labels: T-Task

#21484 Update nodejs version requirements
  README.md
Labels: T-Task

#21476 Voice rooms prototype
  docs/labs.md
  src/vector/jitsi/index.ts
Labels: X-Blocked

#21385 Delete documentation relating to legacy communities
  docs/labs.md
  webpack.config.js
Labels: T-Task

#21512 Add voice rooms to labs labels
  .github/workflows/triage-labelled.yml
  .github/workflows/triage-unlabelled.yml
Labels: T-Task

#21562 Update location of Settings.ts in labs docs
  docs/feature-flags.md
Labels: T-Task

#21582 Fix typo in labs label workflow
  .github/workflows/triage-unlabelled.yml
Labels: T-Task

#21590 Docs: Require creation of config.json as part of Getting Started
  README.md
Labels: T-Task

#21629 Update name of video rooms label
  .github/workflows/triage-labelled.yml
  .github/workflows/triage-unlabelled.yml
Labels: T-Task
