Repository element-hq/element-web, pull requests merged in 2022-02, with the labels that each got.

#20863 Remove the Location Sharing labs feature
  docs/labs.md
Labels: T-Task

#20845 Document `uisi_autorageshake_app` config option
  docs/config.md
Labels: T-Task

#20895 Enable new search experience by default on Develop & Nightly
  element.io/develop/config.json
Labels: T-Task

#20985 Yarn upgrade
  yarn.lock
Labels: T-Task

#21042 Switch to IPC channel for `getDesktopCapturerSources`
  src/vector/platform/ElectronPlatform.tsx
Labels: T-Task

#21046 Remove postcss-extend
  package.json
  webpack.config.js
  yarn.lock
Labels: T-Task

#21079 Add map_style_url to config for app.element.io
  element.io/app/config.json
Labels: T-Defect

#21078 Provide sample config for the map_style_url
  config.sample.json
Labels: T-Task

#21080 Provide sample config for the map_style_url
  config.sample.json
Labels: T-Defect

#21090 Deprecate Piwik/Matomo support
  docs/config.md
Labels: T-Task

#21102 Fix command key missing in keyboard shortcuts tab
  src/vector/platform/ElectronPlatform.tsx
Labels: T-Defect

#21108 Tweak webpack config around stubbing node modules
  webpack.config.js
Labels: T-Task

#21124 Add Modernizr check for ResizeObserver
  .modernizr.json
  package.json
  src/vector/modernizr.js
  yarn.lock
Labels: T-Task

#21093 Docs for labs flag: Show only current profiles
  docs/labs.md
Labels: T-Task

#20789 Updated the login logo.
  res/themes/element/img/logos/element-logo.svg
  res/welcome/images/logo.svg
Labels: T-Enhancement

#21132 Keybinding code unification #3
  src/i18n/strings/en_EN.json
  src/vector/platform/ElectronPlatform.tsx
Labels: T-Task

#21189 Make customisations (and general file overrides) easier to specify
  docs/customisations.md
  webpack.config.js
Labels: T-Task, Sponsored

#21190 Add a config.json option to skip the built-in Jitsi welcome screen
  docs/config.md
  src/vector/jitsi/index.ts
Labels: T-Enhancement, Sponsored
