Repository element-hq/element-web, pull requests merged in 2022-10, with the labels that each got.

#23443 Add Element Call `brand`
  config.sample.json
  docs/config.md
Labels: T-Enhancement

#23431 Add Element Call participant limit
  config.sample.json
  docs/config.md
Labels: T-Enhancement

#23457 Device manager - tweak string formatting of default device name
  src/i18n/strings/en_EN.json
  src/vector/platform/ElectronPlatform.tsx
  src/vector/platform/IPCManager.ts
  src/vector/platform/WebPlatform.ts
  test/unit-tests/vector/platform/ElectronPlatform-test.ts
  test/unit-tests/vector/platform/WebPlatform-test.ts
Labels: T-Enhancement

#23467 Make bash scripts exit on error rather than continue
  scripts/fetch-develop.deps.sh
  scripts/genflags.sh
  scripts/get-version-from-git.sh
  scripts/layered.sh
  scripts/make-icons.sh
  scripts/normalize-version.sh
Labels: T-Task

#23468 Make ErrorView & CompatibilityView scrollable
  res/css/structures/ErrorView.pcss
Labels: T-Defect

#23427 Move from `browser-request` to `fetch`
  package.json
  src/vector/app.tsx
  src/vector/getconfig.ts
  src/vector/platform/WebPlatform.ts
  test/app-tests/loading-test.tsx
  test/unit-tests/vector/getconfig-test.ts
  test/unit-tests/vector/platform/WebPlatform-test.ts
  yarn.lock
Labels: T-Task

#23473 Trim /version file response
  src/vector/platform/WebPlatform.ts
Labels: T-Task

#23477 Fix dockerhub builds
  Dockerfile
Labels: T-Task

#23474 Fix tests and convert to RTL
  .eslintrc.js
  package.json
  src/vector/platform/WebPlatform.ts
  test/.eslintrc.js
  test/app-tests/loading-test.tsx
  test/jest-mocks.ts
  test/test-utils.ts
  test/unit-tests/vector/getconfig-test.ts
  test/unit-tests/vector/platform/ElectronPlatform-test.ts
  test/unit-tests/vector/platform/WebPlatform-test.ts
  test/unit-tests/vector/url_utils-test.ts
  tsconfig.json
  yarn.lock
Labels: T-Task

#23472 Update enhancement issue template
  .github/ISSUE_TEMPLATE/enhancement.yml
Labels: T-Task

#23480 Add automation for a PS feature team
  .github/workflows/triage-labelled.yml
Labels: T-Task

#23489 Update documentation on how to disable integration managers
  docs/config.md
Labels: T-Task, A-Documentation, Z-Community-PR

#23506 Stub out crypto imports in node
  webpack.config.js
Labels: T-Task

#23577 Fix config.json failing to load for Jitsi wrapper in non-root deployment
  package.json
  src/vector/jitsi/index.ts
  yarn.lock
Labels: T-Defect

#23490 Update issue automation for design
  .github/workflows/triage-labelled.yml
Labels: T-Task

#23585 Add issue automation for the VoIP team
  .github/workflows/triage-labelled.yml
Labels: T-Task

#23410 Document voice_broadcast.chunk_length
  docs/config.md
Labels: T-Task

#23602 Run dockerhub builder stage without emulation
  Dockerfile
Labels: T-Task

#23609 Update issue automation for labs features
  .github/workflows/triage-labelled.yml
Labels: T-Task

#23630 Change label in automation to for the rich text editor
  .github/workflows/triage-labelled.yml
Labels: T-Task

#23633 Constrain webpack config for `olm.wasm`
  webpack.config.js
Labels: T-Task

#23644 Add issue automation to tidy Help Wanted
  .github/workflows/triage-labelled.yml
Labels: T-Task
