Repository element-hq/element-web, pull requests merged in 2022-05, with the labels that each got.

#22035 Prune i18n files
  src/i18n/strings/eo.json
  src/i18n/strings/is.json
  src/i18n/strings/pt_BR.json
Labels: T-Task

#22053 Improve wording in the labs docs page
  docs/labs.md
Labels: T-Task

#22060 Fully close Jitsi conferences on errors
  src/vector/jitsi/index.ts
Labels: T-Defect

#22092 Add 'Choosing an issue to work on' doc
  README.md
  docs/choosing-an-issue.md
Labels: A-Documentation

#22101 Remove docs for now-defunct labs flags
  docs/labs.md
Labels: T-Task

#22115 Update config.md
  docs/config.md
Labels: T-Task

#22125 Fix video rooms sometimes connecting muted when they shouldn't
  src/vector/jitsi/index.ts
Labels: T-Defect

#22172 Make pull_request.yaml between the layers consistent and fix enforce labels
  .editorconfig
  .github/workflows/preview_changelog.yaml
  .github/workflows/pull_request.yaml
Labels: T-Task

#22194 Update unlabel workflow to check for card archive-ness
  .github/workflows/triage-unlabelled.yml
Labels: T-Task

#22054 Run CI in Github Actions
  .editorconfig
  .github/workflows/build.yml
  .github/workflows/build_develop.yml
  .github/workflows/sentry-sourcemaps.yaml
  .github/workflows/sonarqube.yml
  .github/workflows/static_analysis.yaml
  .github/workflows/tests.yaml
  .github/workflows/triage-incoming.yml
  .github/workflows/triage-labelled.yml
  .github/workflows/triage-move-review-requests.yml
  .github/workflows/triage-priority-bugs.yml
  .github/workflows/triage-unlabelled.yml
  README.md
  package.json
  scripts/get-version-from-git.sh
  scripts/layered.sh
  scripts/yarn-sub.js
  sonar-project.properties
Labels: T-Task

#22224 Improve code as per Sonar suggestions
  res/decoder-ring/datatypes.js
  res/decoder-ring/decoder.js
  res/decoder-ring/index.html
  res/welcome.html
  src/vector/jitsi/index.ts
  src/vector/mobile_guide/index.html
  src/vector/mobile_guide/index.ts
  src/vector/platform/WebPlatform.ts
  src/vector/static/incompatible-browser.html
  src/vector/static/unable-to-load.html
  webpack.config.js
Labels: T-Task

#22225 Ignore decoder-ring for Sonar coverage
  sonar-project.properties
Labels: T-Task

#22247 Update weblateToCounterpart to be more resilient
  .github/workflows/static_analysis.yaml
  scripts/copy-res.js
Labels: T-Task, X-Release-Blocker

#22249 Revert "Sonarcloud check out upstream develop not fork develop"
  .github/workflows/sonarqube.yml
Labels: T-Task

#22260 Remove spaces to delight board automation
  .github/workflows/triage-labelled.yml
  .github/workflows/triage-priority-bugs.yml
Labels: T-Task

#22270 Patch Jitsi logs into rageshakes
  src/vector/jitsi/index.ts
Labels: T-Task

#22248 Consolidate i18n check into a reusable workflow
  .github/workflows/static_analysis.yaml
Labels: T-Task

#22301 Stop Jitsi if we time out while connecting to a video room
  src/vector/jitsi/index.ts
Labels: T-Defect

#22295 Option to disable hardware acceleration on Element Desktop
  src/vector/platform/ElectronPlatform.tsx
Labels: T-Enhancement

#22321 Fix wrongly using github.ref in workflow_run actions concurrency
  .github/workflows/sonarqube.yml
Labels: T-Task

#22255 Remove stale release.sh parameter for no-jsdoc
  release.sh
Labels: T-Task

#22353 Work around a Jitsi log handling crash
  src/vector/jitsi/index.ts
Labels: T-Defect

#22360 Fix gha concurrency conditions
  .github/workflows/pull_request.yaml
Labels: T-Task

#22358 Make Lao translation available
  scripts/copy-res.js
Labels: T-Enhancement

#22352 Show a dialog when Jitsi encounters an error
  src/vector/jitsi/index.ts
Labels: T-Enhancement

#22371 unit test WebPlatform
  .gitignore
  test/unit-tests/vector/platform/WebPlatform-test.ts
Labels: T-Task

#22373 unit test getVectorConfig
  test/unit-tests/vector/getconfig-test.ts
  test/unit-tests/vector/platform/WebPlatform-test.ts
Labels: T-Task

#22395 matrix-mock-request to 2.0
  package.json
  yarn.lock
Labels: T-Task

#22397 Add /coverage to .gitignore
  .gitignore
Labels: T-Task

#22396 Github Actions pull_request synchronize runs on PR open anyway
  .github/workflows/pull_request.yaml
Labels: T-Task

#22348 Disable no-non-null assertions lint rule
  .eslintrc.js
Labels: T-Task

#21066 Document custom home view
  docs/config.md
  docs/custom-home.md
Labels: T-Enhancement
