Repository element-hq/element-web, pull requests merged in 2022-06, with the labels that each got.

#22414 Remove Z-IA issues to delight board automation
  .github/workflows/triage-labelled.yml
Labels: T-Task

#22452 Put web app team issues in the board
  .github/workflows/triage-assigned.yml
Labels: T-Task

#22451 Clean up closed issues (duplicates and rageshakes)
  .github/workflows/issue_closed.yml
Labels: T-Task

#22409 Switch to composite actions for pr_details and sonarqube
  .github/workflows/sonarqube.yml
Labels: T-Task

#21671 Add docs for feature_html_topic labs flag
  docs/labs.md
Labels: T-Task

#22474 Add CI to improve experience for community
  .github/workflows/pull_request.yaml
Labels: T-Task

#22482 Pass missing ci secret
  .github/workflows/pull_request.yaml
Labels: T-Task

#21962 Release video rooms as a beta feature
  docs/labs.md
  element.io/develop/config.json
Labels: T-Task

#22525 Work around a Jitsi bug with display name encoding
  src/vector/jitsi/index.ts
Labels: T-Defect

#22491 Abstract electron settings properly to avoid boilerplate-hell
  src/i18n/strings/en_EN.json
  src/vector/platform/ElectronPlatform.tsx
  src/vector/platform/IPCManager.ts
  src/vector/platform/PWAPlatform.ts
  src/vector/platform/SeshatIndexManager.ts
  src/vector/platform/VectorBasePlatform.ts
  src/vector/platform/WebPlatform.ts
Labels: T-Task

#22561 Skip running jobs on fork `develop` where they lack secrets
  .github/workflows/build_develop.yml
Labels: T-Task

#22577 Workflow: Move WAT issues to In Progress rather than Ready when assigned
  .github/workflows/triage-assigned.yml
Labels: T-Task

#22612 Add docs `feature_exploring_public_spaces`
  docs/labs.md
Labels: T-Task

#22660 Connect to Jitsi unmuted by default
  src/vector/jitsi/index.ts
Labels: T-Defect

#22665 Reduce video rooms log spam
  src/vector/jitsi/index.ts
Labels: T-Defect

#22664 Add support for switching layouts in the Jitsi wrapper
  src/vector/jitsi/index.ts
Labels: T-Enhancement

#22666 Update matrix-web-i18n
  package.json
  yarn.lock
Labels: T-Task
