Repository element-hq/element-web, pull requests merged in 2023-10, with the labels that each got.

#26262 Improve config.md docs on `custom_translations_url`
  docs/config.md
Labels: T-Task

#26287 Bump matrix-web-i18n to 3.1.3 for KEY_SEPARATOR
  package.json
  yarn.lock
Labels: T-Defect

#26307 vector-im/element-x-ios/issues/1824 - Convert the apple-app-site-association file to a newer format…
  res/apple-app-site-association
Labels: T-Enhancement

#26325 Remove former PS teams from issue automation
  .github/workflows/triage-labelled.yml
Labels: T-Task

#26328 Automatically add labeled issues to tech debt project
  .github/workflows/triage-labelled.yml
Labels: T-Task

#26329 Remove trailing ||
  .github/workflows/triage-labelled.yml
Labels: T-Task

#26336 Update Linux Kernel link in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: T-Task, Z-Community-PR

#26359 Remove hardcoded defaults and update manifest.json
  res/manifest.json
  src/async-components/structures/CompatibilityView.tsx
Labels: T-Task

#26362 Run build workflow in CI on the windows & macos also
  .github/workflows/build.yml
Labels: T-Task

#26368 Update the Element Call unstable URL
  element.io/develop/config.json
Labels: T-Task

#26367 Set up mdbook in github pages
  .github/workflows/docs.yml
  .gitignore
  book.toml
  docs/SUMMARY.md
Labels: T-Task

#26395 Correctly fill window.matrixChat even when a Wrapper module is active
  src/vector/app.tsx
  src/vector/init.tsx
  test/app-tests/server-config-test.ts
  test/app-tests/wrapper-test.tsx
Labels: T-Enhancement, Z-Community-PR

#26398 Add automation to move Element-R issues to crypto board
  .github/workflows/triage-labelled.yml
Labels: T-Task

#26324 Adds labs label to Element R issues
  .github/workflows/triage-labelled.yml
Labels: T-Task

#26403 docs: fixed multiple typos
  docs/config.md
  docs/e2ee.md
  docs/labs.md
  docs/translating-dev.md
Labels: T-Task, Z-Community-PR

#26400 OIDC: document config
  docs/SUMMARY.md
  docs/oidc.md
Labels: T-Task

#26430 Update triage-assigned.yml
  .github/workflows/triage-assigned.yml
Labels: T-Task

#26291 Enable rust cryptography on develop.element.io
  element.io/develop/config.json
Labels: T-Task

#26446 Document `feedback.new_issue_url` & `feedback.existing_issues_url`
  docs/config.md
Labels: T-Task

#26434 Iterate build_debian.yaml workflow
  .github/workflows/build_debian.yaml
Labels: T-Task

#26216 Update webpack to 4.47.0 / webpack-cli to 4.10.0 / webpack-dev-server 4.15.1
  package.json
  webpack.config.js
  yarn.lock
Labels: T-Task

#26426 Add mdbook-mermaid
  .github/workflows/docs.yml
  .gitignore
  book.toml
  docs/app-load.md
Labels: T-Task

#26461 Use olm from default npm registry, since it's there now
  package.json
  yarn.lock
Labels: T-Task

#26392 Release prep script for cutting branches
  .github/workflows/release_prepare.yml
Labels: T-Task
