Repository element-hq/element-web, pull requests merged in 2023-05, with the labels that each got.

#25232 Improve quality of Typescripting
  src/async-components/structures/CompatibilityView.tsx
  src/components/views/auth/VectorAuthFooter.tsx
  src/favicon.ts
  src/vector/index.ts
  src/vector/platform/VectorBasePlatform.ts
  tsconfig.json
Labels: T-Task

#25276 Wait for login screen to appear in loading-test
  test/app-tests/loading-test.tsx
Labels: T-Task

#25287 Ensure we actually wait for the login form to appear in loading-test
  test/app-tests/loading-test.tsx
Labels: T-Task

#25312 Add error notification audio
  src/vector/index.html
Labels: T-Task

#25339 Allow welcome.html logo to be replaced by config
  res/welcome.html
  res/welcome/images/logo.svg
Labels: T-Enhancement

#25337 Improve bundle size and add webpack-bundle-analyzer
  package.json
  webpack.config.js
  yarn.lock
Labels: T-Task

#25351 Handle trailing dot FQDNs for domain-specific config.json files
  src/vector/getconfig.ts
Labels: T-Defect

#25353 Fix analyse:webpack-bundles script
  package.json
Labels: T-Task

#25377 Increase yarn timeout
  Dockerfile
Labels: T-Task

#25336 vector/index.html: Allow fetching blob urls
  src/vector/index.html
Labels: T-Enhancement, Z-Community-PR

#25427 Track release blockers in Matrix room header
  .github/workflows/pending-reviews.yaml
Labels: T-Task
