Repository element-hq/element-web, pull requests merged in 2023-03, with the labels that each got.

#24696 Update yarn.lock
  package.json
  yarn.lock
Labels: T-Task

#24708 Depend on a non-broken version of matrix-react-sdk
  yarn.lock
Labels: T-Task

#24642 Bump @matrix-org/react-sdk-module-api to 0.0.4
  package.json
  yarn.lock
Labels: T-Task

#24721 Remove hosting link provider from Element (documentation)
  docs/config.md
Labels: T-Task

#24732 Remove items incorrectly included in changelog for 1.11.24
  CHANGELOG.md
Labels: T-Task

#24736 package.json: Remove --host override
  package.json
Labels: T-Task, Z-Community-PR

#24767 Remove deprecated stylelint rules which are handled by prettier
  .stylelintrc.js
  package.json
Labels: T-Task

#24777 Fix cloudflare action pointing at commit hash instead of tag
  .github/workflows/build_develop.yml
Labels: T-Defect, A-Developer-Experience

#24766 Remove unused dev dependency
  package.json
  yarn.lock
Labels: T-Task

#24786 Pin versions of third-party github actions
  .github/workflows/backport.yml
  .github/workflows/dockerhub.yaml
  .github/workflows/static_analysis.yaml
  .github/workflows/tests.yaml
Labels: T-Task

#24809 Use forked wait-on-check-action
  .github/workflows/build_develop.yml
Labels: T-Task

#24820 Add API params to mute audio and/or video in Jitsi calls by default
  src/vector/jitsi/index.ts
Labels: T-Enhancement, Z-Community-PR

#24842 Update safari support policy
  README.md
Labels: T-Task

#24847 Update apple-app-site-association
  res/apple-app-site-association
Labels: T-Task

#24872 Update matrix-widget-api
  package.json
  yarn.lock
Labels: T-Task

#16940 Allow desktop app to expose recent rooms in UI integrations
  src/vector/platform/ElectronPlatform.tsx
  test/unit-tests/vector/platform/ElectronPlatform-test.ts
Labels: T-Enhancement

#24646 Use a newly generated access_token while joining Jitsi
  src/vector/jitsi/index.ts
Labels: T-Defect, Z-Community-PR

#24895 Enable blank issue template
  .github/ISSUE_TEMPLATE/config.yml
Labels: T-Task

#24978 Delete .sentryclirc
  .sentryclirc
Labels: T-Task

#24975 Update changelog for v1.11.26 now the security issue is public
  CHANGELOG.md
Labels: T-Task

#24990 `code_style.md`: Add notes on comments
  code_style.md
Labels: T-Task

#24989 Fix concurrency conflict
  .github/workflows/dockerhub.yaml
Labels: T-Task

#25002 Replace newTranslatableError with UserFriendlyError
  package.json
  src/vector/app.tsx
  yarn.lock
Labels: T-Task
