Repository element-hq/element-web, pull requests merged in 2023-07, with the labels that each got.

#25700 Align develop.e.io cloudflare pages headers with other deploys
  .github/cfp_headers
Labels: T-Task

#25712 Tweak branch matching to allow not applying outside of PRs for matrix-analytics-events
  scripts/layered.sh
Labels: T-Task

#25724 Enable strictNullChecks and noImplicitAny
  tsconfig.json
Labels: T-Task

#25729 Enable strictPropertyInitialization
  tsconfig.json
Labels: T-Task

#25730 Enable strictFunctionTypes
  package.json
  tsconfig.json
  yarn.lock
Labels: T-Task

#25735 Enable strictPropertyInitialization
  .github/workflows/static_analysis.yaml
  tsconfig.json
Labels: T-Task

#25736 Deprecate customisations in favour of Module API
  docs/customisations.md
  webpack.config.js
Labels: T-Deprecation

#25682 Allow default_server_config as a fallback config
  docs/config.md
  src/i18n/strings/en_EN.json
  src/vector/app.tsx
  src/vector/mobile_guide/index.ts
  test/app-tests/server-config-test.ts
Labels: T-Enhancement, Z-Community-PR

#25725 Utility automation for updating topics as part of release process
  .github/workflows/update-topics.yaml
Labels: T-Task

#19695 Add `default_server_config` fallback to element.io configs
  element.io/app/config.json
  element.io/develop/config.json
Labels: T-Task

#25747 Delete redundant make-icons.sh
  scripts/make-icons.sh
Labels: T-Task

#25688 OIDC: store initial screen in session storage
  src/vector/app.tsx
  src/vector/routing.ts
  test/unit-tests/vector/routing-test.ts
Labels: T-Enhancement

#25769 Update logging ignore list comment
  src/vector/rageshakesetup.ts
Labels: T-Task

#25772 Remove rageshake server from config.sample.json
  config.sample.json
Labels: T-Task

#25800 Deprecate camelCase config options
  docs/config.md
Labels: T-Deprecation

#25802 Switch to the new `session` API for screen-sharing
  src/@types/global.d.ts
  src/vector/platform/ElectronPlatform.tsx
  test/unit-tests/vector/platform/ElectronPlatform-test.ts
Labels: T-Task

#25783 Test: don't unmount `MatrixChat` before setup is finished
  test/app-tests/loading-test.tsx
Labels: T-Task

#25813 Correct Jitsi preferred_domain property
  docs/jitsi.md
Labels: T-Defect

#25814 Remove redundant dependencies
  package.json
  webpack.config.js
Labels: T-Task

#25823 Removing stale labs flag
  docs/labs.md
  element.io/develop/config.json
Labels: T-Task

#25833 Avoid using deprecated config.json key casing
  element.io/app/config.json
  element.io/develop/config.json
Labels: T-Task
