Repository element-hq/element-web, pull requests merged in 2023-08, with the labels that each got.

#25890 Document 'feature_new_room_decoration_ui'
  docs/labs.md
Labels: T-Task

#25906 Transpile @vector-im/compound-web with babel
  webpack.config.js
Labels: T-Task

#25198 Package release builds of element-web in package.element.io debs
  .github/workflows/build_debian.yaml
  debian/conffiles
  debian/control
Labels: T-Enhancement

#25915 Remove feature_right_panel_default_open
  docs/labs.md
Labels: T-Task

#25923 Update labs.md for knock rooms
  docs/labs.md
Labels: T-Enhancement, Z-Community-PR

#25928 Update setupFilesAfterEnv to TS
  jest.config.ts
Labels: T-Task

#25898 Fix tests for Matrix v1.1 requirement
  test/app-tests/loading-test.tsx
  test/app-tests/server-config-test.ts
Labels: T-Task

#25953 Remove redundant `makeRegistrationUrl` prop
  src/vector/app.tsx
  test/app-tests/loading-test.tsx
Labels: T-Task

#25970 Switch to nested object pluralisation format for i18n files
  package.json
  scripts/copy-res.js
  src/i18n/strings/basefile.json
  yarn.lock
Labels: T-Task

#25978 Tidy and improve dev scripts
  package.json
  scripts/analyse_unused_exports.ts
  scripts/build-jitsi.ts
  scripts/check-i18n.pl
  yarn.lock
Labels: T-Task

#25998 Allow external assets loading
  webpack.config.js
Labels: T-Task

#25997 Fix path separator for Windows based systems
  webpack.config.js
Labels: T-Defect

#25986 Bump @matrix-org/react-sdk-module-api from 1.0.0 to 2.0.0
  module_system/installer.ts
  package.json
  webpack.config.js
  yarn.lock
Labels: T-Task, Z-Community-PR

#25991 Remove `Exploring public spaces` from labs.md
  docs/labs.md
Labels: T-Task

#26001 Simplify languages.json file and grab language names from Intl
  scripts/copy-res.js
Labels: T-Task

#26048 Revert "Update react-types (#25256)"
  package.json
  yarn.lock
Labels: T-Task

#25537 Add support for rendering a custom wrapper around Element
  package.json
  src/vector/app.tsx
  test/app-tests/loading-test.tsx
  test/app-tests/wrapper-test.tsx
  test/test-utils.ts
  yarn.lock
Labels: T-Enhancement, A-Timesheet-1

#26069 Fix compound external assets path in bundle
  webpack.config.js
Labels: T-Defect

#26082 Make SVGR icons use forward ref
  webpack.config.js
Labels: T-Enhancement
