Repository element-hq/element-web, pull requests merged in 2023-06, with the labels that each got.

#25495 Redirect to the SSO page if `sso_redirect_options.on_welcome_page` is enabled and the URL hash is empty
  src/vector/app.tsx
Labels: T-Enhancement, Z-Community-PR

#25518 Add documentation for config to skip widget_build_url for DM rooms
  docs/config.md
Labels: T-Task

#25549 Document help_url and help_encryption_url
  docs/config.md
Labels: T-Task

#25605 Remove `feature_favourite_messages` as it is has been abandoned for now
  docs/labs.md
Labels: T-Task

#25609 Fix error when generating error for polling for updates
  src/vector/platform/WebPlatform.ts
Labels: T-Defect

#25617 Deprecate new breadcrumbs
  docs/labs.md
Labels: T-Task

#25636 Point develop.element.io to our Element Call + LiveKit experiment
  element.io/develop/config.json
Labels: T-Task

#25651 Revert "Point develop.element.io to our Element Call + LiveKit experiment"
  element.io/develop/config.json
Labels: T-Task

#25660 Point develop.element.io to our Element Call + LiveKit experiment
  element.io/develop/config.json
Labels: T-Task

#25662 Document `io.element.e2ee.force_disable`
  docs/e2ee.md
Labels: T-Task

#25664 OIDC: remove auth params from url after login attempt
  src/vector/app.tsx
Labels: T-Enhancement
