Repository element-hq/element-web, pull requests merged in 2023-01, with the labels that each got.

#24124 Align code_style.md with prettier
  code_style.md
Labels: T-Task

#24086 Use Identity Server v2 API for tests
  test/app-tests/loading-test.tsx
Labels: T-Task

#24150 Downgrade to style-loader 2 to regain Webpack 4 compatibility
  package.json
  yarn.lock
Labels: T-Task

#24152 Revert "Update dependency worker-loader to v3 (#24033)"
  package.json
  yarn.lock
Labels: T-Task

#24154 Explicitly set worker-loader's publicPath to webapp
  webpack.config.js
Labels: T-Task

#24156 Revert "Explicitly set worker-loader's publicPath to webapp"
  webpack.config.js
Labels: T-Task

#24159 Upgrade worker loader to v3 (with config fix to prevent bundling)
  package.json
  webpack.config.js
  yarn.lock
Labels: T-Task

#24160 Configure babel to transform logical assignment
  babel.config.js
Labels: T-Task

#23965 Stow more things in element-web-develop.element.io
  .github/workflows/build_develop.yml
Labels: T-Task

#24219 Update automation for new app team board
  .github/workflows/triage-assigned.yml
Labels: T-Task

#24225 Remove delight automation
  .github/workflows/triage-labelled.yml
Labels: T-Task

#24224 Document updated default `uisi_autorageshake_app`
  docs/config.md
Labels: T-Task

#22993 Move pin drop out of labs (PSG-664)
  docs/labs.md
Labels: T-Enhancement

#24317 Document the decoder ring
  CONTRIBUTING.md
Labels: T-Task

#24368 Include Janne in WAT assignment automation
  .github/workflows/triage-assigned.yml
Labels: T-Task

#24294 Jitsi requests 'requires_client' capability if auth token is provided
  src/vector/jitsi/index.ts
Labels: T-Defect, Z-Community-PR
