Repository element-hq/element-web, pull requests merged in 2023-02, with the labels that each got.

#23513 Description of QR code sign in labs feature
  docs/labs.md
Labels: T-Enhancement

#24428 Update config.md - these UIFeature flags died with communities
  docs/config.md
Labels: T-Task

#24483 Add some advice on good PR titles
  CONTRIBUTING.md
Labels: T-Task

#24488 labs.md: add notes about `feature_rust_crypto`
  docs/labs.md
Labels: T-Task

#24542 Remove Element Home ad links
  element.io/app/config.json
  element.io/develop/config.json
Labels: T-Task

#24553 Don't remove Z-Labs from A-Jump-To-Date
  .github/workflows/triage-labelled.yml
  .github/workflows/triage-unlabelled.yml
Labels: T-Task

#24584 Update webpack hash function for greater OSSL compat
  webpack.config.js
Labels: T-Task, X-Release-Blocker

#24564 yarn upgrade all eslint packages
  yarn.lock
Labels: T-Task

#24591 Remove reference to threads in labs
  docs/betas.md
  docs/labs.md
Labels: T-Task

#24610 Add issue automation for the Verticals Team
  .github/workflows/triage-labelled.yml
Labels: T-Task

#24609 Pass current language into Jitsi (#24609
  src/vector/jitsi/index.ts
Labels: T-Enhancement, Z-Community-PR

#21128 Fix frame-ancestors docs from none to self to not break Jitsi
  README.md
  docs/kubernetes.md
Labels: T-Task

#24630 Remove experimental PWA support for Firefox and Safari
  README.md
Labels: T-Enhancement

#24570 yarn upgrade all jest packages
  yarn.lock
Labels: T-Task

#24679 Pull reviews bot automation for Web App Team room
  .editorconfig
  .github/workflows/pending-reviews.yaml
Labels: T-Task
