Repository element-hq/element-web, pull requests merged in 2023-11, with the labels that each got.

#26399 Ship OpenCoDE variant to Dockerhub
  .github/workflows/dockerhub.yaml
  variants/openDesk/README.md
  variants/openDesk/build_config.yaml
  variants/openDesk/customisations.json
  variants/openDesk/customisations.json.license
Labels: T-Task

#26533 Ship element-web as a debian package
  .github/workflows/build_debian.yaml
  debian/.gitignore
  debian/control
Labels: T-Enhancement

#26534 Update @matrix-org/react-sdk-module-api
  package.json
  yarn.lock
Labels: T-Task, Z-Community-PR, Dependencies

#26517 Only update repo description once
  .github/workflows/dockerhub.yaml
Labels: T-Task

#26550 Run Localazy Download on a schedule 3 times a week instead of during release process
  .github/workflows/localazy_download.yaml
  docs/translating.md
Labels: T-Task

#26495 New release automations
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release-gitflow.yml
  .github/workflows/release.yml
Labels: T-Task

#26543 Remove unused dependencies and add transitive deps
  .prettierignore
  package.json
  yarn.lock
Labels: T-Task

#26593 Split copy-res into two phases during yarn start
  package.json
  scripts/copy-res.ts
Labels: T-Task

#26599 Replace copy/watching of non-language assets with copy-webpack-plugin
  package.json
  scripts/copy-res.ts
  src/@types/cpx.d.ts
  src/@types/loader-utils.d.ts
  webpack.config.js
  yarn.lock
Labels: T-Task

#26548 Add feature_disable_call_per_sender_encryption documentation (in labs.md)
  docs/labs.md
Labels: T-Enhancement

#26602 Add documentation around releases
  docs/SUMMARY.md
  docs/release.md
Labels: T-Task

#26229 Update to webpack 5
  jest.config.ts
  package.json
  recorder-worklet-loader.js
  scripts/copy-res.ts
  src/@types/loader-utils.d.ts
  src/vector/index.html
  src/vector/index.ts
  tsconfig.json
  webpack.config.js
  yarn.lock
Labels: T-Task

#26612 Set up rudimentary workflow for manually triggering label sync
  .github/labels.yml
  .github/workflows/sync-labels.yml
Labels: T-Task

#26616 Improve rendering style of markdown in the mdbook
  book.toml
  docs/css/custom.css
Labels: T-Task

#26621 Set up CI to lint workflows with action-validator
  .github/workflows/static_analysis.yaml
  package.json
  yarn.lock
Labels: T-Task

#26622 Add Jitsi SDK as a static resource and set up CI to update it on change
  .github/workflows/update-jitsi.yml
  .prettierignore
  package.json
  res/jitsi_external_api.min.js
  res/jitsi_external_api.min.js.LICENSE.txt
  scripts/build-jitsi.ts
  webpack.config.js
Labels: T-Task

#26630 Enable new room header by default on develop
  element.io/develop/config.json
Labels: T-Task

#26641 Adapt to renaming of release-action workflow
  .github/workflows/release.yml
Labels: T-Task

#26637 Improve Module API docs & example
  build_config.sample.yaml
  docs/modules.md
Labels: T-Task

#26672 Adapt label-sync workflow to new version of upstream workflow
  .github/labels.yml
  .github/workflows/sync-labels.yml
Labels: T-Task

#26673 Add missing labels for label sync
  .github/labels.yml
Labels: T-Task

#26674 Enable label sync workflow
  .github/workflows/sync-labels.yml
Labels: T-Task

#25885 Remove documentation for 'feature_state_counters'
  docs/labs.md
Labels: T-Task
