Repository element-hq/element-web, pull requests merged in 2024-09, with the labels that each got.

#28020 Switch to element's react-sdk fork
  scripts/fetch-develop.deps.sh
  scripts/layered.sh
Labels: T-Task

#28024 Change Licence
  CONTRIBUTING.md
  LICENSE
  LICENSE-AGPL-3.0
  LICENSE-GPL-3.0
  contribute.json
  jest.config.ts
  module_system/BuildConfig.ts
  module_system/installer.ts
  module_system/scripts/install.ts
  package.json
  recorder-worklet-loader.js
  res/css/structures/ErrorView.pcss
  scripts/genflags.sh
  src/@types/global.d.ts
  src/@types/jitsi-meet.d.ts
  src/@types/svg.d.ts
  src/async-components/structures/ErrorView.tsx
  src/components/views/auth/VectorAuthFooter.tsx
  src/components/views/auth/VectorAuthHeaderLogo.tsx
  src/components/views/auth/VectorAuthPage.tsx
  src/favicon.ts
  src/languageHandler.tsx
  src/serviceworker/index.ts
  src/vector/app.tsx
  src/vector/devcss.ts
  src/vector/getconfig.ts
  src/vector/index.ts
  src/vector/indexeddb-worker.ts
  src/vector/init.tsx
  src/vector/jitsi/index.pcss
  src/vector/jitsi/index.ts
  src/vector/platform/ElectronPlatform.tsx
  src/vector/platform/IPCManager.ts
  src/vector/platform/PWAPlatform.ts
  src/vector/platform/SeshatIndexManager.ts
  src/vector/platform/VectorBasePlatform.ts
  src/vector/platform/WebPlatform.ts
  src/vector/rageshakesetup.ts
  src/vector/routing.ts
  src/vector/url_utils.ts
  test/app-tests/server-config-test.ts
  test/app-tests/wrapper-test.tsx
  test/jest-mocks.ts
  test/setup/setupLanguage.ts
  test/test-utils.ts
  test/unit-tests/async-components/structures/ErrorView-test.tsx
  test/unit-tests/components/views/auth/VectorAuthFooter-test.tsx
  test/unit-tests/components/views/auth/VectorAuthHeaderLogo-test.tsx
  test/unit-tests/components/views/auth/VectorAuthPage-test.tsx
  test/unit-tests/favicon-test.ts
  test/unit-tests/vector/getconfig-test.ts
  test/unit-tests/vector/platform/ElectronPlatform-test.ts
  test/unit-tests/vector/platform/PWAPlatform-test.ts
  test/unit-tests/vector/platform/WebPlatform-test.ts
  test/unit-tests/vector/routing-test.ts
  test/unit-tests/vector/url_utils-test.ts
Labels: T-Task

#28034 Fix default_widget_container_height in sample config
  config.sample.json
Labels: T-Defect

#28035 Add doc for 'force_verification config option
  config.sample.json
  docs/config.md
Labels: T-Enhancement

#28040 Update icons to include transparency
  res/vector-icons/1024.png
  res/vector-icons/120.png
  res/vector-icons/1240x600.png
  res/vector-icons/150.png
  res/vector-icons/152.png
  res/vector-icons/180.png
  res/vector-icons/24.png
  res/vector-icons/300.png
  res/vector-icons/44.png
  res/vector-icons/50.png
  res/vector-icons/620x300.png
  res/vector-icons/76.png
  res/vector-icons/88.png
  res/vector-icons/apple-touch-icon-114.png
  res/vector-icons/apple-touch-icon-120.png
  res/vector-icons/apple-touch-icon-144.png
  res/vector-icons/apple-touch-icon-152.png
  res/vector-icons/apple-touch-icon-180.png
  res/vector-icons/apple-touch-icon-57.png
  res/vector-icons/apple-touch-icon-60.png
  res/vector-icons/apple-touch-icon-72.png
  res/vector-icons/apple-touch-icon-76.png
  res/vector-icons/mstile-150.png
  res/vector-icons/mstile-310.png
  res/vector-icons/mstile-310x150.png
  res/vector-icons/mstile-70.png
Labels: T-Defect

#28049 Replace `matrix.org/matrix-react-sdk` with `element-hq/matrix-react-sdk` in CI
  .github/release-drafter.yml
  .github/workflows/docs.yml
  .github/workflows/end-to-end-tests.yaml
  .github/workflows/pending-reviews.yaml
  .github/workflows/release_prepare.yml
Labels: T-Task

#28045 enable Element Call on develop.element.io
  element.io/develop/config.json
Labels: T-Task

#28053 Remove regexpunicodesets modernizr check
  src/vector/index.ts
Labels: T-Task

#28055 Add "Registration.mobileRegistrationHelper" config setting on develop.
  element.io/develop/config.json
Labels: T-Task

#28057 Disable pending reviews jobs for now
  .github/workflows/pending-reviews.yaml
Labels: T-Task

#28069 Update release docs for new repo
  docs/release.md
Labels: T-Task

#28070 Fix dependency dashboard issue number
  docs/release.md
Labels: T-Task

#28096 Update native OIDC callback url to be RFC8252 compliant
  src/vector/platform/ElectronPlatform.tsx
Labels: T-Defect

#28124 Don't add `labs` label for `A-Message-Pinning`
  .github/workflows/triage-labelled.yml
Labels: T-Task

#28113 Update docs to reflect that you can join calls without the labs flags
  docs/labs.md
Labels: T-Task
