Repository element-hq/element-web, pull requests merged in 2024-08, with the labels that each got.

#27884 Upgrade target to es2022
  babel.config.js
  tsconfig.json
  tsconfig.module_system.json
Labels: T-Task

#27891 Switch from `self` to `global` for service worker
  src/serviceworker/index.ts
Labels: T-Task

#27900 Update Element icons
  res/vector-icons/1024.png
  res/vector-icons/120.png
  res/vector-icons/1240x600.png
  res/vector-icons/150.png
  res/vector-icons/152.png
  res/vector-icons/180.png
  res/vector-icons/24.png
  res/vector-icons/300.png
  res/vector-icons/44.png
  res/vector-icons/50.png
  res/vector-icons/620x300.png
  res/vector-icons/76.png
  res/vector-icons/88.png
  res/vector-icons/apple-touch-icon-114.png
  res/vector-icons/apple-touch-icon-120.png
  res/vector-icons/apple-touch-icon-144.png
  res/vector-icons/apple-touch-icon-152.png
  res/vector-icons/apple-touch-icon-180.png
  res/vector-icons/apple-touch-icon-57.png
  res/vector-icons/apple-touch-icon-60.png
  res/vector-icons/apple-touch-icon-72.png
  res/vector-icons/apple-touch-icon-76.png
  res/vector-icons/mstile-150.png
  res/vector-icons/mstile-310.png
  res/vector-icons/mstile-310x150.png
  res/vector-icons/mstile-70.png
Labels: T-Defect

#27901 Fix develop build
  webpack.config.js
Labels: T-Task

#27904 Fix permissions in release tarballs
  scripts/package.sh
Labels: T-Defect

#27905 dos2unix more Docker scripts
  Dockerfile
Labels: T-Task

#27906 Update dependencies for MSC4157
  package.json
  yarn.lock
Labels: Dependencies

#27910 Update @vector-im/compound-design-tokens
  package.json
  res/css/structures/ErrorView.pcss
  yarn.lock
Labels: T-Task

#27922 Add docs for widget container height option
  config.sample.json
  docs/config.md
Labels: T-Enhancement

#27945 Replace old webpack-dev-server https arg
  package.json
Labels: T-Task, Z-Community-PR

#27972 Fix stale action not closing issues as expected
  .github/workflows/triage-stale-flaky-tests.yml
Labels: T-Task

#27979 Add `allowImportingTsExtensions` to tsconfig.json
  tsconfig.json
Labels: T-Task
