Repository element-hq/element-web, pull requests merged in 2024-11, with the labels that each got.

#20891 Specify a local address when exposing ports with Docker
  docs/install.md
Labels: T-Task

#28338 Remove boilerplate around dispatcher and settings watchers
  src/DeviceListener.ts
  src/PosthogAnalytics.ts
  src/Presence.ts
  src/components/structures/EmbeddedPage.tsx
  src/components/structures/LoggedInView.tsx
  src/components/structures/ThreadView.tsx
  src/components/structures/UserMenu.tsx
  src/components/views/dialogs/RoomSettingsDialog.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/messages/DateSeparator.tsx
  src/components/views/messages/MImageBody.tsx
  src/components/views/messages/MVideoBody.tsx
  src/components/views/right_panel/TimelineCard.tsx
  src/components/views/rooms/AppsDrawer.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/RoomList.tsx
  src/components/views/rooms/RoomSublist.tsx
  src/components/views/rooms/RoomTile.tsx
  src/components/views/rooms/Stickerpicker.tsx
  src/components/views/settings/FontScalingPanel.tsx
  src/components/views/settings/IntegrationManager.tsx
  src/components/views/settings/SetIdServer.tsx
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
  src/components/views/voip/LegacyCallView.tsx
  src/dispatcher/dispatcher.ts
  src/mjolnir/Mjolnir.ts
  src/models/Call.ts
  src/settings/SettingsStore.ts
  src/settings/watchers/FontWatcher.ts
  src/settings/watchers/ThemeWatcher.ts
  src/stores/AsyncStore.ts
  src/stores/AsyncStoreWithClient.ts
  src/stores/OwnBeaconStore.ts
  src/stores/ReadyWatchingStore.ts
  src/stores/widgets/WidgetLayoutStore.ts
  test/unit-tests/DeviceListener-test.ts
Labels: T-Task

#28350 Remove unused Security customisations module
  docs/customisations.md
  src/customisations/Security.ts
Labels: T-Task

#28351 Show developer jump to event button on all events with associations
  src/components/views/context_menus/MessageContextMenu.tsx
Labels: T-Task

#28348 Wire up analytics for Legacy/EC/Jitsi voip options
  package.json
  src/components/views/rooms/RoomHeader.tsx
  src/hooks/room/useRoomCall.tsx
  src/utils/room/placeCall.ts
  yarn.lock
Labels: T-Task

#28363 Fix markdown escaping wrongly passing html through
  src/Markdown.ts
  test/unit-tests/editor/serialize-test.ts
Labels: T-Defect

#28336 Switch ModalManager to the React 18 createRoot API
  src/Modal.tsx
  test/unit-tests/components/structures/MatrixChat-test.tsx
  test/unit-tests/components/structures/auth/ForgotPassword-test.tsx
  test/unit-tests/components/views/dialogs/ConfirmRedactDialog-test.tsx
  test/unit-tests/components/views/messages/DateSeparator-test.tsx
  test/unit-tests/components/views/rooms/wysiwyg_composer/utils/message-test.ts
  test/unit-tests/components/views/settings/JoinRuleSettings-test.tsx
  test/unit-tests/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/unit-tests/utils/media/requestMediaPermissions-test.tsx
Labels: T-Task

#28340 Move navigator message listener registration to be synchronously attached
  src/vector/platform/WebPlatform.ts
Labels: T-Task

#28361 Show message type prefix in thread root & reply previews
  res/css/_components.pcss
  res/css/views/rooms/_EventPreview.pcss
  res/css/views/rooms/_PinnedMessageBanner.pcss
  src/components/views/rooms/EventPreview.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/PinnedMessageBanner.tsx
  src/components/views/rooms/ThreadSummary.tsx
  src/i18n/strings/en_EN.json
  test/test-utils/threads.ts
  test/unit-tests/components/views/rooms/PinnedMessageBanner-test.tsx
  test/unit-tests/components/views/rooms/__snapshots__/PinnedMessageBanner-test.tsx.snap
Labels: T-Enhancement

#28346 Flatten Vector-override components
  components.json
  src/BasePlatform.ts
  src/components/views/auth/AuthFooter.tsx
  src/components/views/auth/AuthHeaderLogo.tsx
  src/components/views/auth/AuthPage.tsx
  src/components/views/auth/VectorAuthFooter.tsx
  src/components/views/auth/VectorAuthHeaderLogo.tsx
  src/components/views/auth/VectorAuthPage.tsx
  src/i18n/strings/en_EN.json
  src/vector/app.tsx
  src/vector/platform/ElectronPlatform.tsx
  src/vector/platform/VectorBasePlatform.ts
  src/vector/platform/WebPlatform.ts
  test/unit-tests/components/structures/MatrixChat-test.tsx
  test/unit-tests/components/structures/__snapshots__/MatrixChat-test.tsx.snap
  test/unit-tests/components/views/auth/AuthFooter-test.tsx
  test/unit-tests/components/views/auth/AuthHeaderLogo-test.tsx
  test/unit-tests/components/views/auth/AuthPage-test.tsx
  test/unit-tests/components/views/auth/VectorAuthFooter-test.tsx
  test/unit-tests/components/views/auth/__snapshots__/AuthFooter-test.tsx.snap
  test/unit-tests/components/views/auth/__snapshots__/AuthHeaderLogo-test.tsx.snap
  test/unit-tests/components/views/auth/__snapshots__/AuthPage-test.tsx.snap
  test/unit-tests/vector/platform/WebPlatform-test.ts
Labels: T-Task

#28384 Remove redundant `switch_package_to_release` call
  .github/workflows/static_analysis.yaml
Labels: T-Task

#28375 Ignore `m.3pid_changes` for Identity service 3PID changes
  src/components/views/settings/discovery/DiscoverySettings.tsx
Labels: T-Defect

#28401 Auto approvoce `io.element.call.reaction` capability for element call widgets
  src/stores/widgets/StopGapWidgetDriver.ts
Labels: T-Enhancement

#28381 Deduplicate icons using Compound Design Tokens
  playwright/snapshots/forgot-password/forgot-password.spec.ts/forgot-password-verify-email-linux.png
  res/css/structures/_RoomStatusBar.pcss
  res/css/structures/_SpaceHierarchy.pcss
  res/css/views/context_menus/_MessageContextMenu.pcss
  res/css/views/dialogs/_AddExistingToSpaceDialog.pcss
  res/css/views/dialogs/security/_AccessSecretStorageDialog.pcss
  res/css/views/elements/_InfoTooltip.pcss
  res/css/views/messages/_MessageActionBar.pcss
  res/css/views/rooms/_EntityTile.pcss
  res/css/views/rooms/_ThreadSummary.pcss
  res/img/compound/chevron-right-12px.svg
  res/img/compound/retry-16px.svg
  res/img/element-icons/retry.svg
  res/img/element-icons/warning-badge.svg
  res/img/element-icons/warning.svg
  res/img/member_chevron.png
  src/components/structures/auth/forgot-password/CheckEmail.tsx
  src/components/structures/auth/forgot-password/VerifyEmailModal.tsx
  src/components/views/dialogs/AddExistingToSpaceDialog.tsx
  src/components/views/dialogs/ModalWidgetDialog.tsx
  src/components/views/location/MapError.tsx
  src/components/views/messages/MessageActionBar.tsx
  test/unit-tests/components/views/location/__snapshots__/MapError-test.tsx.snap
  test/unit-tests/components/views/messages/__snapshots__/MBeaconBody-test.tsx.snap
  test/unit-tests/img/edit.png
  test/unit-tests/img/icon_context_message.svg
Labels: T-Enhancement

#28379 Handle authenticated media when downloading from ImageView
  src/components/views/elements/ImageView.tsx
  test/unit-tests/components/views/elements/ImageView-test.tsx
Labels: T-Defect

#28395 Enable enable_authenticated_media in Playwright tests
  playwright/plugins/homeserver/synapse/templates/default/homeserver.yaml
Labels: T-Task

#28376 Feed events to widgets as they are decrypted (even if out of order)
  src/stores/widgets/StopGapWidget.ts
  test/unit-tests/stores/widgets/StopGapWidget-test.ts
Labels: T-Defect

#28357 Let widget driver send error details
  package.json
  src/stores/widgets/StopGapWidgetDriver.ts
  yarn.lock
Labels: T-Enhancement

#28419 Deduplicate icons using Compound Design Tokens
  playwright/snapshots/register/email.spec.ts/registration-check-your-email-linux.png
  playwright/snapshots/register/register.spec.ts/registration-linux.png
  playwright/snapshots/register/register.spec.ts/terms-prompt-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/appearance-tab-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/window-12px-linux.png
  playwright/snapshots/settings/general-room-settings-tab.spec.ts/General-room-settings-tab-should-be-rendered-properly-1-linux.png
  playwright/snapshots/settings/preferences-user-settings-tab.spec.ts/Preferences-user-settings-tab-should-be-rendered-properly-1-linux.png
  playwright/snapshots/settings/security-user-settings-tab.spec.ts/Security-user-settings-tab-with-posthog-enable-b5d89-csLearnMoreDialog-should-be-rendered-properly-1-linux.png
  playwright/snapshots/spaces/threads-activity-centre/threadsActivityCentre.spec.ts/tac-hovered-linux.png
  res/css/_common.pcss
  res/css/components/views/settings/devices/_DeviceExpandDetailsButton.pcss
  res/css/structures/_GenericDropdownMenu.pcss
  res/css/structures/_RoomView.pcss
  res/css/structures/_SpaceHierarchy.pcss
  res/css/structures/_SpacePanel.pcss
  res/css/views/dialogs/_AnalyticsLearnMoreDialog.pcss
  res/css/views/elements/_Dropdown.pcss
  res/css/views/elements/_Field.pcss
  res/css/views/messages/_DateSeparator.pcss
  res/css/views/right_panel/_ThreadPanel.pcss
  res/css/views/right_panel/_UserInfo.pcss
  res/css/views/rooms/_LinkPreviewGroup.pcss
  res/css/views/rooms/_RoomListHeader.pcss
  res/css/views/rooms/_RoomSublist.pcss
  res/css/views/spaces/_SpaceCreateMenu.pcss
  res/css/views/voip/_CallView.pcss
  res/img/feather-customised/chevron-down.svg
  res/img/feather-customised/search-input.svg
  res/img/minimise.svg
  res/img/tick-circle.svg
  src/components/views/settings/devices/DeviceExpandDetailsButton.tsx
  test/unit-tests/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/unit-tests/components/views/settings/devices/__snapshots__/DeviceExpandDetailsButton-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
Labels: T-Enhancement

#28386 Use React Suspense when rendering async modals
  src/AddThreepid.ts
  src/AsyncWrapper.tsx
  src/Modal.tsx
  src/SecurityManager.ts
  src/async-components/views/dialogs/security/NewRecoveryMethodDialog.tsx
  src/async-components/views/dialogs/security/RecoveryMethodRemovedDialog.tsx
  src/components/structures/MatrixChat.tsx
  src/components/views/dialogs/LogoutDialog.tsx
  src/components/views/settings/CryptographyPanel.tsx
  src/components/views/settings/EventIndexPanel.tsx
  src/components/views/settings/SecureBackupPanel.tsx
  test/unit-tests/SecurityManager-test.ts
  test/unit-tests/async-components/dialogs/security/RecoveryMethodRemovedDialog-test.tsx
  test/unit-tests/components/structures/MatrixChat-test.tsx
  test/unit-tests/components/views/dialogs/LogoutDialog-test.tsx
  test/unit-tests/components/views/settings/AddRemoveThreepids-test.tsx
  test/unit-tests/components/views/settings/CryptographyPanel-test.tsx
Labels: T-Enhancement

#28282 Replace `MatrixClient.isRoomEncrypted` by `MatrixClient.CryptoApi.isEncryptionEnabledInRoom` in `useIsEncrypted`
  src/hooks/useIsEncrypted.ts
  test/unit-tests/components/views/right_panel/RoomSummaryCard-test.tsx
  test/unit-tests/components/views/right_panel/UserInfo-test.tsx
Labels: T-Task

#28385 Use new `CrytoApi.restoreKeyBackup` & `CrytoApi.restoreKeyBackupFromPassphrase` api
  src/components/views/dialogs/security/RestoreKeyBackupDialog.tsx
  src/stores/SetupEncryptionStore.ts
  test/test-utils/test-utils.ts
  test/unit-tests/components/views/dialogs/security/RestoreKeyBackupDialog-test.tsx
  test/unit-tests/components/views/dialogs/security/__snapshots__/RestoreKeyBackupDialog-test.tsx.snap
Labels: T-Task

#28414 Refactor signing out devices to handle React 18 Strict Mode
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
Labels: T-Task

#28416 Refactor TimelinePanel to avoid race conditions in React 18 between state updates
  src/components/structures/TimelinePanel.tsx
Labels: T-Task

#28415 Update type and usage of window.matrixChat to be better React 18 friendly
  src/@types/global.d.ts
  src/utils/login.ts
  src/vector/init.tsx
  src/vector/routing.ts
  test/unit-tests/utils/login-test.ts
  test/unit-tests/vector/__snapshots__/init-test.ts.snap
  test/unit-tests/vector/init-test.ts
  test/unit-tests/vector/routing-test.ts
Labels: T-Task

#28452 Fix React 18 strict mode breaking spotlight dialog
  src/accessibility/RovingTabIndex.tsx
  src/accessibility/roving/RovingTabIndexWrapper.tsx
  src/components/structures/SpaceHierarchy.tsx
  src/components/views/dialogs/ForwardDialog.tsx
  src/components/views/dialogs/spotlight/Option.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/elements/Field.tsx
  src/components/views/elements/StyledCheckbox.tsx
  src/components/views/elements/StyledRadioButton.tsx
  src/components/views/emojipicker/EmojiPicker.tsx
  src/components/views/emojipicker/Search.tsx
  src/components/views/messages/JumpToDatePicker.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
  test/unit-tests/accessibility/RovingTabIndex-test.tsx
Labels: T-Defect

#26546 Wrap up new release workflows
  release_config.yaml
Labels: T-Task

#28427 Update search placeholder to Compound Design Token for placeholder text
  res/css/views/emojipicker/_EmojiPicker.pcss
  res/css/views/rooms/wysiwyg_composer/components/_Editor.pcss
Labels: T-Task

#28461 Make the version file part of webpack output
  .github/workflows/end-to-end-tests.yaml
  package.json
  scripts/docker-package.sh
  scripts/package.sh
  webpack.config.js
  yarn.lock
Labels: T-Task

#28460 Allow tab completing users in brackets
  src/autocomplete/UserProvider.tsx
  src/editor/autocomplete.ts
  src/editor/model.ts
Labels: T-Defect

#28472 Fix download button size in message action bar
  res/css/views/messages/_MessageActionBar.pcss
Labels: T-Defect

#28471 Upgrade to compound-design-tokens v2
  package.json
  res/css/views/emojipicker/_EmojiPicker.pcss
  res/css/views/rooms/wysiwyg_composer/components/_Editor.pcss
  res/themes/dark/css/_dark.pcss
  res/themes/legacy-dark/css/_legacy-dark.pcss
  res/themes/legacy-light/css/_legacy-light.pcss
  res/themes/light/css/_light.pcss
  yarn.lock
Labels: T-Enhancement

#28353 Clean up the OpenSans license file
  res/fonts/Open_Sans/LICENSE.txt
Labels: T-Task

#28453 Fix matrix-widget-api version in package.json
  yarn.lock
Labels: T-Task

#28473 Enable stylelint rule no-unknown-custom-properties
  .stylelintrc.js
  package.json
  res/css/components/views/elements/_AppPermission.pcss
  res/css/structures/_RoomView.pcss
  res/css/structures/_SpaceRoomView.pcss
  res/css/views/audio_messages/_PlaybackContainer.pcss
  res/css/views/audio_messages/_SeekBar.pcss
  res/css/views/elements/_ProgressBar.pcss
  res/css/views/rooms/_BasicMessageComposer.pcss
  res/css/views/rooms/_EventTile.pcss
  res/css/views/rooms/wysiwyg_composer/components/_Editor.pcss
  yarn.lock
Labels: T-Task

#28478 Start sending stable `m.marked_unread` events
  src/utils/notifications.ts
  test/unit-tests/components/views/context_menus/RoomGeneralContextMenu-test.tsx
  test/unit-tests/stores/RoomViewStore-test.ts
  test/unit-tests/stores/notifications/RoomNotificationState-test.ts
  test/unit-tests/utils/notifications-test.ts
Labels: T-Enhancement, Z-Community-PR

#28467 Check that the file the user chose has a MIME type of `image/*`
  src/components/views/elements/MiniAvatarUploader.tsx
  src/components/views/settings/AvatarSetting.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/views/elements/MiniAvatarUploader-test.tsx
  test/unit-tests/components/views/settings/AvatarSetting-test.tsx
Labels: T-Defect

#28217 Standardise icons using Compound Design Tokens
  playwright/snapshots/polls/polls.spec.ts/Polls-Timeline-tile-no-votes-linux.png
  playwright/snapshots/room-directory/room-directory.spec.ts/filtered-no-results-linux.png
  playwright/snapshots/room-directory/room-directory.spec.ts/filtered-one-result-linux.png
  playwright/snapshots/user-menu/user-menu.spec.ts/user-menu-linux.png
  res/css/structures/_RightPanel.pcss
  res/css/structures/_SpacePanel.pcss
  res/css/structures/_SpaceRoomView.pcss
  res/css/structures/_UserMenu.pcss
  res/css/views/context_menus/_MessageContextMenu.pcss
  res/css/views/context_menus/_RoomGeneralContextMenu.pcss
  res/css/views/dialogs/_ConfirmSpaceUserActionDialog.pcss
  res/css/views/dialogs/_LeaveSpaceDialog.pcss
  res/css/views/dialogs/_ManageRestrictedJoinRuleDialog.pcss
  res/css/views/dialogs/_SpotlightDialog.pcss
  res/css/views/elements/_InfoTooltip.pcss
  res/css/views/messages/_MessageActionBar.pcss
  res/css/views/right_panel/_ThreadPanel.pcss
  res/css/views/rooms/_RoomList.pcss
  res/css/views/rooms/_RoomListHeader.pcss
  res/css/views/rooms/_RoomPreviewCard.pcss
  res/css/views/rooms/_RoomTile.pcss
  res/css/views/spaces/_SpacePublicShare.pcss
  res/img/element-icons/export.svg
  res/img/element-icons/info.svg
  res/img/element-icons/leave.svg
  res/img/element-icons/link.svg
  res/img/element-icons/location.svg
  res/img/element-icons/message/fwd.svg
  res/img/element-icons/message/thread.svg
  res/img/element-icons/room/apps.svg
  res/img/element-icons/room/members.svg
  res/img/element-icons/room/message-bar/reply.svg
  res/img/element-icons/room/room-summary.svg
  res/img/element-icons/room/thread.svg
  res/img/element-icons/roomlist/favorite.svg
  res/img/element-icons/roomlist/member-plus.svg
  src/components/views/location/MapFallback.tsx
  src/components/views/location/Marker.tsx
  src/components/views/location/ShareType.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/rooms/EventTile/EventTileThreadToolbar.tsx
  src/components/views/settings/tabs/user/SidebarUserSettingsTab.tsx
  src/components/views/spaces/QuickSettingsButton.tsx
  test/unit-tests/components/views/beacon/__snapshots__/BeaconViewDialog-test.tsx.snap
  test/unit-tests/components/views/location/__snapshots__/LocationViewDialog-test.tsx.snap
  test/unit-tests/components/views/location/__snapshots__/Marker-test.tsx.snap
  test/unit-tests/components/views/location/__snapshots__/SmartMarker-test.tsx.snap
  test/unit-tests/components/views/messages/__snapshots__/MLocationBody-test.tsx.snap
  test/unit-tests/components/views/rooms/EventTile/__snapshots__/EventTileThreadToolbar-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/SidebarUserSettingsTab-test.tsx.snap
Labels: T-Enhancement

#28407 Listen to events so that encryption icon updates when status changes
  src/hooks/useEncryptionStatus.ts
  test/unit-tests/components/views/rooms/RoomHeader-test.tsx
Labels: T-Defect

#28402 Reset cross-signing before backup when resetting both
  src/SecurityManager.ts
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/components/views/dialogs/security/AccessSecretStorageDialog.tsx
  src/components/views/dialogs/security/RestoreKeyBackupDialog.tsx
  src/components/views/settings/SecureBackupPanel.tsx
  src/stores/SetupEncryptionStore.ts
  test/unit-tests/SecurityManager-test.ts
  test/unit-tests/components/views/dialogs/AccessSecretStorageDialog-test.tsx
  test/unit-tests/components/views/dialogs/security/CreateSecretStorageDialog-test.tsx
  test/unit-tests/stores/SetupEncryptionStore-test.ts
Labels: T-Defect

#28242 First batch: Replace `MatrixClient.isRoomEncrypted` by `MatrixClient.CryptoApi.isEncryptionEnabledInRoom`
  src/DeviceListener.ts
  src/Searching.ts
  src/SlidingSyncManager.ts
  src/components/structures/MatrixChat.tsx
  src/components/views/dialogs/ReportEventDialog.tsx
  src/components/views/dialogs/devtools/RoomNotifications.tsx
  src/components/views/messages/EncryptionEvent.tsx
  src/utils/arrays.ts
  src/utils/crypto/shouldSkipSetupEncryption.ts
  test/test-utils/client.ts
  test/unit-tests/DeviceListener-test.ts
  test/unit-tests/components/structures/MatrixChat-test.tsx
  test/unit-tests/components/structures/MessagePanel-test.tsx
  test/unit-tests/components/structures/RoomView-test.tsx
  test/unit-tests/components/views/messages/EncryptionEvent-test.tsx
  test/unit-tests/utils/arrays-test.ts
Labels: T-Task

#28499 Fix source maps in production builds
  webpack.config.js
Labels: T-Task

#28463 Rework `UrlPreviewSettings` to use `MatrixClient.CryptoApi.isEncryptionEnabledInRoom`
  package.json
  src/components/views/room_settings/UrlPreviewSettings.tsx
  src/components/views/settings/tabs/room/GeneralRoomSettingsTab.tsx
  test/unit-tests/components/views/room_settings/UrlPreviewSettings-test.tsx
  test/unit-tests/components/views/room_settings/__snapshots__/UrlPreviewSettings-test.tsx.snap
  yarn.lock
Labels: T-Task

#28485 Remove usage of legacyRoot in RTL tests
  src/components/structures/auth/ForgotPassword.tsx
  test/unit-tests/components/structures/MatrixChat-test.tsx
  test/unit-tests/components/structures/TimelinePanel-test.tsx
  test/unit-tests/components/structures/auth/ForgotPassword-test.tsx
  test/unit-tests/components/views/messages/DateSeparator-test.tsx
  test/unit-tests/components/views/messages/MPollEndBody-test.tsx
  test/unit-tests/components/views/right_panel/UserInfo-test.tsx
  test/unit-tests/components/views/rooms/MessageComposer-test.tsx
  test/unit-tests/components/views/settings/JoinRuleSettings-test.tsx
Labels: T-Task

#28505 Fix force tab complete not working since switching to React 18 createRoot API
  src/components/views/rooms/Autocomplete.tsx
Labels: T-Defect

#28498 Filter out redacted poll votes to avoid crashing the Poll widget
  src/components/views/messages/MPollBody.tsx
Labels: T-Defect

#28512 Add `Z-Flaky-Jest-Test` label
  .github/labels.yml
Labels: T-Task, A-Testing, A-Developer-Experience

#28502 Tighten GITHUB_TOKEN permissions
  .github/workflows/backport.yml
  .github/workflows/build.yml
  .github/workflows/build_debian.yaml
  .github/workflows/build_develop.yml
  .github/workflows/dockerhub.yaml
  .github/workflows/docs.yml
  .github/workflows/end-to-end-tests-netlify.yaml
  .github/workflows/end-to-end-tests.yaml
  .github/workflows/issue_closed.yml
  .github/workflows/localazy_download.yaml
  .github/workflows/localazy_upload.yaml
  .github/workflows/netlify.yaml
  .github/workflows/pending-reviews.yaml
  .github/workflows/playwright-image-updates.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/pull_request_base_branch.yaml
  .github/workflows/release-drafter.yml
  .github/workflows/release-gitflow.yml
  .github/workflows/release.yml
  .github/workflows/release_prepare.yml
  .github/workflows/sonarqube.yml
  .github/workflows/static_analysis.yaml
  .github/workflows/sync-labels.yml
  .github/workflows/tests.yml
  .github/workflows/triage-assigned.yml
  .github/workflows/triage-incoming.yml
  .github/workflows/triage-labelled.yml
  .github/workflows/triage-move-review-requests.yml
  .github/workflows/triage-stale-flaky-tests.yml
  .github/workflows/triage-unlabelled.yml
  .github/workflows/update-jitsi.yml
  .github/workflows/update-topics.yaml
Labels: T-Task

#28514 Switch away from deprecated github-status-action
  .github/workflows/tests.yml
Labels: T-Task, Dependencies

#28211 Display a warning when an unverified user's identity changes
  res/css/_components.pcss
  res/css/views/rooms/_UserIdentityWarning.pcss
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/UserIdentityWarning.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/views/rooms/UserIdentityWarning-test.tsx
Labels: T-Enhancement

#28521 Fix getOidcCallbackUrl for Element Desktop
  src/vector/platform/ElectronPlatform.tsx
Labels: T-Defect

#28513 Send and respect MSC4230 is_animated flag
  src/@types/matrix-js-sdk.d.ts
  src/ContentMessages.ts
  src/components/views/messages/MImageBody.tsx
  src/utils/image-media.ts
Labels: T-Enhancement

#28450 Use `CryptoApi.getKeyBackupInfo` instead of deprecated `MatrixClient.getKeyBackupVersion`
  src/DeviceListener.ts
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/components/structures/MatrixChat.tsx
  src/components/views/dialogs/LogoutDialog.tsx
  src/components/views/dialogs/security/RestoreKeyBackupDialog.tsx
  src/components/views/settings/SecureBackupPanel.tsx
  src/stores/SetupEncryptionStore.ts
  test/test-utils/client.ts
  test/test-utils/test-utils.ts
  test/unit-tests/DeviceListener-test.ts
  test/unit-tests/components/structures/MatrixChat-test.tsx
  test/unit-tests/components/views/dialogs/LogoutDialog-test.tsx
  test/unit-tests/components/views/dialogs/security/CreateSecretStorageDialog-test.tsx
  test/unit-tests/components/views/dialogs/security/RestoreKeyBackupDialog-test.tsx
  test/unit-tests/components/views/settings/SecureBackupPanel-test.tsx
  test/unit-tests/components/views/settings/tabs/user/SecurityUserSettingsTab-test.tsx
  test/unit-tests/stores/SetupEncryptionStore-test.ts
Labels: T-Task

#28525 Deploy app.element.io & staging.element.io via Github Actions
  .github/actions/download-verify-element-tarball/action.yml
  .github/workflows/deploy.yml
Labels: T-Task

#28535 Add spinner when room encryption is loading in room settings
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  test/unit-tests/components/views/settings/tabs/room/SecurityRoomSettingsTab-test.tsx
Labels: T-Defect, X-Regression

#28543 Temporarily add a default branch to handle unknown shield codes
  src/components/views/rooms/EventTile.tsx
Labels: T-Task

#28549 Remove Twemoji SBIX font in favour of COLRv0
  __mocks__/FontManager.js
  jest.config.ts
  res/fonts/Twemoji_Mozilla/TwemojiMozilla-sbix.woff2
  res/themes/light/css/_fonts.pcss
  src/components/structures/LoggedInView.tsx
  src/components/views/verification/VerificationShowSas.tsx
  src/utils/FontManager.ts
Labels: T-Task

#28278 Replace `MatrixClient.isRoomEncrypted` by `MatrixClient.CryptoApi.isEncryptionEnabledInRoom` in RoomView
  playwright/e2e/crypto/decryption-failure-messages.spec.ts
  src/components/structures/RoomView.tsx
  src/contexts/RoomContext.ts
  test/test-utils/room.ts
  test/test-utils/test-utils.ts
  test/unit-tests/components/structures/RoomView-test.tsx
  test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/unit-tests/components/views/rooms/SendMessageComposer-test.tsx
Labels: T-Task

#28398 Update calls to addEventToTimeline and addLiveEvents for new signature
  src/components/structures/FilePanel.tsx
  src/indexing/EventIndex.ts
  src/utils/dm/createDmLocalRoom.ts
  test/test-utils/call.ts
  test/test-utils/threads.ts
  test/unit-tests/Notifier-test.ts
  test/unit-tests/RoomNotifs-test.ts
  test/unit-tests/Unread-test.ts
  test/unit-tests/components/structures/FilePanel-test.tsx
  test/unit-tests/components/structures/RoomView-test.tsx
  test/unit-tests/components/structures/ThreadPanel-test.tsx
  test/unit-tests/components/structures/TimelinePanel-test.tsx
  test/unit-tests/components/views/context_menus/RoomGeneralContextMenu-test.tsx
  test/unit-tests/components/views/dialogs/InviteDialog-test.tsx
  test/unit-tests/components/views/elements/Pill-test.tsx
  test/unit-tests/components/views/elements/RoomTopic-test.tsx
  test/unit-tests/components/views/rooms/NotificationBadge/UnreadNotificationBadge-test.tsx
  test/unit-tests/components/views/rooms/RoomHeader-test.tsx
  test/unit-tests/components/views/settings/Notifications-test.tsx
  test/unit-tests/components/views/settings/notifications/Notifications2-test.tsx
  test/unit-tests/events/EventTileFactory-test.ts
  test/unit-tests/models/Call-test.ts
  test/unit-tests/stores/MemberListStore-test.ts
  test/unit-tests/stores/RoomViewStore-test.ts
  test/unit-tests/stores/room-list/MessagePreviewStore-test.ts
  test/unit-tests/stores/room-list/algorithms/RecentAlgorithm-test.ts
  test/unit-tests/stores/room-list/previews/ReactionEventPreview-test.ts
  test/unit-tests/useTopic-test.tsx
  test/unit-tests/utils/exportUtils/HTMLExport-test.ts
  test/unit-tests/utils/notifications-test.ts
  test/unit-tests/voice-broadcast/components/VoiceBroadcastBody-test.tsx
  test/unit-tests/voice-broadcast/models/VoiceBroadcastPlayback-test.tsx
  test/unit-tests/voice-broadcast/utils/hasRoomLiveVoiceBroadcast-test.ts
  test/unit-tests/voice-broadcast/utils/isRelatedToVoiceBroadcast-test.ts
  test/unit-tests/voice-broadcast/utils/retrieveStartedInfoEvent-test.ts
Labels: T-Task

#28580 Add source-map-loader for easier debugging
  package.json
  webpack.config.js
  yarn.lock
Labels: T-Task

#28551 Apply release blocker checks to cut branches workflow
  .github/workflows/release_prepare.yml
Labels: T-Task

#28581 Add Modernizr warning when running in non-secure context
  src/vector/index.ts
Labels: T-Enhancement

#28582 Remove `Features.RustCrypto` flag
  src/MatrixClientPeg.ts
  src/settings/Settings.tsx
  test/unit-tests/MatrixClientPeg-test.ts
Labels: T-Enhancement

#28583 Remove redundant MSC implementation for io.element.rendezvous
  src/components/views/auth/LoginWithQR.tsx
  src/components/views/settings/devices/LoginWithQRSection.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  test/unit-tests/components/views/settings/devices/LoginWithQRSection-test.tsx
Labels: T-Task

#28591 Fix format bar position
  src/components/views/rooms/MessageComposerFormatBar.tsx
Labels: T-Defect
