Repository element-hq/element-web, pull requests merged in 2024-01, with the labels that each got.

#26796 Update tests not to mock out an ancient server
  test/app-tests/loading-test.tsx
  test/app-tests/server-config-test.ts
  test/app-tests/wrapper-test.tsx
Labels: T-Task

#26793 Rename the GH org to element-hq in documentation, configuration and within code, comments and snapshot tests.
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/labels.yml
  CONTRIBUTING.md
  README.md
  book.toml
  contribute.json
  docs/betas.md
  docs/choosing-an-issue.md
  docs/config.md
  docs/customisations.md
  docs/feature-flags.md
  docs/install.md
  docs/jitsi.md
  docs/labs.md
  docs/modules.md
  docs/native-node-modules.md
  docs/release.md
  docs/translating-dev.md
  element.io/README
  package.json
  src/components/views/auth/VectorAuthFooter.tsx
  src/vector/index.ts
  src/vector/jitsi/index.pcss
  src/vector/jitsi/index.ts
  src/vector/platform/ElectronPlatform.tsx
  src/vector/platform/VectorBasePlatform.ts
  test/unit-tests/components/views/auth/__snapshots__/VectorAuthFooter-test.tsx.snap
  test/unit-tests/components/views/auth/__snapshots__/VectorAuthPage-test.tsx.snap
  webpack.config.js
Labels: T-Task

#26818 Update teams names in CODEOWNERS and workflows
  .github/CODEOWNERS
  .github/workflows/pending-reviews.yaml
Labels: T-Task

#26832 Split up the changelog
  .prettierignore
  CHANGELOG.md
  docs/changelogs/CHANGELOG-2022.md
  docs/changelogs/CHANGELOG-2023.md
  docs/changelogs/CHANGELOG-pre-2022.md
Labels: T-Task

#26801 Run Playwright tests on merge queue
  .github/workflows/build.yml
  .github/workflows/downstream-artifacts.yml
  .github/workflows/end-to-end-tests.yaml
  .github/workflows/static_analysis.yaml
  .github/workflows/tests.yaml
Labels: T-Task

#26831 Strip data-testid in production
  package.json
  webpack.config.js
  yarn.lock
Labels: T-Task

#26840 Fix CSS stacking context order determinism
  src/vector/index.html
Labels: T-Defect, X-Release-Blocker

#26870 Update reference from cypress to playwright
  CONTRIBUTING.md
Labels: T-Task

#26885 Deprecate welcome bot `welcome_user_id` support
  docs/config.md
Labels: T-Deprecation

#26884 Use Github Artifacts v4
  .github/workflows/build_debian.yaml
  .github/workflows/build_develop.yml
  .github/workflows/tests.yaml
Labels: T-Task

#26903 Remove webpack 4 hack
  webpack.config.js
Labels: T-Task

#26904 Add workaround for webpack builds on platforms unsupported by Sentry
  webpack.config.js
Labels: T-Task

#26911 Bump @matrix-org/react-sdk-module-api from 2.2.1 to 2.3.0
  package.json
  yarn.lock
Labels: T-Task, Z-Community-PR

#26819 Force Element Call video rooms
  element.io/develop/config.json
Labels: T-Task
