Repository element-hq/element-web, pull requests merged in 2024-07, with the labels that each got.

#27662 Remove `mdbook-combiner` version
  .github/workflows/docs.yml
Labels: T-Task

#27672 Use last node lts in workflow
  .github/workflows/build.yml
  .github/workflows/build_develop.yml
  .github/workflows/static_analysis.yaml
  .github/workflows/tests.yaml
  .github/workflows/update-jitsi.yml
Labels: T-Task

#27674 Add a Modernizr check for v mode regexes
  src/vector/index.ts
Labels: T-Task

#25477 Remove message audio element (for another pr)
  src/vector/index.html
Labels: T-Task, Z-Community-PR

#27650 Remove code which loads legacy libolm
  package.json
  src/vector/index.ts
  src/vector/init.tsx
  webpack.config.js
Labels: T-Task

#27677 Add Modernizr rule for Intl.Segmenter
  src/vector/index.ts
Labels: T-Enhancement

#27685 Ensure we do not load matrix-react-sdk is a manner which can white-screen
  src/vector/index.ts
  src/vector/init.tsx
Labels: T-Defect, X-Release-Blocker

#27675 Add Electron IPC APIs for authenticated media
  src/@types/global.d.ts
  src/vector/platform/ElectronPlatform.tsx
Labels: T-Task

#27706 Move needs info and flaky tests issues to the correct columns
  .github/workflows/triage-labelled.yml
Labels: T-Task

#27705 Docs: Align `widget_build_url_ignore_dm` with call behaviour switch between 1:1 and Widget
  docs/config.md
Labels: T-Task

#27758 Add debugging for service worker version check
  src/serviceworker/index.ts
Labels: T-Task

#27767 Unminify modernizr
  .modernizr.json
  sonar-project.properties
  src/vector/modernizr.js
Labels: T-Task

#27772 Enable audio/webaudio Modernizr rule
  .modernizr.json
  src/vector/modernizr.js
Labels: T-Enhancement

#27803 Polyfill Intl.Segmenter for wider web browser compatibility
  package.json
  src/vector/index.ts
  yarn.lock
Labels: X-Release-Blocker, T-Enhancement

#27807 Update Supported Environments
  README.md
Labels: T-Task

#27858 Fix Jitsi by updating device mute updates over postMessage API
  src/vector/jitsi/index.ts
Labels: T-Defect, X-Upcoming-Release-Blocker

#27857 Update unsupported browser react component to new designs
  docs/config.md
  package.json
  res/css/structures/ErrorView.pcss
  res/themes/element/img/compound/apple.svg
  res/themes/element/img/compound/fade-arc-light.png
  res/themes/element/img/compound/linux.svg
  res/themes/element/img/compound/microsoft.svg
  res/themes/element/img/logos/element-app-logo.png
  src/async-components/structures/CompatibilityView.tsx
  src/async-components/structures/ErrorView.tsx
  src/i18n/strings/en_EN.json
  src/vector/init.tsx
  test/unit-tests/async-components/structures/ErrorView-test.tsx
  test/unit-tests/async-components/structures/__snapshots__/ErrorView-test.tsx.snap
  tsconfig.json
  yarn.lock
Labels: T-Enhancement

#26453 feat: Add autoformat and lint for ts/tsx files
  .husky/pre-commit
  .lintstagedrc
  package.json
  yarn.lock
Labels: T-Task, Z-Community-PR

#27881 Make sonarcloud happier
  src/favicon.ts
  src/vector/getconfig.ts
  src/vector/localstorage-fix.ts
  src/vector/mobile_guide/index.ts
Labels: T-Task
