Repository element-hq/element-web, pull requests merged in 2024-06, with the labels that each got.

#27527 Roll out Rust crypto to 60% of existing users on app.element.io
  element.io/app/config.json
Labels: T-Enhancement

#27530 Fix CI docs generation
  .github/workflows/docs.yml
Labels: T-Task

#27561 Conform to no-floating-promises
  .eslintrc.js
  src/vector/index.ts
  src/vector/init.tsx
  src/vector/jitsi/index.ts
  src/vector/mobile_guide/index.ts
  src/vector/platform/ElectronPlatform.tsx
  src/vector/platform/WebPlatform.ts
  src/vector/rageshakesetup.ts
Labels: T-Task

#27569 Add `Z-Flaky-Test-Disabled` label to labels.yml
  .github/labels.yml
Labels: T-Task

#27567 Remove setImmediate polyfill
  package.json
  src/favicon.ts
  src/vector/index.ts
Labels: T-Task

#27570 Fix webpack deprecation warnings
  recorder-worklet-loader.js
  webpack.config.js
Labels: T-Task

#27558 Use stable endpoints for MSC3916
  src/serviceworker/index.ts
Labels: T-Enhancement

#27576 Add SSO redirect option for login page
  docs/config.md
  src/vector/app.tsx
Labels: T-Enhancement, Z-Community-PR

#27568 Update postcss-preset-env
  package.json
  yarn.lock
Labels: T-Task

#27598 Replace deprecated babel proposal plugins
  babel.config.js
  package.json
  yarn.lock
Labels: T-Task

#27588 Remove very outdated loading-test.tsx
  test/app-tests/loading-test.tsx
  test/test-utils.ts
Labels: T-Task

#27619 Remove outdated rust-crypto settings config
  docs/labs.md
Labels: T-Task
