Repository element-hq/element-web, pull requests merged in 2024-03, with the labels that each got.

#27102 Improve Element Desktop OIDC Native dynamic registration
  src/vector/platform/ElectronPlatform.tsx
Labels: T-Enhancement

#27081 Trigger Element Desktop release drafter upon release of Element Web
  .github/workflows/release.yml
Labels: T-Task

#27101 Add docs for element call external conference configuration (single-page app URL)
  docs/config.md
Labels: T-Enhancement, A-Element Call

#27149 Remove process to move issue to the old triage board (which has been …
  .github/workflows/triage-incoming.yml
Labels: T-Task

#27152 Remove Element-R from Z-Labs labelling
  .github/workflows/triage-labelled.yml
Labels: T-Task

#27188 Fix missing compound design tokens
  yarn.lock
Labels: T-Defect, backport staging

#27200 Fix deploying develop when the bundles are already present in R2
  .github/workflows/build_develop.yml
Labels: T-Task
