Repository element-hq/element-web, pull requests merged in 2024-05, with the labels that each got.

#27416 Roll out Rust crypto to 30% of existing users on `app.element.io`
  element.io/app/config.json
Labels: T-Enhancement

#27464 Modernize hash in webpack
  webpack.config.js
Labels: T-Task, Z-Community-PR

#27466 Revert "Modernize hash in webpack"
  webpack.config.js
Labels: T-Task, Z-Community-PR

#27452 Add code style rule for multiple return types
  code_style.md
Labels: T-Task

#26817 Sign Docker images using cosign
  .github/workflows/dockerhub.yaml
Labels: T-Enhancement

#27431 Fix `element-desktop-ssoid being` included in OIDC Authorization call
  src/vector/platform/ElectronPlatform.tsx
Labels: T-Task

#27326 Typescriptify & use service worker for MSC3916 authentication
  res/sw.js
  src/serviceworker/index.ts
  src/vector/platform/WebPlatform.ts
  webpack.config.js
Labels: T-Enhancement

#27478 Add missing @types/semver dev dep
  package.json
Labels: T-Task
