Repository element-hq/element-web, pull requests merged in 2024-12, with the labels that each got.

#28574 Improve performance of RoomContext in RoomHeader
  src/components/structures/FilePanel.tsx
  src/components/structures/NotificationPanel.tsx
  src/components/structures/RoomSearchView.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/ThreadPanel.tsx
  src/components/structures/ThreadView.tsx
  src/components/structures/WaitingForThirdPartyRoomView.tsx
  src/components/views/avatars/BaseAvatar.tsx
  src/components/views/context_menus/WidgetContextMenu.tsx
  src/components/views/elements/MiniAvatarUploader.tsx
  src/components/views/messages/RoomPredecessorTile.tsx
  src/components/views/right_panel/PinnedMessagesCard.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/right_panel/TimelineCard.tsx
  src/components/views/rooms/HistoryTile.tsx
  src/components/views/rooms/MessageComposerButtons.tsx
  src/components/views/rooms/NewRoomIntro.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/ThreadSummary.tsx
  src/components/views/rooms/wysiwyg_composer/components/Emoji.tsx
  src/components/views/rooms/wysiwyg_composer/components/WysiwygAutocomplete.tsx
  src/components/views/rooms/wysiwyg_composer/components/WysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/useEditing.ts
  src/components/views/rooms/wysiwyg_composer/hooks/useInitialContent.ts
  src/components/views/rooms/wysiwyg_composer/hooks/useInputEventProcessor.ts
  src/components/views/rooms/wysiwyg_composer/hooks/usePlainTextListeners.ts
  src/components/views/rooms/wysiwyg_composer/hooks/useWysiwygEditActionHandler.ts
  src/components/views/rooms/wysiwyg_composer/hooks/useWysiwygSendActionHandler.ts
  src/components/views/rooms/wysiwyg_composer/hooks/utils.ts
  src/components/views/rooms/wysiwyg_composer/utils/editing.ts
  src/components/views/rooms/wysiwyg_composer/utils/event.ts
  src/components/views/rooms/wysiwyg_composer/utils/message.ts
  src/contexts/RoomContext.ts
  src/contexts/ScopedRoomContext.tsx
  src/hooks/room/useRoomMemberProfile.ts
  test/unit-tests/components/structures/MessagePanel-test.tsx
  test/unit-tests/components/structures/ThreadPanel-test.tsx
  test/unit-tests/components/structures/ThreadView-test.tsx
  test/unit-tests/components/views/audio_messages/RecordingPlayback-test.tsx
  test/unit-tests/components/views/avatars/MemberAvatar-test.tsx
  test/unit-tests/components/views/context_menus/MessageContextMenu-test.tsx
  test/unit-tests/components/views/messages/MFileBody-test.tsx
  test/unit-tests/components/views/messages/MessageActionBar-test.tsx
  test/unit-tests/components/views/messages/RoomPredecessorTile-test.tsx
  test/unit-tests/components/views/right_panel/RoomSummaryCard-test.tsx
  test/unit-tests/components/views/rooms/EditMessageComposer-test.tsx
  test/unit-tests/components/views/rooms/EventTile-test.tsx
  test/unit-tests/components/views/rooms/MessageComposer-test.tsx
  test/unit-tests/components/views/rooms/MessageComposerButtons-test.tsx
  test/unit-tests/components/views/rooms/NewRoomIntro-test.tsx
  test/unit-tests/components/views/rooms/SendMessageComposer-test.tsx
  test/unit-tests/components/views/rooms/wysiwyg_composer/EditWysiwygComposer-test.tsx
  test/unit-tests/components/views/rooms/wysiwyg_composer/SendWysiwygComposer-test.tsx
  test/unit-tests/components/views/rooms/wysiwyg_composer/components/PlainTextComposer-test.tsx
  test/unit-tests/components/views/rooms/wysiwyg_composer/components/WysiwygAutocomplete-test.tsx
  test/unit-tests/components/views/rooms/wysiwyg_composer/components/WysiwygComposer-test.tsx
Labels: T-Enhancement

#28510 Replace `MatrixClient.isRoomEncrypted` by `MatrixClient.CryptoApi.isEncryptionEnabledInRoom` in `EventTile.tsx`
  src/components/views/rooms/EventTile.tsx
  test/test-utils/test-utils.ts
  test/unit-tests/components/views/dialogs/ForwardDialog-test.tsx
  test/unit-tests/components/views/rooms/EventTile-test.tsx
Labels: T-Task

#28538 Remove space-specific right panel store handling
  src/components/structures/RightPanel.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/SpaceRoomView.tsx
  src/components/structures/UserView.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomInfoLine.tsx
  src/components/views/toasts/VerificationRequestToast.tsx
  src/stores/right-panel/RightPanelStore.ts
  src/stores/right-panel/RightPanelStoreIPanelState.ts
  src/stores/right-panel/RightPanelStorePhases.ts
  src/stores/right-panel/action-handlers/View3pidInvite.ts
  src/verification.ts
  test/unit-tests/components/structures/RightPanel-test.tsx
  test/unit-tests/components/structures/RoomView-test.tsx
  test/unit-tests/components/structures/SpaceRoomView-test.tsx
  test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/unit-tests/components/views/right_panel/RoomSummaryCard-test.tsx
  test/unit-tests/components/views/right_panel/UserInfo-test.tsx
  test/unit-tests/components/views/rooms/PinnedMessageBanner-test.tsx
  test/unit-tests/components/views/rooms/RoomHeader-test.tsx
  test/unit-tests/stores/right-panel/RightPanelStore-test.ts
  test/unit-tests/stores/right-panel/action-handlers/View3pidInvite-test.ts
Labels: T-Task

#28613 Fix code block highlighting not working reliably with many code blocks
  src/components/views/messages/TextualBody.tsx
  src/utils/react.tsx
Labels: T-Defect

#28612 Remove unused scripts
  scripts/copy-i18n.py
  scripts/fetch-develop.deps.sh
  scripts/genflags.sh
Labels: T-Task

#28598 New UX for Share dialog
  playwright/e2e/share-dialog/share-dialog.spec.ts
  playwright/snapshots/share-dialog/share-dialog.spec.ts/share-dialog-event-linux.png
  playwright/snapshots/share-dialog/share-dialog.spec.ts/share-dialog-room-linux.png
  playwright/snapshots/share-dialog/share-dialog.spec.ts/share-dialog-user-linux.png
  res/css/_common.pcss
  res/css/views/dialogs/_ShareDialog.pcss
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/dialogs/ShareDialog.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/RoomHeader/CallGuestLinkButton.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/views/dialogs/ShareDialog-test.tsx
  test/unit-tests/components/views/dialogs/__snapshots__/ShareDialog-test.tsx.snap
  test/unit-tests/components/views/right_panel/RoomSummaryCard-test.tsx
  test/unit-tests/components/views/right_panel/UserInfo-test.tsx
  test/unit-tests/components/views/rooms/RoomHeader/CallGuestLinkButton-test.tsx
Labels: T-Enhancement

#28617 Add `Close` tooltip to dialog
  src/components/views/dialogs/BaseDialog.tsx
  test/unit-tests/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
  test/unit-tests/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
Labels: T-Enhancement

#28625 Fix TAC `should mark all threads as read` e2e test
  playwright/e2e/spaces/threads-activity-centre/index.ts
  playwright/e2e/spaces/threads-activity-centre/threadsActivityCentre.spec.ts
Labels: T-Task

#28623 Tag screenshot tests to speed up test:playwright:screenshot
  package.json
  playwright/e2e/app-loading/feature-detection.spec.ts
  playwright/e2e/audio-player/audio-player.spec.ts
  playwright/e2e/chat-export/html-export.spec.ts
  playwright/e2e/crypto/crypto.spec.ts
  playwright/e2e/editing/editing.spec.ts
  playwright/e2e/file-upload/image-upload.spec.ts
  playwright/e2e/forgot-password/forgot-password.spec.ts
  playwright/e2e/invite/invite-dialog.spec.ts
  playwright/e2e/messages/messages.spec.ts
  playwright/e2e/permalinks/permalinks.spec.ts
  playwright/e2e/pinned-messages/pinned-messages.spec.ts
  playwright/e2e/polls/polls.spec.ts
  playwright/e2e/register/email.spec.ts
  playwright/e2e/register/register.spec.ts
  playwright/e2e/release-announcement/releaseAnnouncement.spec.ts
  playwright/e2e/right-panel/file-panel.spec.ts
  playwright/e2e/right-panel/notification-panel.spec.ts
  playwright/e2e/right-panel/right-panel.spec.ts
  playwright/e2e/room-directory/room-directory.spec.ts
  playwright/e2e/room/room-header.spec.ts
  playwright/e2e/settings/account-user-settings-tab.spec.ts
  playwright/e2e/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts
  playwright/e2e/settings/appearance-user-settings-tab/message-layout-panel.ts
  playwright/e2e/settings/appearance-user-settings-tab/theme-choice-panel.spec.ts
  playwright/e2e/settings/general-room-settings-tab.spec.ts
  playwright/e2e/settings/preferences-user-settings-tab.spec.ts
  playwright/e2e/settings/security-user-settings-tab.spec.ts
  playwright/e2e/share-dialog/share-dialog.spec.ts
  playwright/e2e/spaces/spaces.spec.ts
  playwright/e2e/spaces/threads-activity-centre/threadsActivityCentre.spec.ts
  playwright/e2e/threads/threads.spec.ts
  playwright/e2e/timeline/timeline.spec.ts
  playwright/e2e/user-menu/user-menu.spec.ts
  playwright/e2e/user-onboarding/user-onboarding-new.spec.ts
  playwright/e2e/user-view/user-view.spec.ts
  playwright/e2e/widgets/layout.spec.ts
  playwright/element-web-test.ts
Labels: T-Task

#28631 Fix font & spaces in settings subsection
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/window-12px-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/theme-choice-panel.spec.ts/theme-panel-custom-theme-added-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/theme-choice-panel.spec.ts/theme-panel-custom-theme-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/theme-choice-panel.spec.ts/theme-panel-custom-theme-removed-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/theme-choice-panel.spec.ts/theme-panel-dark-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/theme-choice-panel.spec.ts/theme-panel-light-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/theme-choice-panel.spec.ts/theme-panel-match-system-enabled-linux.png
  res/css/components/views/settings/shared/_SettingsSubsection.pcss
  src/components/views/settings/shared/SettingsSubsection.tsx
  src/components/views/settings/shared/SettingsSubsectionHeading.tsx
  test/unit-tests/components/views/settings/__snapshots__/LayoutSwitcher-test.tsx.snap
  test/unit-tests/components/views/settings/__snapshots__/ThemeChoicePanel-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/AppearanceUserSettingsTab-test.tsx.snap
Labels: T-Defect

#28630 increase ringing timeout from 10 seconds to 90 seconds
  src/Notifier.ts
  src/toasts/IncomingCallToast.tsx
Labels: T-Enhancement

#28626 Remove usages of Buffer so we don't need to ship the polyfill
  .eslintrc.js
  package.json
  playwright/e2e/crypto/device-verification.spec.ts
  src/@types/png-chunks-extract.d.ts
  src/DecryptionFailureTracker.ts
  src/components/views/auth/LoginWithQR.tsx
  src/components/views/elements/crypto/VerificationQRCode.tsx
  src/components/views/right_panel/VerificationPanel.tsx
  src/stores/ThreepidInviteStore.ts
  src/utils/WidgetUtils.ts
  src/utils/exportUtils/HtmlExport.tsx
  src/utils/tokens/pickling.ts
  test/unit-tests/Lifecycle-test.ts
  test/unit-tests/components/views/elements/crypto/VerificationQRCode-test.tsx
  test/unit-tests/components/views/right_panel/VerificationPanel-test.tsx
  webpack.config.js
  yarn.lock
Labels: T-Task

#28641 Playwright: fix (hopefully) flaky shields test
  playwright/e2e/crypto/event-shields.spec.ts
Labels: T-Task

#28649 Remove stale webpack configuration
  webpack.config.js
Labels: T-Task

#28655 Fix multiple pinned messages flaky tests
  playwright/e2e/pinned-messages/index.ts
Labels: T-Task

#28654 Fix jumpy timeline when the pinned message banner is displayed
  src/components/structures/RoomView.tsx
  src/components/views/rooms/PinnedMessageBanner.tsx
  test/unit-tests/components/views/rooms/PinnedMessageBanner-test.tsx
Labels: T-Defect

#28658 Rename CreateCrossSigningDialog to InitialCryptoSetupDialog
  src/components/structures/auth/E2eSetup.tsx
  src/components/views/dialogs/security/InitialCryptoSetupDialog.tsx
  test/components/views/dialogs/security/InitialCryptoSetupDialog-test.tsx
Labels: T-Task

#28678 Make tsc faster again
  src/accessibility/context_menu/ContextMenuButton.tsx
  src/accessibility/context_menu/ContextMenuTooltipButton.tsx
  src/accessibility/roving/RovingAccessibleButton.tsx
  src/components/structures/auth/SoftLogout.tsx
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  src/components/views/dialogs/devtools/SettingExplorer.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/dialogs/spotlight/TooltipOption.tsx
  src/components/views/directory/NetworkDropdown.tsx
  src/components/views/elements/AccessibleButton.tsx
  src/components/views/elements/EditableItemList.tsx
  src/components/views/emojipicker/Emoji.tsx
  src/components/views/messages/MPollEndBody.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/settings/SetIdServer.tsx
  src/components/views/settings/devices/DeviceExpandDetailsButton.tsx
  src/components/views/settings/tabs/user/MjolnirUserSettingsTab.tsx
  src/components/views/spaces/SpaceBasicSettings.tsx
  src/components/views/spaces/SpacePanel.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
  src/components/views/voip/LegacyCallView/LegacyCallViewButtons.tsx
  test/unit-tests/components/structures/__snapshots__/MatrixChat-test.tsx.snap
  test/unit-tests/components/views/settings/SetIntegrationManager-test.tsx
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/MjolnirUserSettingsTab-test.tsx.snap
Labels: T-Task

#28668 Add delay in test to allow Alice to fetch Bob's device keys
  playwright/e2e/crypto/user-verification.spec.ts
Labels: T-Task

#28316 Allow trusted Element Call widget to send and receive media encryption key to-device messages
  src/stores/widgets/StopGapWidgetDriver.ts
Labels: T-Enhancement

#28675 Factor out crypto setup process into a store
  src/@types/global.d.ts
  src/components/structures/MatrixChat.tsx
  src/components/structures/auth/E2eSetup.tsx
  src/components/views/dialogs/security/InitialCryptoSetupDialog.tsx
  src/stores/InitialCryptoSetupStore.ts
  src/stores/SetupEncryptionStore.ts
  test/components/views/dialogs/security/InitialCryptoSetupDialog-test.tsx
  test/unit-tests/stores/InitialCryptoSetupStore-test.ts
Labels: T-Task

#28719 Fix Read Receipt Test
  test/unit-tests/components/views/rooms/ReadReceiptGroup-test.tsx
  test/unit-tests/components/views/rooms/__snapshots__/ReadReceiptGroup-test.tsx.snap
Labels: T-Task

#28723 Change to en-US locale for date tests
  test/unit-tests/utils/DateUtils-test.ts
Labels: T-Task

#28700 Update `@vector-im/compound-web` to `7.5.0`
  package.json
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/window-12px-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/theme-choice-panel.spec.ts/theme-panel-custom-theme-added-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/theme-choice-panel.spec.ts/theme-panel-custom-theme-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/theme-choice-panel.spec.ts/theme-panel-custom-theme-removed-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/theme-choice-panel.spec.ts/theme-panel-dark-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/theme-choice-panel.spec.ts/theme-panel-light-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/theme-choice-panel.spec.ts/theme-panel-match-system-enabled-linux.png
  test/unit-tests/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/unit-tests/components/views/settings/__snapshots__/LayoutSwitcher-test.tsx.snap
  test/unit-tests/components/views/settings/__snapshots__/ThemeChoicePanel-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/AppearanceUserSettingsTab-test.tsx.snap
  test/unit-tests/components/views/spaces/__snapshots__/SpacePanel-test.tsx.snap
  test/unit-tests/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
  yarn.lock
Labels: T-Task

#28718 Move rust-sdk wasm artifact into bundles directory
  webpack.config.js
Labels: T-Task

#28734 Add some logging to `UserIdenitityWarning`
  src/components/views/rooms/UserIdentityWarning.tsx
Labels: T-Task

#28753 Enable message layout e2e test
  playwright/e2e/settings/appearance-user-settings-tab/message-layout-panel.spec.ts
  playwright/snapshots/settings/appearance-user-settings-tab/message-layout-panel.spec.ts/message-layout-panel-bubble-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/message-layout-panel.spec.ts/message-layout-panel-modern-linux.png
Labels: T-Task

#28691 Enable key backup by default
  playwright/e2e/crypto/backups.spec.ts
  src/CreateCrossSigning.ts
  src/DeviceListener.ts
  src/components/views/dialogs/LogoutDialog.tsx
  src/i18n/strings/en_EN.json
  src/stores/InitialCryptoSetupStore.ts
  src/toasts/SetupEncryptionToast.ts
  test/test-utils/test-utils.ts
  test/unit-tests/DeviceListener-test.ts
  test/unit-tests/components/structures/MatrixChat-test.tsx
  test/unit-tests/components/views/dialogs/LogoutDialog-test.tsx
  test/unit-tests/toasts/SetupEncryptionToast-test.tsx
Labels: T-Enhancement

#28754 Move room header info button to right-most position
  playwright/e2e/room/room-header.spec.ts
  playwright/snapshots/room/room-header.spec.ts/room-header-linux.png
  playwright/snapshots/room/room-header.spec.ts/room-header-long-name-linux.png
  playwright/snapshots/room/room-header.spec.ts/room-header-video-room-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/collapsed-gels-and-messages-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/collapsed-gels-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/configured-room-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-line-inline-start-margin-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tiles-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tiles-compact-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tiles-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tiles-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-and-messages-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-emote-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-redaction-placeholder-linux.png
  src/components/views/rooms/RoomHeader.tsx
  test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/unit-tests/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
Labels: T-Enhancement

#28765 Fix url preview display
  src/components/views/messages/TextualBody.tsx
  test/unit-tests/components/views/messages/TextualBody-test.tsx
Labels: T-Defect, X-Regression, X-Release-Blocker, backport staging

#28750 Remove AccountPasswordStore and related flows
  src/CreateCrossSigning.ts
  src/SecurityManager.ts
  src/components/structures/MatrixChat.tsx
  src/components/structures/auth/Login.tsx
  src/components/structures/auth/Registration.tsx
  src/contexts/SDKContext.ts
  src/stores/AccountPasswordStore.ts
  src/stores/InitialCryptoSetupStore.ts
  src/stores/SetupEncryptionStore.ts
  test/CreateCrossSigning-test.ts
  test/unit-tests/stores/AccountPasswordStore-test.ts
  test/unit-tests/stores/InitialCryptoSetupStore-test.ts
  test/unit-tests/stores/SetupEncryptionStore-test.ts
Labels: T-Task

#28770 Clean up Playwright test code related to legacy crypto
  playwright/e2e/crypto/dehydration.spec.ts
  playwright/e2e/crypto/event-shields.spec.ts
  playwright/e2e/crypto/migration.spec.ts
  playwright/e2e/crypto/utils.ts
Labels: T-Task

#28752 Use mapped types around account data events
  playwright/e2e/crypto/crypto.spec.ts
  playwright/e2e/integration-manager/get-openid-token.spec.ts
  playwright/e2e/integration-manager/kick.spec.ts
  playwright/e2e/integration-manager/read_events.spec.ts
  playwright/e2e/integration-manager/send_event.spec.ts
  playwright/e2e/room/room.spec.ts
  playwright/e2e/spotlight/spotlight.spec.ts
  playwright/e2e/widgets/stickers.spec.ts
  playwright/pages/client.ts
  src/@types/matrix-js-sdk.d.ts
  src/components/structures/LoggedInView.tsx
  src/components/views/dialogs/devtools/AccountData.tsx
  src/components/views/settings/devices/useOwnDevices.ts
  src/hooks/useAccountData.ts
  src/settings/handlers/AccountSettingsHandler.ts
  src/stores/WidgetStore.ts
  src/utils/IdentityServerUtils.ts
  src/utils/WidgetUtils-types.ts
  src/utils/WidgetUtils.ts
  src/utils/device/clientInformation.ts
  src/utils/device/types.ts
  src/utils/notifications.ts
  test/unit-tests/Notifier-test.ts
  test/unit-tests/components/views/right_panel/RoomSummaryCard-test.tsx
  test/unit-tests/utils/notifications-test.ts
Labels: T-Task

#28757 Run Playwright tests on Firefox & "Safari" nightly
  .github/workflows/end-to-end-tests.yaml
  docs/playwright.md
  package.json
  playwright.config.ts
  playwright/e2e/audio-player/audio-player.spec.ts
  playwright/e2e/crypto/backups.spec.ts
  playwright/e2e/crypto/device-verification.spec.ts
  playwright/e2e/crypto/migration.spec.ts
  playwright/e2e/location/location.spec.ts
  playwright/e2e/oidc/oidc-aware.spec.ts
  playwright/e2e/oidc/oidc-native.spec.ts
  playwright/e2e/register/register.spec.ts
  playwright/e2e/right-panel/file-panel.spec.ts
  playwright/e2e/room-directory/room-directory.spec.ts
  playwright/e2e/settings/general-room-settings-tab.spec.ts
  playwright/e2e/settings/preferences-user-settings-tab.spec.ts
  playwright/e2e/spaces/spaces.spec.ts
  playwright/e2e/spaces/threads-activity-centre/threadsActivityCentre.spec.ts
  playwright/e2e/threads/threads.spec.ts
  playwright/e2e/timeline/timeline.spec.ts
  playwright/e2e/widgets/stickers.spec.ts
  playwright/element-web-test.ts
  playwright/plugins/docker/index.ts
Labels: T-Task

#28615 Delabs native OIDC support
  src/components/structures/auth/Login.tsx
  src/components/structures/auth/Registration.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/unit-tests/components/structures/UserMenu-test.tsx
  test/unit-tests/components/structures/auth/Login-test.tsx
  test/unit-tests/components/structures/auth/Registration-test.tsx
Labels: T-Enhancement

#28749 Simplify types
  package.json
  src/@types/png-chunks-extract.d.ts
  src/@types/sanitize-html.d.ts
  src/HtmlUtils.tsx
  src/Linkify.tsx
  yarn.lock
Labels: T-Task

#28808 Playwright: wait for the network listener on the postgres db
  playwright/plugins/postgres/index.ts
Labels: T-Defect

#28789 Enable node export condition in jest to consume ESM WASM packages
  jest.config.ts
Labels: T-Task

#28805 Remove stale OIDC aware docs and tests
  docs/oidc.md
  playwright/e2e/oidc/oidc-aware.spec.ts
  playwright/e2e/oidc/oidc-native.spec.ts
Labels: T-Task

#28787 OIDC settings tweaks
  scripts/analyse_unused_exports.ts
  src/components/views/dialogs/oidc/OidcLogoutDialog.tsx
  src/components/views/settings/devices/CurrentDeviceSection.tsx
  src/components/views/settings/devices/DeviceDetails.tsx
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/components/views/settings/tabs/user/AccountUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  src/utils/oidc/getOidcLogoutUrl.ts
  src/utils/oidc/urls.ts
  test/unit-tests/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/user/AccountUserSettingsTab-test.tsx
  test/unit-tests/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/AccountUserSettingsTab-test.tsx.snap
Labels: T-Enhancement
