Repository element-hq/element-web, pull requests merged in 2024-10, with the labels that each got.

#28130 Separate out tasks for each merge in the Prepare Release script
  .github/workflows/release_prepare.yml
Labels: T-Task

#28129 Remove legacy room header
  docs/labs.md
  element.io/develop/config.json
Labels: T-Task

#28148 Correct typo in option documentation
  docs/config.md
Labels: T-Defect, Z-Community-PR

#28151 Update prefetch composer icons to Compound
  src/vector/index.html
Labels: T-Task

#28152 Remove broken HMR support
  .env.example
  README.md
  package.json
  src/vector/devcss.ts
  src/vector/index.ts
  webpack.config.js
  yarn.lock
Labels: T-Task

#28157 Upgrade `compound-web` package
  package.json
  test/unit-tests/async-components/structures/__snapshots__/ErrorView-test.tsx.snap
  yarn.lock
Labels: T-Task

#28191 Update to Compound v7
  package.json
  yarn.lock
Labels: T-Task

#28173 Remove feature_dehydration
  docs/labs.md
Labels: T-Enhancement

#28204 Remove references to `MatrixClient.crypto`
  src/SlashCommands.tsx
  src/components/views/dialogs/DevtoolsDialog.tsx
  src/components/views/dialogs/devtools/VerificationExplorer.tsx
  src/i18n/strings/en_EN.json
  src/stores/SetupEncryptionStore.ts
  src/stores/widgets/StopGapWidgetDriver.ts
  test/test-utils/test-utils.ts
  test/unit-tests/SlashCommands-test.tsx
  test/unit-tests/components/views/dialogs/__snapshots__/DevtoolsDialog-test.tsx.snap
  test/unit-tests/components/views/settings/devices/LoginWithQR-test.tsx
  test/unit-tests/stores/widgets/StopGapWidgetDriver-test.ts
  test/unit-tests/stores/widgets/__snapshots__/StopGapWidgetDriver-test.ts.snap
Labels: T-Task

#28215 Pin GHA runner versions
  .github/workflows/backport.yml
  .github/workflows/build.yml
  .github/workflows/build_debian.yaml
  .github/workflows/build_develop.yml
  .github/workflows/dockerhub.yaml
  .github/workflows/docs.yml
  .github/workflows/issue_closed.yml
  .github/workflows/pending-reviews.yaml
  .github/workflows/release.yml
  .github/workflows/release_prepare.yml
  .github/workflows/static_analysis.yaml
  .github/workflows/triage-assigned.yml
  .github/workflows/triage-incoming.yml
  .github/workflows/triage-labelled.yml
  .github/workflows/triage-move-review-requests.yml
  .github/workflows/triage-stale-flaky-tests.yml
  .github/workflows/triage-unlabelled.yml
  .github/workflows/update-jitsi.yml
  .github/workflows/update-topics.yaml
Labels: T-Task

#28220 Fix network dropdown missing checkbox & aria-checked
  src/components/structures/GenericDropdownMenu.tsx
Labels: T-Defect

#28222 Deflake unskippable verification
  playwright/e2e/login/login.spec.ts
Labels: T-Task

#28223 Fix Ctrl+F shortcut not working with minimised room summary card
  src/stores/right-panel/RightPanelStore.ts
  src/stores/right-panel/RightPanelStoreIPanelState.ts
Labels: T-Defect

#28226 Port the flaky add/remove 3pid test to playwright
  playwright/e2e/settings/account-user-settings-tab.spec.ts
  test/unit-tests/components/views/settings/AddRemoveThreepids-test.tsx
Labels: T-Task

#28224 Deflake keyboard navigation test
  playwright/e2e/accessibility/keyboard-navigation.spec.ts
Labels: T-Task

#28227 Second batch: remove deprecated calls on `MatrixClient`
  src/SlashCommands.tsx
  test/test-utils/test-utils.ts
Labels: T-Task

#28225 Replace `Matrix.getKeyBackupEnabled` by `MatrixClient.CryptoApi.getActiveSessionBackupVersion`
  src/async-components/views/dialogs/security/NewRecoveryMethodDialog.tsx
  src/components/structures/MatrixChat.tsx
  test/test-utils/test-utils.ts
  test/unit-tests/async-components/dialogs/security/NewRecoveryMethodDialog-test.tsx
  test/unit-tests/async-components/dialogs/security/__snapshots__/NewRecoveryMethodDialog-test.tsx.snap
  test/unit-tests/components/structures/MatrixChat-test.tsx
Labels: T-Task

#28237 Remove openDesk variant
  .github/workflows/dockerhub.yaml
  variants/openDesk/README.md
  variants/openDesk/build_config.yaml
  variants/openDesk/customisations.json
  variants/openDesk/customisations.json.license
Labels: T-Task

#28236 Make Sonar happier
  src/AddThreepid.ts
  src/Avatar.ts
  src/ContentMessages.ts
  src/IdentityAuthClient.tsx
  src/Lifecycle.ts
  src/NodeAnimator.tsx
  src/Notifier.ts
  src/PosthogAnalytics.ts
  src/RoomInvite.tsx
  src/SlashCommands.tsx
  src/SlidingSyncManager.ts
  src/Terms.ts
  src/actions/RoomListActions.ts
  src/components/structures/MatrixChat.tsx
  src/components/views/dialogs/RoomUpgradeDialog.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/settings/AddRemoveThreepids.tsx
  test/unit-tests/Lifecycle-test.ts
Labels: T-Task

#28238 Replace `MatrixClient.isRoomEncrypted` by `MatrixClient.CryptoApi.isEncryptionEnabledInRoom` in `ContentMessages.ts`
  src/ContentMessages.ts
  test/test-utils/test-utils.ts
  test/unit-tests/ContentMessages-test.ts
Labels: T-Task

#28231 Replace legacy Tooltips with Compound tooltips
  package.json
  playwright/e2e/editing/editing.spec.ts
  playwright/e2e/register/register.spec.ts
  playwright/element-web-test.ts
  res/css/_components.pcss
  res/css/views/auth/_PassphraseField.pcss
  res/css/views/elements/_Field.pcss
  res/css/views/elements/_MiniAvatarUploader.pcss
  res/css/views/elements/_Tooltip.pcss
  res/css/views/elements/_Validation.pcss
  src/components/structures/ContextMenu.tsx
  src/components/structures/HomePage.tsx
  src/components/views/auth/EmailField.tsx
  src/components/views/auth/PassphraseConfirmField.tsx
  src/components/views/auth/PassphraseField.tsx
  src/components/views/auth/RegistrationForm.tsx
  src/components/views/context_menus/GenericTextContextMenu.tsx
  src/components/views/elements/CopyableText.tsx
  src/components/views/elements/Field.tsx
  src/components/views/elements/MiniAvatarUploader.tsx
  src/components/views/elements/Tooltip.tsx
  src/components/views/elements/Validation.tsx
  src/components/views/messages/CodeBlock.tsx
  src/components/views/messages/TextualBody.tsx
  src/components/views/settings/SetIdServer.tsx
  test/unit-tests/components/views/elements/Field-test.tsx
  test/unit-tests/components/views/messages/TextualBody-test.tsx
  test/unit-tests/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
  yarn.lock
Labels: T-Enhancement

#28244 Fix RTE mentions autocomplete test
  playwright/e2e/composer/RTE.spec.ts
Labels: T-Task

#28241 Close right panel chat when minimising maximised voip widget
  src/components/views/elements/AppTile.tsx
Labels: T-Defect

#28233 Remove deprecated `MatrixClient.keyBackupKeyFromPassword` call.
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/components/views/dialogs/security/RestoreKeyBackupDialog.tsx
  test/unit-tests/components/views/dialogs/security/CreateSecretStorageDialog-test.tsx
Labels: T-Task

#28239 Deduplicate icons using Compound
  playwright/e2e/timeline/timeline.spec.ts
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-Msg1-linux.png
  playwright/snapshots/polls/polls.spec.ts/ThreadView-with-a-poll-on-bubble-layout-linux.png
  playwright/snapshots/polls/polls.spec.ts/ThreadView-with-a-poll-on-group-layout-linux.png
  playwright/snapshots/threads/threads.spec.ts/Reply-to-the-location-on-ThreadView-linux.png
  playwright/snapshots/widgets/layout.spec.ts/apps-drawer-linux.png
  res/css/components/views/location/_ZoomButtons.pcss
  res/css/structures/_SpacePanel.pcss
  res/css/views/context_menus/_MessageContextMenu.pcss
  res/css/views/elements/_InviteReason.pcss
  res/css/views/messages/_MImageBody.pcss
  res/css/views/messages/_ViewSourceEvent.pcss
  res/css/views/right_panel/_BaseCard.pcss
  res/css/views/rooms/_EventTile.pcss
  res/css/views/rooms/_JumpToBottomButton.pcss
  res/css/views/rooms/_RoomListHeader.pcss
  res/css/views/rooms/_RoomSublist.pcss
  res/css/views/rooms/_TopUnreadMessagesBar.pcss
  res/css/views/voip/LegacyCallView/_LegacyCallViewButtons.pcss
  res/img/element-icons/add-photo.svg
  res/img/element-icons/community-rooms.svg
  res/img/element-icons/maximise-expand.svg
  res/img/element-icons/message/chevron-up.svg
  res/img/element-icons/message/overflow-large.svg
  res/img/element-icons/minimise-collapse.svg
  res/img/element-icons/minus-button.svg
  res/img/element-icons/plus-button.svg
  res/img/element-icons/plus.svg
  res/img/element-icons/roomlist/archived.svg
  res/img/element-icons/roomlist/plus.svg
  res/img/feather-customised/alert-triangle.svg
  res/img/feather-customised/eye.svg
  res/img/feather-customised/plus.svg
  res/img/feather-customised/widget/external-link.svg
  res/img/icon-address-delete.svg
  res/img/icon-email-user.svg
  res/img/icon-invite-people.svg
  res/img/icon-return.svg
  res/img/icon_context_delete.svg
  res/img/icons-create-room.svg
  res/img/icons-room-add.svg
  res/img/subtract.svg
  src/components/views/elements/AppTile.tsx
  src/components/views/location/ZoomButtons.tsx
  src/components/views/messages/ViewSourceEvent.tsx
  test/unit-tests/components/views/elements/__snapshots__/AppTile-test.tsx.snap
  test/unit-tests/components/views/location/__snapshots__/LocationViewDialog-test.tsx.snap
  test/unit-tests/components/views/location/__snapshots__/ZoomButtons-test.tsx.snap
Labels: T-Enhancement

#28243 Stabilise audio-player reply button clicking in playwright
  playwright/e2e/audio-player/audio-player.spec.ts
Labels: T-Task

#28216 Remove `MatrixClient.requestVerification` call
  src/components/views/right_panel/UserInfo.tsx
  src/verification.ts
  test/test-utils/test-utils.ts
Labels: T-Task

#28245 Enable "should find unknown people"
  playwright/e2e/spotlight/spotlight.spec.ts
Labels: T-Task

#28207 First batch: remove deprecated calls on `MatrixClient`
  src/SecurityManager.ts
  src/async-components/views/dialogs/security/CreateKeyBackupDialog.tsx
  src/components/structures/MatrixChat.tsx
  src/components/views/dialogs/security/AccessSecretStorageDialog.tsx
  src/components/views/dialogs/security/CreateCrossSigningDialog.tsx
  src/components/views/dialogs/security/RestoreKeyBackupDialog.tsx
  src/components/views/settings/CryptographyPanel.tsx
  src/verification.ts
  test/test-utils/client.ts
  test/test-utils/test-utils.ts
  test/unit-tests/MatrixClientPeg-test.ts
  test/unit-tests/components/structures/MatrixChat-test.tsx
  test/unit-tests/components/views/dialogs/security/CreateKeyBackupDialog-test.tsx
  test/unit-tests/components/views/right_panel/UserInfo-test.tsx
  test/unit-tests/components/views/settings/CrossSigningPanel-test.tsx
  test/unit-tests/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/unit-tests/toasts/UnverifiedSessionToast-test.tsx
Labels: T-Task

#28250 Fix pill contrast in invitation dialog
  playwright/snapshots/invite/invite-dialog.spec.ts/invite-dialog-dm-with-user-pill-linux.png
  playwright/snapshots/invite/invite-dialog.spec.ts/invite-dialog-room-with-user-pill-linux.png
  res/css/views/dialogs/_InviteDialog.pcss
Labels: T-Defect

#28253 Small tweaks & improvements
  .editorconfig
  .prettierignore
  jest.config.ts
  playwright/.gitignore
  sonar-project.properties
Labels: T-Task

#28257 Fix flake in pinned message e2e test due to tooltip
  playwright/e2e/pinned-messages/index.ts
Labels: T-Task

#28260 playwright: remove flaky check
  playwright/e2e/crypto/crypto.spec.ts
Labels: T-Task

#28254 Remove `MatrixClient.getDehydratedDevice` call
  src/stores/SetupEncryptionStore.ts
  test/unit-tests/stores/SetupEncryptionStore-test.ts
Labels: T-Task

#28263 Replace `IBootstrapCrossSigningOpts` by `BootstrapCrossSigningOpts` to use CryptoApi type instead of old crypto type.
  test/unit-tests/stores/SetupEncryptionStore-test.ts
Labels: T-Task

#28255 Hide scroll to bottom button in pinned message e2e test
  playwright/e2e/pinned-messages/pinned-messages.spec.ts
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-Msg1-linux.png
Labels: T-Task

#28218 Refactor CreateCrossSigningDialog
  src/CreateCrossSigning.ts
  src/components/structures/MatrixChat.tsx
  src/components/structures/auth/E2eSetup.tsx
  src/components/views/dialogs/security/CreateCrossSigningDialog.tsx
  test/CreateCrossSigning-test.ts
  test/components/views/dialogs/security/CreateCrossSigningDialog-test.tsx
  test/test-utils/test-utils.ts
  test/unit-tests/components/structures/MatrixChat-test.tsx
Labels: T-Task

#28259 Switch away from deprecated ReactDOM findDOMNode
  src/NodeAnimator.tsx
  src/components/structures/MessagePanel.tsx
  src/components/structures/ScrollPanel.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/messages/TextualBody.tsx
  src/components/views/rooms/Autocomplete.tsx
  test/unit-tests/components/structures/TimelinePanel-test.tsx
Labels: T-Task

#28268 Fix pinned message e2e flakes
  playwright/e2e/pinned-messages/index.ts
  playwright/e2e/pinned-messages/pinned-messages.spec.ts
Labels: T-Task

#28279 Fix other devices not being decorated as such
  src/components/views/settings/devices/DeviceDetails.tsx
  test/unit-tests/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/unit-tests/components/views/settings/devices/__snapshots__/DeviceDetails-test.tsx.snap
Labels: T-Defect

#28281 Replace `MatrixClient.isRoomEncrypted` by `MatrixClient.CryptoApi.isEncryptionEnabledInRoom` in `SecurityRoomSettingsTab`
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  test/test-utils/test-utils.ts
  test/unit-tests/components/views/settings/tabs/room/SecurityRoomSettingsTab-test.tsx
Labels: T-Task

#28289 Playwright: deflake verification tests
  playwright/e2e/crypto/user-verification.spec.ts
Labels: T-Task

#28258 Enable React StrictMode
  src/Modal.tsx
  src/components/views/elements/PersistedElement.tsx
  src/components/views/messages/TextualBody.tsx
  src/utils/pillify.tsx
  src/utils/tooltipify.tsx
  src/vector/app.tsx
  src/vector/init.tsx
Labels: T-Task

#28295 Add back unencrypted path in `StopGapWidgetDriver.sendToDevice`
  src/stores/widgets/StopGapWidgetDriver.ts
  test/unit-tests/stores/widgets/StopGapWidgetDriver-test.ts
Labels: T-Defect

#28309 Update screenshot for timezone difference
  playwright/snapshots/settings/preferences-user-settings-tab.spec.ts/Preferences-user-settings-tab-should-be-rendered-properly-1-linux.png
Labels: T-Task

#28287 Excluding floating-ui portals as part of hiding tooltips in Playwright screenshots
  playwright/e2e/pinned-messages/index.ts
  playwright/e2e/release-announcement/index.ts
  playwright/element-web-test.ts
  playwright/snapshots/threads/threads.spec.ts/Reply-to-the-location-on-ThreadView-linux.png
Labels: T-Task

#28292 Add PostHog codes for trust requirement failures
  package.json
  src/DecryptionFailureTracker.ts
  test/unit-tests/DecryptionFailureTracker-test.ts
  yarn.lock
Labels: T-Task

#28269 Fix 'remove alias' button in room settings
  res/css/views/elements/_EditableItemList.pcss
Labels: T-Defect, Z-Community-PR

#28288 Remove unused icons & styles
  playwright/snapshots/chat-export/html-export.spec.ts/html-export-linux.png
  res/css/_components.pcss
  res/css/structures/_RoomView.pcss
  res/css/views/rooms/_LegacyRoomHeader.pcss
  res/img/camera.svg
  res/img/element-icons/call/freedom.svg
  res/img/element-icons/call/spotlight.svg
  res/img/element-icons/reduce.svg
  res/img/feather-customised/edit.svg
  res/img/location/pointer.svg
  res/img/markdown.svg
  res/img/voip/signal-bars.svg
  src/utils/exportUtils/HtmlExport.tsx
  src/utils/exportUtils/exportCustomCSS.css
  test/unit-tests/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
Labels: T-Task

#28313 Enable Element Call by default on release instances
  element.io/app/config.json
  res/css/views/rooms/_RoomHeader.pcss
  src/components/views/rooms/RoomHeader.tsx
  src/hooks/room/useRoomCall.tsx
Labels: T-Enhancement, backport staging

#28314 Enable Element Call by default on release instances
  element.io/app/config.json
Labels: T-Enhancement

#28299 Remove upgrade encryption in `DeviceListener` and `SetupEncryptionToast`
  src/DeviceListener.ts
  src/i18n/strings/en_EN.json
  src/toasts/SetupEncryptionToast.ts
  test/unit-tests/DeviceListener-test.ts
Labels: T-Defect

#28315 Support sending encrypted to device messages from widgets
  src/stores/widgets/StopGapWidgetDriver.ts
  test/unit-tests/stores/widgets/StopGapWidgetDriver-test.ts
Labels: T-Enhancement

#28290 Remove "Upgrade your encryption" flow in `CreateSecretStorageDialog`
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/i18n/strings/en_EN.json
  test/test-utils/test-utils.ts
  test/unit-tests/components/views/dialogs/security/CreateSecretStorageDialog-test.tsx
  test/unit-tests/components/views/dialogs/security/__snapshots__/CreateSecretStorageDialog-test.tsx.snap
Labels: T-Defect

#17233 Documentation fix: missing comma and I would also take the ellipsis away
  docs/theming.md
Labels: T-Task

#28339 Pass nodeRef to CSSTransition to avoid ReactDOM.findDOMNode
  src/components/views/messages/MImageBody.tsx
  src/components/views/rooms/RoomBreadcrumbs.tsx
Labels: T-Task
