Repository element-hq/element-web, pull requests merged in 2025-09, with the labels that each got.

#30656 Add checklist item to ensure that people read the review guidelines and contributing guide
  .github/PULL_REQUEST_TEMPLATE.md
Labels: T-Task

#30649 Fix stable-suffixed MSC4133 support
  src/settings/Settings.tsx
Labels: T-Defect

#30558 A11y: improve accessibility of pinned messages
  res/css/views/messages/_PinnedMessageBadge.pcss
  src/components/views/messages/IBodyProps.ts
  src/components/views/messages/MessageEvent.tsx
  src/components/views/messages/PinnedMessageBadge.tsx
  src/components/views/messages/TextualBody.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/PinnedEventTile.tsx
  src/components/views/rooms/PinnedMessageBanner.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/unit-tests/components/views/right_panel/__snapshots__/PinnedMessagesCard-test.tsx.snap
  test/unit-tests/components/views/rooms/PinnedMessageBanner-test.tsx
  test/unit-tests/components/views/rooms/__snapshots__/PinnedEventTile-test.tsx.snap
  test/unit-tests/components/views/rooms/__snapshots__/PinnedMessageBanner-test.tsx.snap
  test/unit-tests/components/views/settings/__snapshots__/LayoutSwitcher-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/AppearanceUserSettingsTab-test.tsx.snap
  test/unit-tests/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
Labels: T-Defect

#30663 Update m.topic tests
  test/unit-tests/TextForEvent-test.ts
Labels: T-Task, Z-Community-PR

#30318 Add Playwright tests for settings toggles
  playwright/e2e/create-room/create-room.spec.ts
  playwright/e2e/devtools/devtools.spec.ts
  playwright/e2e/devtools/upgraderoom.spec.ts
  playwright/e2e/invite/decline-and-block-invite-dialog.spec.ts
  playwright/e2e/location/location.spec.ts
  playwright/e2e/room/create-room.spec.ts
  playwright/e2e/settings/notifications/notifications-settings-2-tab.spec.ts
  playwright/e2e/settings/notifications/notifications-settings-tab.spec.ts
  playwright/e2e/settings/room-settings/roles-permissions-room-settings-tab.spec.ts
  playwright/e2e/settings/room-settings/room-security-tab.spec.ts
  playwright/e2e/settings/room-settings/room-video-tab.spec.ts
  playwright/e2e/settings/security-user-settings-tab.spec.ts
  playwright/e2e/spaces/spaces.spec.ts
  playwright/e2e/widgets/permissions-dialog.spec.ts
  playwright/pages/ElementAppPage.ts
  playwright/pages/settings.ts
  playwright/snapshots/devtools/devtools.spec.ts/devtools-dialog-linux.png
  playwright/snapshots/devtools/upgraderoom.spec.ts/upgrade-room-linux.png
  playwright/snapshots/invite/decline-and-block-invite-dialog.spec.ts/decline-and-block-invite-empty-linux.png
  playwright/snapshots/location/location.spec.ts/location-live-share-dialog-linux.png
  playwright/snapshots/room/create-room.spec.ts/create-room-linux.png
  playwright/snapshots/room/create-room.spec.ts/create-video-room-linux.png
  playwright/snapshots/settings/notifications/notifications-settings-2-tab.spec.ts/standard-notifications-2-settings-linux.png
  playwright/snapshots/settings/notifications/notifications-settings-tab.spec.ts/standard-notification-settings-linux.png
  playwright/snapshots/settings/room-settings/room-security-tab.spec.ts/room-security-settings-linux.png
  playwright/snapshots/settings/room-settings/room-video-tab.spec.ts/room-video-settings-linux.png
  playwright/snapshots/settings/security-user-settings-tab.spec.ts/security-settings-tab-linux.png
  playwright/snapshots/spaces/spaces.spec.ts/space-visibility-settings-linux.png
  playwright/snapshots/widgets/layout.spec.ts/apps-drawer-linux.png
  playwright/snapshots/widgets/permissions-dialog.spec.ts/widget-capabilites-prompt-linux.png
  res/css/views/dialogs/_DevtoolsDialog.pcss
  res/css/views/rooms/_AppsDrawer.pcss
  src/components/views/avatars/WidgetAvatar.tsx
  src/components/views/dialogs/DevtoolsDialog.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/right_panel/WidgetCard.tsx
  src/components/views/settings/Notifications.tsx
  src/components/views/settings/notifications/NotificationSettings2.tsx
  src/components/views/settings/shared/SettingsSubsectionHeading.tsx
  test/unit-tests/components/views/dialogs/__snapshots__/DevtoolsDialog-test.tsx.snap
  test/unit-tests/components/views/elements/__snapshots__/AppTile-test.tsx.snap
  test/unit-tests/components/views/right_panel/__snapshots__/ExtensionsCard-test.tsx.snap
  test/unit-tests/components/views/settings/notifications/__snapshots__/Notifications2-test.tsx.snap
Labels: T-Task

#30664 Block change recovery key button while a change is ongoing.
  playwright/e2e/settings/encryption-user-tab/index.ts
  src/components/views/settings/encryption/ChangeRecoveryKey.tsx
  test/unit-tests/components/views/settings/encryption/ChangeRecoveryKey-test.tsx
Labels: T-Defect

#30699 Ensure container starts if it is mounted with an empty /modules directory.
  docker/docker-entrypoint.d/18-load-element-modules.sh
Labels: T-Defect

#30702 Remove remaining support for outdated .well-known settings
  src/SecurityManager.ts
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/utils/WellKnownUtils.ts
Labels: T-Deprecation

#30713 Automatically adjust history visibility when making a room private
  playwright/e2e/settings/room-settings/room-security-tab.spec.ts
  playwright/snapshots/settings/room-settings/room-security-tab.spec.ts/room-security-settings-linux.png
  playwright/snapshots/settings/room-settings/room-security-tab.spec.ts/room-security-settings-world-readable-linux.png
  src/components/views/settings/JoinRuleSettings.tsx
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/views/settings/tabs/room/SecurityRoomSettingsTab-test.tsx
  test/unit-tests/components/views/settings/tabs/room/__snapshots__/SecurityRoomSettingsTab-test.tsx.snap
Labels: T-Enhancement

#30724 Upgrade compound-web for AXE fix
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListHeaderView-test.tsx.snap
  test/unit-tests/components/views/spaces/__snapshots__/QuickSettingsButton-test.tsx.snap
  yarn.lock
Labels: T-Task

#30731 Fix flaky shields playwright test
  playwright/e2e/crypto/event-shields.spec.ts
  playwright/e2e/crypto/toasts.spec.ts
  playwright/e2e/crypto/utils.ts
Labels: T-Task

#30726 Remove 'beta' pill from Element Call option
  src/hooks/room/useRoomCall.tsx
Labels: T-Task

#30768 Hold Electron toasts until after the client starts
  src/vector/platform/ElectronPlatform.tsx
  test/unit-tests/vector/platform/ElectronPlatform-test.ts
Labels: T-Task, X-Release-Blocker, backport staging

#30770 Don't show release announcements while toasts are displayed
  playwright/e2e/release-announcement/releaseAnnouncement.spec.ts
  playwright/snapshots/release-announcement/releaseAnnouncement.spec.ts/release-announcement-Chats-has-a-new-look--linux.png
  src/stores/ReleaseAnnouncementStore.ts
  test/unit-tests/stores/ReleaseAnnouncementStore-test.tsx
Labels: T-Defect

#30787 Avoid flicker of the room list filter on resize
  src/components/views/rooms/RoomListPanel/RoomListPrimaryFilters.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListPrimaryFilters-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPrimaryFilters-test.tsx.snap
Labels: T-Defect, backport staging

#30799 Storybook: load story when language is set
  .storybook/preview.tsx
Labels: T-Task

#30804 Update Message Sound for Element
  res/media/message.mp3
  res/media/message.ogg
Labels: T-Enhancement, Z-Community-PR

#30870 Fix theoretical bug where VerificationRequestDialog uses an outdated request
  src/components/views/dialogs/VerificationRequestDialog.tsx
  test/unit-tests/components/views/dialogs/VerificationRequestDialog-test.tsx
  test/unit-tests/components/views/dialogs/__snapshots__/VerificationRequestDialog-test.tsx.snap
Labels: T-Task

#30872 Update mvvm doc
  docs/MVVM-v1.md
  docs/MVVM.md
Labels: T-Task

#30878 Fix a11y issue on list in invite dialog
  src/shared-components/hooks/useListKeyDown.test.ts
  src/shared-components/hooks/useListKeyDown.ts
  src/shared-components/rich-list/RichItem/RichItem.module.css
  src/shared-components/rich-list/RichItem/RichItem.tsx
  src/shared-components/rich-list/RichItem/__snapshots__/RichItem.test.tsx.snap
  src/shared-components/rich-list/RichList/RichList.tsx
  src/shared-components/rich-list/RichList/__snapshots__/RichList.test.tsx.snap
Labels: T-Defect

#30903 New Room List: Don't clear filters on space change
  src/components/viewmodels/roomlist/useFilteredRooms.tsx
  test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
Labels: T-Enhancement

#30907 Improve accessibility of the `<AvatarSetting> component
  src/components/views/room_settings/RoomProfileSettings.tsx
  src/components/views/settings/AvatarSetting.tsx
  src/components/views/settings/UserProfileSettings.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/views/settings/AvatarSetting-test.tsx
Labels: T-Defect
