Repository element-hq/element-web, pull requests merged in 2025-02, with the labels that each got.

#29128 Always show back button in the right panel
  playwright/e2e/read-receipts/index.ts
  playwright/snapshots/right-panel/memberlist.spec.ts/with-four-members-linux.png
  src/stores/right-panel/RightPanelStore.ts
  test/unit-tests/stores/right-panel/RightPanelStore-test.ts
Labels: T-Enhancement

#29129 Encryption tab: hide `Advanced` section when the key storage is out of sync
  playwright/e2e/settings/encryption-user-tab/encryption-tab.spec.ts
  playwright/e2e/settings/encryption-user-tab/recovery.spec.ts
  playwright/snapshots/settings/encryption-user-tab/encryption-tab.spec.ts/default-tab-linux.png
  playwright/snapshots/settings/encryption-user-tab/encryption-tab.spec.ts/out-of-sync-recovery-linux.png
  playwright/snapshots/settings/encryption-user-tab/encryption-tab.spec.ts/verify-device-encryption-tab-linux.png
  playwright/snapshots/settings/encryption-user-tab/recovery.spec.ts/out-of-sync-recovery-linux.png
  src/components/views/settings/encryption/RecoveryPanel.tsx
  src/components/views/settings/encryption/RecoveryPanelOutOfSync.tsx
  src/components/views/settings/tabs/user/EncryptionUserSettingsTab.tsx
  test/unit-tests/components/views/settings/encryption/RecoveryPanel-test.tsx
  test/unit-tests/components/views/settings/encryption/__snapshots__/RecoveryPanel-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/user/EncryptionUserSettingsTab-test.tsx
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/EncryptionUserSettingsTab-test.tsx.snap
Labels: T-Defect

#29163 Make profile header section match the designs
  playwright/snapshots/user-view/user-view.spec.ts/user-info-linux.png
  res/css/views/right_panel/_UserInfo.pcss
  src/components/views/right_panel/UserInfo.tsx
  test/unit-tests/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
Labels: T-Enhancement

#29152 Improve rendering of empty topics in the timeline
  src/TextForEvent.tsx
  src/components/views/room_settings/RoomProfileSettings.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/TextForEvent-test.ts
Labels: T-Enhancement

#29159 Apply lint rule @typescript-eslint/no-empty-object-type
  .eslintrc.js
  playwright/pages/client.ts
  src/@types/diff-dom.d.ts
  src/@types/matrix-js-sdk.d.ts
  src/@types/react.d.ts
  src/AddThreepid.ts
  src/WorkerManager.ts
  src/autocomplete/QueryMatcher.ts
  src/components/structures/AutoHideScrollbar.tsx
  src/components/structures/NonUrgentToastContainer.tsx
  src/components/structures/ToastContainer.tsx
  src/components/structures/auth/header/AuthHeaderProvider.tsx
  src/components/views/audio_messages/Waveform.tsx
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  src/components/views/auth/Welcome.tsx
  src/components/views/elements/EditableItemList.tsx
  src/components/views/elements/StyledCheckbox.tsx
  src/components/views/elements/StyledRadioButton.tsx
  src/components/views/rooms/Autocomplete.tsx
  src/components/views/rooms/RoomBreadcrumbs.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/utils.ts
  src/components/views/settings/CrossSigningPanel.tsx
  src/components/views/settings/CryptographyPanel.tsx
  src/components/views/settings/EventIndexPanel.tsx
  src/components/views/settings/FontScalingPanel.tsx
  src/components/views/settings/ImageSizePanel.tsx
  src/components/views/settings/Notifications.tsx
  src/components/views/settings/SecureBackupPanel.tsx
  src/components/views/settings/SetIntegrationManager.tsx
  src/components/views/settings/tabs/user/AppearanceUserSettingsTab.tsx
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  src/components/views/settings/tabs/user/LabsUserSettingsTab.tsx
  src/components/views/settings/tabs/user/MjolnirUserSettingsTab.tsx
  src/components/views/settings/tabs/user/VoiceUserSettingsTab.tsx
  src/contexts/MatrixClientContext.tsx
  src/editor/autocomplete.ts
  src/hooks/useAccountData.ts
  src/stores/CallStore.ts
  src/stores/WidgetStore.ts
  src/stores/notifications/RoomNotificationStateStore.ts
  src/stores/room-list/MessagePreviewStore.ts
  src/stores/room-list/RoomListLayoutStore.ts
  src/stores/room-list/RoomListStore.ts
  src/stores/room-list/SlidingRoomListStore.ts
  src/stores/spaces/SpaceStore.ts
  src/stores/widgets/WidgetMessagingStore.ts
  src/utils/MultiInviter.ts
  src/utils/PinningUtils.ts
  src/utils/notifications.ts
  src/utils/objects.ts
  src/vector/app.tsx
  src/vector/init.tsx
  src/vector/platform/IPCManager.ts
  test/unit-tests/components/views/settings/tabs/user/LabsUserSettingsTab-test.tsx
  test/unit-tests/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/unit-tests/hooks/useProfileInfo-test.tsx
Labels: T-Task

#29138 Wire up the "Forgot recovery key" button for the "Key storage out of sync" toast
  playwright/e2e/crypto/toasts.spec.ts
  playwright/e2e/crypto/utils.ts
  playwright/snapshots/crypto/toasts.spec.ts/key-storage-out-of-sync-toast-linux.png
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/settings/encryption/ResetIdentityPanel.tsx
  src/components/views/settings/tabs/user/EncryptionUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/toasts/SetupEncryptionToast.ts
  test/unit-tests/components/views/dialogs/UserSettingsDialog-test.tsx
  test/unit-tests/components/views/settings/encryption/ResetIdentityPanel-test.tsx
  test/unit-tests/components/views/settings/encryption/__snapshots__/ResetIdentityPanel-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/user/EncryptionUserSettingsTab-test.tsx
  test/unit-tests/toasts/SetupEncryptionToast-test.tsx
Labels: T-Defect

#29168 Update package description
  debian/control
  package.json
Labels: T-Task

#29201 Add KeyIcon to key storage out of sync toast
  playwright/snapshots/crypto/toasts.spec.ts/key-storage-out-of-sync-toast-linux.png
  src/toasts/SetupEncryptionToast.ts
Labels: T-Enhancement

#29202 Add `Forgot recovery key?` button to encryption tab
  playwright/e2e/settings/encryption-user-tab/encryption-tab.spec.ts
  playwright/snapshots/settings/encryption-user-tab/encryption-tab.spec.ts/out-of-sync-recovery-linux.png
  res/css/_components.pcss
  res/css/views/settings/encryption/_RecoveryPanelOutOfSync.pcss
  src/components/views/settings/encryption/RecoveryPanelOutOfSync.tsx
  src/components/views/settings/tabs/user/EncryptionUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/views/settings/encryption/RecoveryPanelOutOfSync-test.tsx
  test/unit-tests/components/views/settings/encryption/__snapshots__/RecoveryPanelOutOfSync-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/user/EncryptionUserSettingsTab-test.tsx
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/EncryptionUserSettingsTab-test.tsx.snap
Labels: T-Enhancement

#29210 Add `code_style`, `developer_guide` and fix `CONTRIBUTING.md`
  CONTRIBUTING.md
  README.md
  code_style.md
  developer_guide.md
Labels: T-Task

#29104 Initial support for runtime modules
  docs/config.md
  jest.config.ts
  package.json
  playwright/e2e/modules/loader.spec.ts
  playwright/sample-files/example-module.js
  src/@types/global.d.ts
  src/IConfigOptions.ts
  src/customisations/Alias.ts
  src/customisations/ChatExport.ts
  src/customisations/ComponentVisibility.ts
  src/customisations/Directory.ts
  src/customisations/Lifecycle.ts
  src/customisations/Media.ts
  src/customisations/RoomList.ts
  src/customisations/UserIdentifier.ts
  src/customisations/WidgetPermissions.ts
  src/customisations/WidgetVariables.ts
  src/modules/Api.ts
  src/vector/app.tsx
  src/vector/index.ts
  src/vector/init.tsx
  yarn.lock
Labels: T-Enhancement

#29214 e2e test: by default the bot should not use a passphrase to create the recovery key
  playwright/e2e/crypto/device-verification.spec.ts
  playwright/e2e/crypto/toasts.spec.ts
  playwright/e2e/crypto/utils.ts
  playwright/e2e/settings/encryption-user-tab/encryption-tab.spec.ts
  playwright/e2e/settings/encryption-user-tab/index.ts
  playwright/e2e/settings/encryption-user-tab/recovery.spec.ts
  playwright/pages/bot.ts
Labels: T-Task

#29212 Close stale PRs after 180 days
  .github/workflows/triage-stale-flaky-tests.yml
  .github/workflows/triage-stale.yml
Labels: T-Task

#29216 Encryption tab: display correct encryption panel when user cancels the reset identity flow
  src/components/views/settings/tabs/user/EncryptionUserSettingsTab.tsx
  test/unit-tests/components/views/settings/tabs/user/EncryptionUserSettingsTab-test.tsx
Labels: T-Defect

#29200 Add new verification section to user profile
  playwright/e2e/crypto/dehydration.spec.ts
  playwright/e2e/crypto/event-shields.spec.ts
  playwright/e2e/crypto/user-verification.spec.ts
  playwright/e2e/crypto/utils.ts
  playwright/e2e/user-view/user-view.spec.ts
  playwright/snapshots/user-view/user-view.spec.ts/user-info-linux.png
  res/css/views/right_panel/_UserInfo.pcss
  src/components/views/right_panel/UserInfo.tsx
  src/i18n/strings/en_EN.json
  src/verification.ts
  test/unit-tests/components/structures/TabbedView-test.tsx
  test/unit-tests/components/structures/__snapshots__/TabbedView-test.tsx.snap
  test/unit-tests/components/views/right_panel/UserInfo-test.tsx
  test/unit-tests/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
Labels: T-Enhancement

#28577 Revert `GoToHome` keyboard shortcut to `Ctrl`–`Shift`–`H` on macOS
  src/accessibility/KeyboardShortcuts.ts
Labels: T-Defect, Z-Community-PR

#29217 Rename "security key" into "recovery key"
  docs/config.md
  playwright/e2e/crypto/backups.spec.ts
  playwright/e2e/crypto/crypto.spec.ts
  playwright/e2e/crypto/device-verification.spec.ts
  playwright/e2e/crypto/toasts.spec.ts
  playwright/e2e/crypto/utils.ts
  playwright/e2e/settings/encryption-user-tab/index.ts
  src/i18n/strings/en_EN.json
  test/unit-tests/components/views/dialogs/AccessSecretStorageDialog-test.tsx
  test/unit-tests/components/views/dialogs/security/CreateSecretStorageDialog-test.tsx
  test/unit-tests/components/views/dialogs/security/RestoreKeyBackupDialog-test.tsx
  test/unit-tests/components/views/dialogs/security/__snapshots__/CreateSecretStorageDialog-test.tsx.snap
  test/unit-tests/components/views/dialogs/security/__snapshots__/RestoreKeyBackupDialog-test.tsx.snap
  test/unit-tests/components/views/settings/__snapshots__/SecureBackupPanel-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/SecurityUserSettingsTab-test.tsx.snap
Labels: T-Enhancement

#29146 test(backup mas): use `checkDeviceIsConnectedKeyBackup` instead at looking at the `Security & Privacy` tab
  playwright/e2e/crypto/backups-mas.spec.ts
  playwright/e2e/crypto/utils.ts
Labels: T-Task

#29225 Restore the accessibility role on call views
  src/components/views/voip/CallView.tsx
  test/unit-tests/components/views/voip/CallView-test.tsx
Labels: T-Defect

#29235 Log when we show, and hide, encryption setup toasts
  src/DeviceListener.ts
  src/stores/ToastStore.ts
  test/unit-tests/DeviceListener-test.ts
Labels: X-Release-Blocker, T-Enhancement, backport staging

#29238 [Backport staging] Log when we show, and hide, encryption setup toasts
  src/DeviceListener.ts
  src/stores/ToastStore.ts
  test/unit-tests/DeviceListener-test.ts
Labels: X-Release-Blocker, T-Enhancement

#29243 Don't reload roomview on offline connectivity check
  src/components/structures/RoomView.tsx
  test/unit-tests/components/structures/RoomView-test.tsx
Labels: T-Defect

#29239 New Room List: Create new labs flag
  docs/labs.md
  src/components/structures/LeftPanel.tsx
  src/components/views/rooms/LegacyRoomList.tsx
  src/components/views/rooms/RoomListView.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/stores/spaces/SpaceStore.ts
  test/unit-tests/components/views/rooms/LegacyRoomList-test.tsx
Labels: T-Enhancement

#29241 New room list: hide favourites and people meta spaces
  res/css/structures/_QuickSettingsButton.pcss
  src/components/views/settings/tabs/user/SidebarUserSettingsTab.tsx
  src/components/views/spaces/QuickSettingsButton.tsx
  src/stores/spaces/SpaceStore.ts
  test/unit-tests/stores/SpaceStore-test.ts
Labels: T-Enhancement

#29259 Replace `focus_room_filter` dispatch by `Action.OpenSpotlight`
  src/components/structures/LoggedInView.tsx
  src/components/structures/RoomSearch.tsx
  test/unit-tests/components/structures/LoggedInView-test.tsx
Labels: T-Task

#29257 Render reason for invite rejection.
  src/TextForEvent.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/TextForEvent-test.ts
Labels: T-Enhancement

#29261 Minor cleanups to `initialiseDehydration`
  src/MatrixClientPeg.ts
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/stores/SetupEncryptionStore.ts
  src/utils/device/dehydration.ts
Labels: T-Task

#29265 Dehydration: enable dehydrated device on "Set up recovery"
  playwright/e2e/crypto/dehydration.spec.ts
  src/components/views/settings/encryption/ChangeRecoveryKey.tsx
Labels: T-Enhancement

#29267 Grow member list search field when resizing the right panel
  res/css/views/rooms/_MemberListHeaderView.pcss
Labels: T-Defect

#29262 ChangeRecoveryKey: error handling
  src/components/views/settings/encryption/ChangeRecoveryKey.tsx
  src/utils/ErrorUtils.tsx
  test/unit-tests/components/views/settings/encryption/ChangeRecoveryKey-test.tsx
  test/unit-tests/components/views/settings/encryption/__snapshots__/ChangeRecoveryKey-test.tsx.snap
Labels: T-Enhancement

#29255 Fix up UIA types and remove unused prop
  src/AddThreepid.ts
  src/CreateCrossSigning.ts
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/components/structures/InteractiveAuth.tsx
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  src/components/views/dialogs/InteractiveAuthDialog.tsx
  test/unit-tests/components/views/auth/InteractiveAuthEntryComponents-test.tsx
Labels: T-Task

#29268 Fix CODEOWNERS for `src/components/views/settings/encryption`
  .github/CODEOWNERS
Labels: T-Task

#29285 Fix font scaling in member list
  res/css/views/rooms/_MemberTileView.pcss
Labels: T-Defect

#29269 Factor out duplicated CSS for buttons in encryption settings
  res/css/views/settings/encryption/_ChangeRecoveryKey.pcss
  res/css/views/settings/encryption/_EncryptionCard.pcss
  res/css/views/settings/encryption/_ResetIdentityPanel.pcss
  src/components/views/settings/encryption/ChangeRecoveryKey.tsx
  src/components/views/settings/encryption/EncryptionCardButtons.tsx
  src/components/views/settings/encryption/ResetIdentityPanel.tsx
  test/unit-tests/components/views/settings/encryption/__snapshots__/ChangeRecoveryKey-test.tsx.snap
  test/unit-tests/components/views/settings/encryption/__snapshots__/ResetIdentityPanel-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/EncryptionUserSettingsTab-test.tsx.snap
Labels: T-Task

#29290 Honour the backup disable flag from Element X
  src/DeviceListener.ts
  test/unit-tests/DeviceListener-test.ts
Labels: T-Enhancement

#29316 Add some basic documentation for MVVM pattern
  docs/MVVM.md
Labels: T-Task

#29319 Move `view_create_chat` & `view_create_room` to `actions.ts`
  src/components/structures/HomePage.tsx
  src/components/structures/MatrixChat.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/rooms/LegacyRoomList.tsx
  src/components/views/rooms/LegacyRoomListHeader.tsx
  src/dispatcher/actions.ts
Labels: T-Task, X-Run-All-Tests

#29312 Add Windows 64-bit arm link and remove 32-bit link on compatibility page
  docs/config.md
  playwright/snapshots/app-loading/feature-detection.spec.ts/unsupported-browser-CompatibilityView-linux.png
  src/IConfigOptions.ts
  src/SdkConfig.ts
  src/async-components/structures/ErrorView.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/async-components/structures/__snapshots__/ErrorView-test.tsx.snap
  test/unit-tests/vector/__snapshots__/init-test.ts.snap
Labels: T-Enhancement

#29311 Move CSS for ResetIdentityPanel into EncryptionCard
  res/css/_components.pcss
  res/css/views/settings/encryption/_EncryptionCardEmphasisedContent.pcss
  res/css/views/settings/encryption/_ResetIdentityPanel.pcss
  src/components/utils/Flex.tsx
  src/components/views/settings/encryption/EncryptionCardEmphasisedContent.tsx
  src/components/views/settings/encryption/ResetIdentityPanel.tsx
  test/unit-tests/components/views/settings/encryption/__snapshots__/ResetIdentityPanel-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/EncryptionUserSettingsTab-test.tsx.snap
Labels: T-Task

#29320 First step to add header to new room list
  playwright/e2e/left-panel/room-list-view/room-list-header.spec.ts
  playwright/snapshots/left-panel/room-list-view/room-list-header.spec.ts/room-list-header-compose-menu-linux.png
  playwright/snapshots/left-panel/room-list-view/room-list-header.spec.ts/room-list-header-linux.png
  playwright/snapshots/left-panel/room-list-view/room-list-view.spec.ts/room-list-view-linux.png
  res/css/_components.pcss
  res/css/views/rooms/RoomListView/_RoomListHeaderView.pcss
  src/components/viewmodels/roomlist/RoomListHeaderViewModel.tsx
  src/components/views/rooms/RoomListView/RoomListHeaderView.tsx
  src/components/views/rooms/RoomListView/RoomListView.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/viewmodels/roomlist/RoomListHeaderViewModel-test.tsx
  test/unit-tests/components/views/rooms/RoomListView/RoomListHeaderView-test.tsx
  test/unit-tests/components/views/rooms/RoomListView/__snapshots__/RoomListHeaderView-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListView/__snapshots__/RoomListView-test.tsx.snap
Labels: T-Enhancement

#29271 Add padding to room header icon
  playwright/e2e/room/room-header.spec.ts
  playwright/snapshots/room/room-header.spec.ts/room-header-with-icon-linux.png
  res/css/views/rooms/_RoomHeader.pcss
Labels: T-Defect

#29280 Use EditInPlace control for Identity Server picker to improve a11y
  playwright/e2e/settings/security-user-settings-tab.spec.ts
  res/css/_common.pcss
  res/css/_components.pcss
  res/css/views/settings/_SetIdServer.pcss
  src/components/views/settings/SetIdServer.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/views/settings/SetIdServer-test.tsx
  test/unit-tests/components/views/settings/__snapshots__/SetIdServer-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/SecurityUserSettingsTab-test.tsx.snap
Labels: T-Enhancement

#29331 Fix 3pid timeout flakes
  test/unit-tests/components/views/settings/AddRemoveThreepids-test.tsx
Labels: T-Task

#29332 Fix SyntaxHighlight flake
  test/unit-tests/components/views/elements/SyntaxHighlight-test.tsx
  test/unit-tests/components/views/elements/__snapshots__/SyntaxHighlight-test.tsx.snap
Labels: T-Task

#29335 Fix test that doesn't make sense in usePublicRoomDirectory-test.tsx
  test/unit-tests/hooks/usePublicRoomDirectory-test.tsx
Labels: T-Task

#29347 New room list: add compose menu for spaces in header
  playwright/e2e/left-panel/room-list-view/room-list-header.spec.ts
  src/components/viewmodels/roomlist/RoomListHeaderViewModel.tsx
  test/unit-tests/components/viewmodels/roomlist/RoomListHeaderViewModel-test.tsx
Labels: T-Enhancement

#29346 Dynamically load Element Web modules in Docker entrypoint
  .github/workflows/docker.yaml
  Dockerfile
  docker/docker-entrypoint.d/18-load-element-modules.sh
  docker/nginx-templates/default.conf.template
  docs/install.md
Labels: X-Release-Blocker, T-Enhancement, backport staging

#29334 Minor CSS fixes for the new room list
  playwright/snapshots/left-panel/room-list-view/room-list-header.spec.ts/room-list-header-linux.png
  playwright/snapshots/left-panel/room-list-view/room-list-view.spec.ts/room-list-view-linux.png
  res/css/views/rooms/RoomListView/_RoomListHeaderView.pcss
  res/css/views/rooms/RoomListView/_RoomListSearch.pcss
Labels: T-Defect

#29358 [backport] Dynamically load Element Web modules in Docker entrypoint
  .github/workflows/docker.yaml
  Dockerfile
  docker/docker-entrypoint.d/18-load-element-modules.sh
  docker/nginx-templates/default.conf.template
  docs/install.md
Labels: X-Release-Blocker, T-Enhancement

#29348 Dismiss "Key storage out of sync" toast when secrets received
  playwright/e2e/crypto/device-verification.spec.ts
  src/DeviceListener.ts
  test/unit-tests/DeviceListener-test.ts
Labels: T-Defect

#29345 Room List - Store sorted rooms in skip list
  src/stores/room-list-v3/skip-list/Level.ts
  src/stores/room-list-v3/skip-list/RoomNode.ts
  src/stores/room-list-v3/skip-list/RoomSkipList.ts
  src/stores/room-list-v3/skip-list/sorters/AlphabeticSorter.ts
  src/stores/room-list-v3/skip-list/sorters/RecencySorter.ts
  src/stores/room-list-v3/skip-list/sorters/index.ts
  src/stores/room-list-v3/skip-list/utils.ts
  src/stores/room-list/algorithms/tag-sorting/RecentAlgorithm.ts
  test/unit-tests/stores/room-list-v3/skip-list/RoomSkipList-test.ts
Labels: T-Enhancement

#29352 New room list: add space menu in room header
  playwright/e2e/left-panel/room-list-view/room-list-header.spec.ts
  playwright/snapshots/left-panel/room-list-view/room-list-header.spec.ts/room-list-header-space-menu-linux.png
  playwright/snapshots/left-panel/room-list-view/room-list-header.spec.ts/room-list-space-header-linux.png
  res/css/views/rooms/RoomListView/_RoomListHeaderView.pcss
  src/components/viewmodels/roomlist/RoomListHeaderViewModel.tsx
  src/components/views/rooms/RoomListView/RoomListHeaderView.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/viewmodels/roomlist/RoomListHeaderViewModel-test.tsx
  test/unit-tests/components/views/rooms/RoomListView/RoomListHeaderView-test.tsx
  test/unit-tests/components/views/rooms/RoomListView/__snapshots__/RoomListHeaderView-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListView/__snapshots__/RoomListView-test.tsx.snap
Labels: T-Enhancement

#29361 New room list: rename `RoomListView` as `RoomListPanel`
  playwright/e2e/left-panel/room-list-panel/room-list-header.spec.ts
  playwright/e2e/left-panel/room-list-panel/room-list-panel.spec.ts
  playwright/e2e/left-panel/room-list-panel/room-list-search.spec.ts
  playwright/snapshots/left-panel/room-list-panel/room-list-header.spec.ts/room-list-header-compose-menu-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-header.spec.ts/room-list-header-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-header.spec.ts/room-list-header-space-menu-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-header.spec.ts/room-list-space-header-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-panel.spec.ts/room-list-panel-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-search.spec.ts/search-section-linux.png
  playwright/snapshots/left-panel/room-list-view/room-list-header.spec.ts/room-list-header-compose-menu-linux.png
  playwright/snapshots/left-panel/room-list-view/room-list-header.spec.ts/room-list-header-linux.png
  playwright/snapshots/left-panel/room-list-view/room-list-search.spec.ts/search-section-linux.png
  playwright/snapshots/left-panel/room-list-view/room-list-view.spec.ts/room-list-view-linux.png
  res/css/_components.pcss
  res/css/views/rooms/RoomListPanel/_RoomListHeaderView.pcss
  res/css/views/rooms/RoomListPanel/_RoomListPanel.pcss
  res/css/views/rooms/RoomListPanel/_RoomListSearch.pcss
  src/components/structures/LeftPanel.tsx
  src/components/views/rooms/RoomListPanel/RoomListHeaderView.tsx
  src/components/views/rooms/RoomListPanel/RoomListPanel.tsx
  src/components/views/rooms/RoomListPanel/RoomListSearch.tsx
  src/components/views/rooms/RoomListPanel/index.ts
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListHeaderView-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListPanel-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListSearch-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListHeaderView-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPanel-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListSearch-test.tsx.snap
Labels: T-Task

#29372 fix: /tmp/element-web-config may already exist preventing the container from booting up
  docker/docker-entrypoint.d/18-load-element-modules.sh
Labels: T-Defect, X-Release-Blocker, Z-Community-PR, backport staging

#29362 Rename `mx_RoomList` as `mx_LegacyRoomList`
  playwright/e2e/crypto/crypto.spec.ts
  playwright/e2e/invite/invite-dialog.spec.ts
  res/css/_components.pcss
  res/css/views/rooms/_LegacyRoomList.pcss
  src/components/structures/SpaceRoomView.tsx
  src/components/views/rooms/LegacyRoomList.tsx
Labels: T-Task

#29376 Enable babel plugins to enable js-sdk to use decorators
  babel.config.js
  package.json
  yarn.lock
Labels: T-Task

#29369 new room list: keep space name in one line in header
  res/css/views/rooms/RoomListPanel/_RoomListHeaderView.pcss
  src/components/views/rooms/RoomListPanel/RoomListHeaderView.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListHeaderView-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPanel-test.tsx.snap
Labels: T-Defect
