Repository element-hq/element-web, pull requests merged in 2025-04, with the labels that each got.

#29392 Fix scroll issues in memberlist
  src/components/views/rooms/MemberList/MemberListView.tsx
Labels: T-Defect

#29642 Remove duplicate jitsi link
  docs/SUMMARY.md
Labels: T-Defect

#29638 Update types for React 19 update
  src/NodeAnimator.tsx
Labels: T-Task

#29643 Fix truncated emoji label during emoji SAS
  res/css/views/verification/_VerificationShowSas.pcss
Labels: T-Defect

#29641 Update @vector-im/compound-web
  package.json
  test/unit-tests/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/unit-tests/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
  test/unit-tests/components/views/rooms/__snapshots__/PinnedEventTile-test.tsx.snap
  test/unit-tests/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
  yarn.lock
Labels: T-Task

#29650 Room List: Scroll to top of the list when active room is not in the list
  playwright/e2e/left-panel/room-list-panel/room-list-filter-sort.spec.ts
  src/components/views/rooms/RoomListPanel/RoomList.tsx
Labels: T-Enhancement

#29665 RoomListStore: Support specific sorting requirements for muted rooms
  playwright/e2e/left-panel/room-list-panel/room-list.spec.ts
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-hover-silent-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-selection-linux.png
  src/stores/room-list-v3/RoomListStoreV3.ts
  src/stores/room-list-v3/skip-list/sorters/RecencySorter.ts
  test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
  test/unit-tests/stores/room-list-v3/skip-list/RoomSkipList-test.ts
Labels: T-Enhancement

#29668 New Room List: Fix mentions filter matching rooms with any highlight
  src/stores/room-list-v3/skip-list/filters/MentionsFilter.ts
  test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
Labels: T-Defect

#29673 New room list: fix multiple visual issues
  package.json
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-activity-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-invited-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-mark-as-unread-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-mention-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-notification-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-selection-linux.png
  res/css/views/rooms/RoomListPanel/_RoomListItemView.pcss
  src/components/viewmodels/roomlist/RoomListItemViewModel.tsx
  src/components/views/rooms/RoomListPanel/RoomListHeaderView.tsx
  src/components/views/rooms/RoomListPanel/RoomListItemMenuView.tsx
  src/components/views/rooms/RoomListPanel/RoomListItemView.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListItemView-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomList-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListItemView-test.tsx.snap
  test/unit-tests/components/views/rooms/__snapshots__/NotificationDecoration-test.tsx.snap
  yarn.lock
Labels: T-Defect

#29672 RoomListViewModel: Reset primary and secondary filters on space change
  src/components/viewmodels/roomlist/useFilteredRooms.tsx
  test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
Labels: T-Enhancement

#29595 test e2e: use encryption tab instead of Security & Settings tab in crypto.spec.ts
  playwright/e2e/crypto/crypto.spec.ts
Labels: T-Task

#29570 Allow reporting a room when rejecting an invite.
  playwright/e2e/room/invites.spec.ts
  playwright/e2e/sliding-sync/sliding-sync.spec.ts
  playwright/snapshots/right-panel/right-panel.spec.ts/room-report-dialog-linux.png
  playwright/snapshots/room/invites.spec.ts/Invites-reject-dialog-linux.png
  playwright/snapshots/room/invites.spec.ts/Invites-room-view-linux.png
  res/css/views/dialogs/_ReportRoomDialog.pcss
  res/css/views/settings/tabs/user/_SecurityUserSettingsTab.pcss
  src/components/structures/MatrixChat.tsx
  src/components/structures/RoomView.tsx
  src/components/views/dialogs/DeclineAndBlockInviteDialog.tsx
  src/components/views/elements/LabelledToggleSwitch.tsx
  src/components/views/rooms/RoomPreviewBar.tsx
  src/components/views/rooms/RoomPreviewCard.tsx
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/test-utils/test-utils.ts
  test/unit-tests/components/structures/RoomView-test.tsx
  test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/unit-tests/components/views/dialogs/ConfirmRejectInviteDialog-test.tsx
  test/unit-tests/components/views/dialogs/__snapshots__/ConfirmRejectInviteDialog-test.tsx.snap
  test/unit-tests/components/views/dialogs/__snapshots__/ReportRoomDialog-test.tsx.snap
  test/unit-tests/components/views/location/__snapshots__/LocationShareMenu-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomPreviewBar-test.tsx
  test/unit-tests/components/views/rooms/__snapshots__/RoomPreviewBar-test.tsx.snap
  test/unit-tests/components/views/settings/__snapshots__/Notifications-test.tsx.snap
  test/unit-tests/components/views/settings/notifications/__snapshots__/Notifications2-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/user/SecurityUserSettingsTab-test.tsx
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/SecurityUserSettingsTab-test.tsx.snap
  test/unit-tests/components/views/spaces/__snapshots__/SpaceSettingsVisibilityTab-test.tsx.snap
Labels: T-Enhancement

#29691 Catch errors after syncing recovery
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/settings/encryption/ResetIdentityPanel.tsx
  src/components/views/settings/tabs/user/EncryptionUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/toasts/SetupEncryptionToast.ts
  test/unit-tests/components/views/settings/encryption/ResetIdentityPanel-test.tsx
  test/unit-tests/components/views/settings/encryption/__snapshots__/ResetIdentityPanel-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/user/EncryptionUserSettingsTab-test.tsx
  test/unit-tests/toasts/SetupEncryptionToast-test.tsx
Labels: T-Defect

#29695 Continue button is disabled when uploading a recovery key file
  src/components/views/dialogs/security/AccessSecretStorageDialog.tsx
Labels: T-Defect, Z-Community-PR

#28503 Don't crash the build when trying to docker-package from a shallow clone of a commit
  scripts/docker-package.sh
Labels: T-Task, Z-Community-PR

#29706 Ensure forceCloseAllModals also closes priority/static modals
  src/Modal.tsx
Labels: T-Defect

#29703 Revert deletion of hydrateSession
  src/Lifecycle.ts
  src/components/structures/auth/SoftLogout.tsx
  test/unit-tests/Lifecycle-test.ts
Labels: T-Defect, Z-Community-PR

#29713 Fix some webp images improperly marked as animated
  src/utils/Image.ts
  test/unit-tests/Image-test.ts
  test/unit-tests/images/static-logo-extended-file-format.webp
Labels: T-Defect, Z-Community-PR

#29719 test: fix flaky SetIdServer test
  test/unit-tests/components/views/settings/SetIdServer-test.tsx
Labels: T-Task

#29711 Fix getOidcCallbackUrl for Element Desktop
  src/vector/platform/ElectronPlatform.tsx
Labels: T-Defect

#29723 New room list: minor visual fixes
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/room-panel-empty-room-list-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/unread-primary-filters-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/unselected-primary-filters-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-panel.spec.ts/room-list-panel-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-more-options-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-selection-linux.png
  res/css/views/rooms/RoomListPanel/_RoomListHeaderView.pcss
  src/components/views/rooms/NotificationDecoration.tsx
  src/components/views/rooms/RoomListPanel/RoomListHeaderView.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListHeaderView-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPanel-test.tsx.snap
  test/unit-tests/components/views/rooms/__snapshots__/NotificationDecoration-test.tsx.snap
Labels: T-Defect

#29726 Fix custom theme support for short hex & rgba hex strings
  src/theme.ts
  test/unit-tests/theme-test.ts
Labels: T-Defect

#29693 New room list: video room and video call decoration
  playwright/e2e/left-panel/room-list-panel/room-list.spec.ts
  playwright/snapshots/left-panel/room-list-panel/room-list-panel.spec.ts/room-list-panel-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-activity-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-hover-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-mark-as-unread-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-mention-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-notification-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-more-options-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-public-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-silent-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-video-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-linux.png
  res/css/_components.pcss
  res/css/views/avatars/_RoomAvatarView.pcss
  res/img/element-icons/roomlist/room-avatar-view-icon-mask.svg
  res/img/element-icons/roomlist/room-avatar-view-presence-mask.svg
  src/components/viewmodels/avatars/RoomAvatarViewModel.tsx
  src/components/viewmodels/roomlist/RoomListHeaderViewModel.tsx
  src/components/viewmodels/roomlist/RoomListItemViewModel.tsx
  src/components/views/avatars/DecoratedRoomAvatar.tsx
  src/components/views/avatars/RoomAvatar.tsx
  src/components/views/avatars/RoomAvatarView.tsx
  src/components/views/rooms/NotificationDecoration.tsx
  src/components/views/rooms/RoomListPanel/RoomListItemView.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/viewmodels/avatars/RoomAvatarViewModel-test.tsx
  test/unit-tests/components/viewmodels/roomlist/RoomListHeaderViewModel-test.tsx
  test/unit-tests/components/views/avatars/RoomAvatarView-test.tsx
  test/unit-tests/components/views/avatars/__snapshots__/RoomAvatarView-test.tsx.snap
  test/unit-tests/components/views/rooms/NotificationDecoration-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListItemView-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomList-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListItemView-test.tsx.snap
  test/unit-tests/components/views/rooms/__snapshots__/NotificationDecoration-test.tsx.snap
Labels: T-Enhancement

#29735 Update to Twemoji 16
  package.json
  res/fonts/Twemoji_Mozilla/TwemojiMozilla-colr.woff2
  yarn.lock
Labels: T-Enhancement

#29737 New room list: fix public room icon visibility when filter change
  src/components/viewmodels/avatars/RoomAvatarViewModel.tsx
  test/unit-tests/components/viewmodels/avatars/RoomAvatarViewModel-test.tsx
Labels: T-Defect

#29724 print better errors in the search view instead of a blocking modal
  src/Searching.ts
  src/components/structures/RoomSearchView.tsx
  src/components/structures/RoomView.tsx
  src/components/views/rooms/RoomSearchAuxPanel.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/structures/RoomSearchView-test.tsx
Labels: T-Enhancement, Z-Community-PR

#29739 Fix flaky MatrixChat tests
  test/unit-tests/components/structures/MatrixChat-test.tsx
Labels: T-Task

#29707 Remove contribute.json
  contribute.json
  package.json
  webpack.config.js
Labels: T-Task

#29747 Fix unwanted form submit behaviour in memberlist
  src/components/views/rooms/MemberList/MemberListHeaderView.tsx
Labels: T-Defect

#29744 Refactor several unit tests to use SettingsStore directly.
  test/unit-tests/HtmlUtils-test.tsx
  test/unit-tests/components/structures/MatrixChat-test.tsx
  test/unit-tests/components/structures/TimelinePanel-test.tsx
  test/unit-tests/components/views/rooms/RoomHeader/RoomHeader-test.tsx
  test/unit-tests/components/views/rooms/RoomHeader/__snapshots__/RoomHeader-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/room/NotificationSettingsTab-test.tsx
  test/unit-tests/utils/notifications-test.ts
Labels: T-Task

#29748 Revert "Update to Twemoji 16"
  package.json
  res/fonts/Twemoji_Mozilla/TwemojiMozilla-colr.woff2
  yarn.lock
Labels: T-Task

#29743 Refactor RoomAvatar into a functional component.
  src/Avatar.ts
  src/components/views/avatars/RoomAvatar.tsx
  src/components/views/avatars/WithPresenceIndicator.tsx
  src/components/views/messages/RoomAvatarEvent.tsx
  src/components/views/room_settings/RoomProfileSettings.tsx
  src/hooks/room/useRoomIdName.ts
  test/unit-tests/components/views/avatars/DecoratedRoomAvatar-test.tsx
  test/unit-tests/components/views/avatars/RoomAvatar-test.tsx
Labels: T-Task

#29770 New room list: fix incorrect decoration
  src/components/viewmodels/avatars/RoomAvatarViewModel.tsx
  src/components/views/avatars/RoomAvatarView.tsx
  src/components/views/avatars/WithPresenceIndicator.tsx
  src/hooks/useCall.ts
  test/unit-tests/components/viewmodels/avatars/RoomAvatarViewModel-test.tsx
  test/unit-tests/components/views/avatars/RoomAvatarView-test.tsx
  test/unit-tests/components/views/avatars/__snapshots__/RoomAvatarView-test.tsx.snap
Labels: T-Defect

#29753 Fix invite test flake
  playwright/e2e/room/invites.spec.ts
  playwright/snapshots/room/invites.spec.ts/Invites-room-view-linux.png
Labels: T-Task

#29635 Remove virtual rooms
  src/@types/global.d.ts
  src/LegacyCallHandler.tsx
  src/Notifier.ts
  src/SlashCommands.tsx
  src/VoipUserMapper.ts
  src/call-types.ts
  src/components/structures/RoomView.tsx
  src/components/structures/TimelinePanel.tsx
  src/createRoom.ts
  src/i18n/strings/en_EN.json
  src/stores/room-list/RoomListStore.ts
  src/stores/room-list/filters/VisibilityProvider.ts
  test/unit-tests/LegacyCallHandler-test.ts
  test/unit-tests/SlashCommands-test.tsx
  test/unit-tests/components/structures/RoomView-test.tsx
  test/unit-tests/components/structures/TimelinePanel-test.tsx
  test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/unit-tests/stores/room-list/filters/VisibilityProvider-test.ts
Labels: T-Task

#29751 Update team members in triage-assigned.yml
  .github/workflows/triage-assigned.yml
Labels: T-Task

#29773 New room list: new visual for invitation
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-invited-linux.png
  res/css/views/rooms/RoomListPanel/_RoomListItemView.pcss
  src/components/viewmodels/roomlist/RoomListItemViewModel.tsx
  src/components/views/rooms/NotificationDecoration.tsx
  test/unit-tests/components/viewmodels/roomlist/RoomListItemViewModel-test.tsx
  test/unit-tests/components/views/rooms/__snapshots__/NotificationDecoration-test.tsx.snap
Labels: T-Enhancement

#29752 New room list: avoid extra render for room list item
  src/components/viewmodels/roomlist/RoomListItemViewModel.tsx
  src/components/views/rooms/NotificationDecoration.tsx
  src/components/views/rooms/RoomListPanel/RoomListItemView.tsx
  src/stores/notifications/RoomNotificationState.ts
  test/unit-tests/components/viewmodels/roomlist/RoomListItemViewModel-test.tsx
  test/unit-tests/components/views/rooms/NotificationDecoration-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListItemView-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListItemView-test.tsx.snap
  test/unit-tests/stores/notifications/RoomNotificationState-test.ts
Labels: T-Task

#28926 feat: warn self change on roles settings
  playwright/e2e/settings/roles-permissions-room-settings-tab.spec.ts
  src/components/views/settings/PowerLevelSelector.tsx
  test/unit-tests/components/views/settings/PowerLevelSelector-test.tsx
  test/unit-tests/components/views/settings/tabs/room/RolesRoomSettingsTab-test.tsx
Labels: T-Enhancement, Z-Community-PR

#29781 New Room List: Prevent potential scroll jump/flicker when switching spaces
  src/components/viewmodels/roomlist/useStickyRoomList.tsx
  src/stores/spaces/SpaceStore.ts
  test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
Labels: T-Defect

#29710 MVVM RoomSummaryCard Topic
  src/components/viewmodels/right_panel/RoomSummaryCardTopicViewModel.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  test/unit-tests/components/viewmodels/right_panel/RoomSummaryCardTopicViewModel-test.tsx
Labels: T-Enhancement, Z-Community-PR

#29783 New room list: add partial keyboard shortcuts support
  playwright/e2e/left-panel/room-list-panel/room-list.spec.ts
  src/components/viewmodels/roomlist/RoomListViewModel.tsx
  src/components/viewmodels/roomlist/useRoomListNavigation.ts
  test/unit-tests/components/viewmodels/roomlist/useRoomListNavigation-test.ts
Labels: T-Enhancement

#29582 Global configuration flag for media previews
  playwright/e2e/timeline/media-preview-settings.spec.ts
  playwright/snapshots/settings/preferences-user-settings-tab.spec.ts/Preferences-user-settings-tab-should-be-rendered-properly-1-linux.png
  playwright/snapshots/timeline/media-preview-settings.spec.ts/invite-no-avatar-linux.png
  playwright/snapshots/timeline/media-preview-settings.spec.ts/invite-room-tree-no-avatar-linux.png
  playwright/snapshots/timeline/media-preview-settings.spec.ts/invite-room-tree-with-avatar-linux.png
  playwright/snapshots/timeline/media-preview-settings.spec.ts/invite-with-avatar-linux.png
  res/css/_components.pcss
  res/css/views/settings/tabs/user/_MediaPreviewAccountSettings.pcss
  src/@types/matrix-js-sdk.d.ts
  src/@types/media_preview.ts
  src/HtmlUtils.tsx
  src/Linkify.tsx
  src/components/views/avatars/RoomAvatar.tsx
  src/components/views/messages/EventContentBody.tsx
  src/components/views/messages/HideActionButton.tsx
  src/components/views/messages/MImageBody.tsx
  src/components/views/messages/MImageReplyBody.tsx
  src/components/views/messages/MStickerBody.tsx
  src/components/views/messages/MVideoBody.tsx
  src/components/views/rooms/LinkPreviewGroup.tsx
  src/components/views/rooms/LinkPreviewWidget.tsx
  src/components/views/settings/tabs/room/GeneralRoomSettingsTab.tsx
  src/components/views/settings/tabs/user/MediaPreviewAccountSettings.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/hooks/useMediaVisible.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/SettingsStore.ts
  src/settings/controllers/MatrixClientBackedController.ts
  src/settings/controllers/MediaPreviewConfigController.ts
  src/settings/handlers/AccountSettingsHandler.ts
  src/settings/handlers/RoomAccountSettingsHandler.ts
  test/unit-tests/HtmlUtils-test.tsx
  test/unit-tests/__snapshots__/HtmlUtils-test.tsx.snap
  test/unit-tests/components/views/avatars/RoomAvatar-test.tsx
  test/unit-tests/components/views/messages/HideActionButton-test.tsx
  test/unit-tests/components/views/messages/MImageBody-test.tsx
  test/unit-tests/components/views/messages/MStickerBody-test.tsx
  test/unit-tests/components/views/messages/MVideoBody-test.tsx
  test/unit-tests/components/views/rooms/RoomPreviewCard-test.tsx
  test/unit-tests/components/views/settings/tabs/user/MediaPreviewAccountSettingsTab-test.tsx
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/PreferencesUserSettingsTab-test.tsx.snap
  test/unit-tests/hooks/useMediaVisible-test.tsx
  test/unit-tests/settings/controllers/MediaPreviewConfigController-test.ts
Labels: T-Enhancement

#29803 Replace usage of `forwardRef` with React 19 ref prop
  .eslintrc.js
  src/@types/react.d.ts
  src/accessibility/Toolbar.tsx
  src/accessibility/context_menu/ContextMenuButton.tsx
  src/accessibility/context_menu/ContextMenuTooltipButton.tsx
  src/autocomplete/Components.tsx
  src/autocomplete/UserProvider.tsx
  src/components/structures/MatrixClientContextProvider.tsx
  src/components/structures/RoomSearchView.tsx
  src/components/structures/auth/LoginSplashView.tsx
  src/components/views/avatars/BaseAvatar.tsx
  src/components/views/avatars/MemberAvatar.tsx
  src/components/views/elements/AccessibleButton.tsx
  src/components/views/location/Marker.tsx
  src/components/views/messages/CallEvent.tsx
  src/components/views/messages/DecryptionFailureBody.tsx
  src/components/views/messages/EncryptionEvent.tsx
  src/components/views/messages/EventContentBody.tsx
  src/components/views/messages/EventTileBubble.tsx
  src/components/views/messages/HiddenBody.tsx
  src/components/views/messages/IBodyProps.ts
  src/components/views/messages/MBeaconBody.tsx
  src/components/views/messages/MPollEndBody.tsx
  src/components/views/messages/RedactedBody.tsx
  src/components/views/messages/UnknownBody.tsx
  src/components/views/right_panel/BaseCard.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/MemberList/MemberListView.tsx
  src/components/views/rooms/MemberList/tiles/common/E2EIconView.tsx
  src/components/views/rooms/MemberList/tiles/common/PresenceIconView.tsx
  src/components/views/rooms/NotificationBadge/StatelessNotificationBadge.tsx
  src/components/views/rooms/RoomListPanel/RoomListItemMenuView.tsx
  src/components/views/rooms/wysiwyg_composer/EditWysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/SendWysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/components/Editor.tsx
  src/components/views/rooms/wysiwyg_composer/components/WysiwygAutocomplete.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/useIsExpanded.ts
  src/components/views/rooms/wysiwyg_composer/hooks/useWysiwygEditActionHandler.ts
  src/components/views/rooms/wysiwyg_composer/hooks/useWysiwygSendActionHandler.ts
  src/components/views/settings/devices/DeviceExpandDetailsButton.tsx
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentreButton.tsx
  src/components/views/voip/LegacyCallView/LegacyCallViewButtons.tsx
  src/contexts/MatrixClientContext.tsx
  src/events/EventTileFactory.tsx
  test/unit-tests/components/views/rooms/memberlist/MemberListHeaderView-test.tsx
  test/unit-tests/components/views/rooms/memberlist/MemberListView-test.tsx
Labels: T-Task

#29784 Add message preview support to the new room list
  package.json
  playwright/e2e/left-panel/room-list-panel/room-list.spec.ts
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/room-panel-empty-room-list-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-header.spec.ts/room-list-header-space-menu-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-panel.spec.ts/room-list-panel-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-message-preview-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-more-options-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-selection-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-scrolled-linux.png
  res/css/_components.pcss
  res/css/views/rooms/RoomListPanel/_RoomListItemView.pcss
  res/css/views/rooms/RoomListPanel/_RoomListSecondaryFilters.pcss
  src/components/viewmodels/roomlist/RoomListItemViewModel.tsx
  src/components/viewmodels/roomlist/useMessagePreviewToggle.tsx
  src/components/views/rooms/RoomListPanel/RoomListItemView.tsx
  src/components/views/rooms/RoomListPanel/RoomListOptionsMenu.tsx
  src/components/views/rooms/RoomListPanel/RoomListSecondaryFilters.tsx
  src/components/views/rooms/RoomListPanel/RoomListView.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/viewmodels/roomlist/RoomListItemViewModel-test.tsx
  test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListItemView-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListSecondaryFilters-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomList-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListItemView-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPanel-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListSecondaryFilters-test.tsx.snap
  yarn.lock
Labels: T-Enhancement

#29811 Fix the buttons not being displayed with long preview text
  res/css/views/rooms/RoomListPanel/_RoomListItemView.pcss
Labels: T-Defect

#29812 Fix another invite test flake
  playwright/e2e/timeline/media-preview-settings.spec.ts
  playwright/snapshots/timeline/media-preview-settings.spec.ts/invite-no-avatar-linux.png
  playwright/snapshots/timeline/media-preview-settings.spec.ts/invite-with-avatar-linux.png
Labels: T-Task

#29804 RoomListStore: Remove invite rooms on decline
  src/stores/room-list-v3/RoomListStoreV3.ts
  test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
Labels: T-Defect

#29826 Fix incorrect display of the user info display name
  playwright/e2e/right-panel/right-panel.spec.ts
  playwright/snapshots/right-panel/right-panel.spec.ts/with-long-name-linux.png
  playwright/snapshots/user-view/user-view.spec.ts/user-info-linux.png
  res/css/views/right_panel/_UserInfo.pcss
Labels: T-Defect

#29211 spell out that EW does *not* work on mobile.
  src/vector/mobile_guide/index.html
Labels: T-Enhancement

#29817 Move rich topics out of labs / stabilise MSC3765
  docs/labs.md
  src/HtmlUtils.tsx
  test/unit-tests/HtmlUtils-test.tsx
Labels: T-Enhancement, Z-Community-PR

#29203 Fix battery drain from Web Audio
  src/audio/BackgroundAudio.ts
  src/audio/compat.ts
Labels: T-Enhancement, Z-Community-PR

#29851 Un-gitignore `modules.ts`
  .gitignore
Labels: T-Task

#29818 Add secondary filters to the new room list
  playwright/e2e/left-panel/room-list-panel/room-list-filter-sort.spec.ts
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/filter-menu-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/room-panel-empty-room-list-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-panel.spec.ts/room-list-panel-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-more-options-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-selection-linux.png
  src/components/views/rooms/RoomListPanel/RoomListFilterMenu.tsx
  src/components/views/rooms/RoomListPanel/RoomListSecondaryFilters.tsx
  src/components/views/rooms/RoomListPanel/textForFilter.ts
  src/i18n/strings/en_EN.json
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListFilterMenu-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListFilterMenu-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPanel-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListSecondaryFilters-test.tsx.snap
Labels: T-Enhancement

#29701 Update identity reset UI (Make consistent with EX)
  playwright/e2e/crypto/dehydration.spec.ts
  playwright/e2e/login/login-consent.spec.ts
  playwright/e2e/settings/encryption-user-tab/encryption-tab.spec.ts
  src/components/structures/auth/CompleteSecurity.tsx
  src/components/structures/auth/SetupEncryptionBody.tsx
  src/components/views/dialogs/ResetIdentityDialog.tsx
  src/components/views/settings/encryption/ResetIdentityBody.tsx
  src/components/views/settings/encryption/ResetIdentityPanel.tsx
  src/components/views/settings/tabs/user/EncryptionUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/stores/SetupEncryptionStore.ts
  test/components/views/dialogs/security/ResetIdentityDialog-test.tsx
  test/components/views/dialogs/security/SetupEncryptionDialog-test.tsx
  test/unit-tests/components/structures/auth/CompleteSecurity-test.tsx
  test/unit-tests/components/views/settings/encryption/ResetIdentityPanel-test.tsx
  test/unit-tests/stores/SetupEncryptionStore-test.ts
Labels: T-Enhancement

#29850 Allow jumping to message search from spotlight
  res/css/views/dialogs/_SpotlightDialog.pcss
  res/themes/light-high-contrast/css/_light-high-contrast.pcss
  src/components/structures/RightPanel.tsx
  src/components/structures/RoomView.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/dispatcher/actions.ts
  src/dispatcher/payloads/FocusMessageSearchPayload.ts
  src/hooks/useTransition.ts
  src/i18n/strings/en_EN.json
  test/test-utils/test-utils.ts
  test/unit-tests/components/structures/RoomView-test.tsx
  test/unit-tests/components/views/dialogs/SpotlightDialog-test.tsx
  test/unit-tests/components/views/right_panel/RoomSummaryCard-test.tsx
Labels: T-Defect

#29852 Modal: remove support for `onFinished` callback
  src/LegacyCallHandler.tsx
  src/Lifecycle.ts
  src/Modal.tsx
  src/Registration.tsx
  src/async-components/views/dialogs/security/NewRecoveryMethodDialog.tsx
  src/components/structures/MatrixChat.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/structures/auth/SetupEncryptionBody.tsx
  src/components/structures/auth/SoftLogout.tsx
  src/components/views/auth/RegistrationForm.tsx
  src/components/views/context_menus/DeveloperToolsOption.tsx
  src/components/views/context_menus/WidgetContextMenu.tsx
  src/components/views/dialogs/AnalyticsLearnMoreDialog.tsx
  src/components/views/dialogs/ConfirmRedactDialog.tsx
  src/components/views/dialogs/SessionRestoreErrorDialog.tsx
  src/components/views/dialogs/SetEmailDialog.tsx
  src/components/views/directory/NetworkDropdown.tsx
  src/components/views/elements/PollCreateDialog.tsx
  src/components/views/elements/ServerPicker.tsx
  src/components/views/messages/TextualBody.tsx
  src/components/views/settings/EventIndexPanel.tsx
  src/components/views/settings/devices/deleteDevices.tsx
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  src/components/views/settings/tabs/user/AccountUserSettingsTab.tsx
  src/components/views/settings/tabs/user/EncryptionUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/components/views/toasts/VerificationRequestToast.tsx
  src/slash-commands/utils.ts
  src/stores/ModalWidgetStore.ts
  src/stores/widgets/StopGapWidgetDriver.ts
  src/toasts/AnalyticsToast.tsx
  src/toasts/UpdateToast.tsx
  src/utils/DialogOpener.ts
  src/utils/leave-behaviour.ts
  src/utils/space.tsx
  test/unit-tests/Modal-test.ts
  test/unit-tests/components/views/settings/devices/deleteDevices-test.tsx
  test/unit-tests/components/views/settings/tabs/user/AccountUserSettingsTab-test.tsx
  test/unit-tests/components/views/settings/tabs/user/EncryptionUserSettingsTab-test.tsx
  test/unit-tests/components/views/settings/tabs/user/SessionManagerTab-test.tsx
Labels: T-Task

#29855 Support error code for email / phone adding unsupported (MSC4178)
  src/AddThreepid.ts
  src/i18n/strings/en_EN.json
Labels: T-Enhancement
