Repository element-hq/element-web, pull requests merged in 2025-07, with the labels that each got.

#30234 Fix link to e2e docs
  developer_guide.md
Labels: T-Task, A-Documentation, Z-Community-PR

#30258 Rename the mobile_guide_app_variant config values to be clearer.
  docs/config.md
  playwright/snapshots/mobile-guide/mobile-guide.spec.ts/mobile-guide-element-classic-linux.png
  playwright/snapshots/mobile-guide/mobile-guide.spec.ts/mobile-guide-element-linux.png
  playwright/snapshots/mobile-guide/mobile-guide.spec.ts/mobile-guide-element-pro-linux.png
  src/IConfigOptions.ts
  src/vector/mobile_guide/index.html
  src/vector/mobile_guide/index.ts
  src/vector/mobile_guide/mobile-apps.ts
Labels: T-Task

#30254 Fix e2e flakes in new room list
  playwright/e2e/left-panel/room-list-panel/room-list-filter-sort.spec.ts
  playwright/e2e/left-panel/room-list-panel/room-list.spec.ts
Labels: T-Task

#30302 Flaky test issue auto-closer: only close playwright test issues
  .github/workflows/triage-stale.yml
Labels: T-Task

#30312 Fix: Prevent page refresh on Enter key in right panel member search
  src/components/views/rooms/MemberList/MemberListView.tsx
  test/unit-tests/components/views/rooms/memberlist/MemberListView-test.tsx
Labels: T-Defect, Z-Community-PR

#30329 Fix flaky tests in `playwright/e2e/left-panel/room-list-panel/room-list.spec.ts`
  playwright/e2e/left-panel/room-list-panel/room-list.spec.ts
  playwright/pages/ElementAppPage.ts
Labels: T-Task

#30268 Add i18n to storybook
  .github/workflows/shared-component-visual-tests.yaml
  .storybook/languageAddon.tsx
  .storybook/main.ts
  .storybook/manager.js
  .storybook/preview.tsx
  package.json
  src/accessibility/KeyboardShortcuts.ts
  src/languageHandler.tsx
  src/settings/Settings.tsx
  src/shared-components/i18n.tsx
  yarn.lock
Labels: T-Task

#30328 Add a background color to left panel for macos titlebar in element desktop
  res/css/structures/_LeftPanel.pcss
Labels: T-Defect

#30323 Add quote functionality to MessageContextMenu (#29893)
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/rooms/EventTile.tsx
  test/unit-tests/components/views/context_menus/MessageContextMenu-test.tsx
Labels: T-Enhancement, Z-Community-PR

#30330 Enhancement: Save image on CTRL+S
  AUTHORS.rst
  src/accessibility/KeyboardShortcuts.ts
  src/components/views/elements/ImageView.tsx
  src/components/views/messages/DownloadActionButton.tsx
  src/hooks/useDownloadMedia.ts
  src/i18n/strings/en_EN.json
  test/unit-tests/components/views/elements/ImageView-test.tsx
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/KeyboardUserSettingsTab-test.tsx.snap
Labels: T-Enhancement, Z-Community-PR

#30315 Support rendering notification badges on platforms that do their own icon overlays
  src/@types/global.d.ts
  src/BasePlatform.ts
  src/favicon.ts
  src/vector/platform/ElectronPlatform.tsx
  test/unit-tests/vector/platform/ElectronPlatform-test.ts
Labels: T-Enhancement

#30338 Disable flaky jest test: `<MatrixChat /> › Multi-tab lockout › waits for other tab to stop during startup`
  test/unit-tests/components/structures/MatrixChat-test.tsx
Labels: T-Task

#30332 Force ED titlebar color for new room list
  res/css/structures/_LeftPanel.pcss
Labels: T-Defect

#30392 Storybook: add tooltip provider and sort stories
  .storybook/preview.tsx
Labels: T-Task

#30396 Update playwright-common package
  package.json
  yarn.lock
Labels: T-Task

#30397 Allow for unknown event shield reasons
  src/components/views/rooms/EventTile.tsx
Labels: T-Task

#30402 fix: replace hardcoded string in poll history dialog
  src/components/views/polls/pollHistory/PollHistoryList.tsx
Labels: T-Defect

#30403 Support `EventShieldReason.MISMATCHED_SENDER`
  src/components/views/rooms/EventTile.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/views/rooms/EventTile-test.tsx
Labels: T-Enhancement

#30408 Fix e2e shield being invisible in white mode for encrypted room
  playwright/e2e/crypto/crypto.spec.ts
  playwright/snapshots/crypto/crypto.spec.ts/composer-e2e-icon-normal-linux.png
  res/css/views/rooms/_E2EIcon.pcss
Labels: T-Defect, X-Regression, backport staging

#30413 MatrixChat test robustness fixes
  test/unit-tests/components/structures/MatrixChat-test.tsx
Labels: T-Task

#30410 Re-enable matrixchat test
  test/unit-tests/components/structures/MatrixChat-test.tsx
Labels: T-Task

#30429 Hacky fix to the MatrixChat flakiness
  test/unit-tests/components/structures/MatrixChat-test.tsx
Labels: T-Task

#30446 Put the 'decrypting' tooltip back
  src/components/views/messages/DownloadActionButton.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/views/messages/DownloadActionButton-test.tsx
Labels: T-Defect

#29869 Implement the member list with virtuoso
  package.json
  playwright/e2e/lazy-loading/lazy-loading.spec.ts
  playwright/e2e/share-dialog/share-dialog.spec.ts
  playwright/snapshots/right-panel/memberlist.spec.ts/with-four-members-linux.png
  src/components/utils/ListView.tsx
  src/components/viewmodels/memberlist/MemberListViewModel.tsx
  src/components/viewmodels/memberlist/tiles/MemberTileViewModel.tsx
  src/components/views/rooms/MemberList/MemberListHeaderView.tsx
  src/components/views/rooms/MemberList/MemberListView.tsx
  src/components/views/rooms/MemberList/tiles/RoomMemberTileView.tsx
  src/components/views/rooms/MemberList/tiles/ThreePidInviteTileView.tsx
  src/components/views/rooms/MemberList/tiles/common/MemberTileView.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/views/rooms/memberlist/MemberTileView-test.tsx
  test/unit-tests/components/views/rooms/memberlist/__snapshots__/MemberTileView-test.tsx.snap
  test/unit-tests/components/views/rooms/memberlist/common.tsx
  test/unit-tests/components/views/utils/ListView-test.tsx
  yarn.lock
Labels: T-Enhancement
