Repository element-hq/element-web, pull requests merged in 2025-05, with the labels that each got.

#29854 Make OIDC identity reset consistent with EX
  src/CreateCrossSigning.ts
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  src/components/views/dialogs/InteractiveAuthDialog.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/views/auth/InteractiveAuthEntryComponents-test.tsx
  test/unit-tests/components/views/auth/__snapshots__/InteractiveAuthEntryComponents-test.tsx.snap
Labels: T-Enhancement

#29725 Add loading state to the new room list view
  res/css/_components.pcss
  res/css/views/rooms/RoomListPanel/_RoomListSkeleton.pcss
  res/css/views/rooms/_RoomSublist.pcss
  res/img/element-icons/roomlist/room-list-item-skeleton.svg
  src/components/viewmodels/roomlist/RoomListViewModel.tsx
  src/components/viewmodels/roomlist/useFilteredRooms.tsx
  src/components/views/rooms/RoomListPanel/RoomListView.tsx
  src/stores/room-list-v3/RoomListStoreV3.ts
  test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/EmptyRoomList-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomList-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListFilterMenu-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListPrimaryFilters-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListSecondaryFilters-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListView-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPanel-test.tsx.snap
  test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
Labels: T-Enhancement

#29873 Respect UIFeature.Voip
  src/hooks/room/useRoomCall.tsx
  test/unit-tests/components/views/rooms/RoomHeader/RoomHeader-test.tsx
  test/unit-tests/components/views/rooms/RoomHeader/__snapshots__/RoomHeader-test.tsx.snap
Labels: T-Defect

#29887 Tidy SetupEncryptionToast tests
  test/unit-tests/toasts/SetupEncryptionToast-test.tsx
Labels: T-Task

#29885 Remove lag in search field
  src/components/views/right_panel/RoomSummaryCard.tsx
  test/unit-tests/components/views/right_panel/RoomSummaryCard-test.tsx
Labels: T-Defect

#29881 New Room List: Prevent old tombstoned rooms from appearing in the list
  playwright/e2e/left-panel/room-list-panel/room-list-filter-sort.spec.ts
  src/stores/room-list-v3/RoomListStoreV3.ts
  src/stores/room-list-v3/skip-list/RoomSkipList.ts
  test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
  test/unit-tests/stores/room-list-v3/skip-list/RoomSkipList-test.ts
Labels: T-Defect

#29805 New room list: add keyboard navigation support
  playwright/e2e/left-panel/room-list-panel/room-list.spec.ts
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-selection-linux.png
  res/css/views/rooms/RoomListPanel/_RoomListItemView.pcss
  src/components/views/rooms/RoomListPanel/RoomList.tsx
  src/components/views/rooms/RoomListPanel/RoomListItemView.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomList-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListItemView-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomList-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListItemView-test.tsx.snap
Labels: T-Enhancement

#29886 Cache the key backup status whether enabled or not
  src/DeviceListener.ts
  test/unit-tests/DeviceListener-test.ts
Labels: T-Task

#29892 Remove release announcement on thread activity centre
  playwright/e2e/release-announcement/releaseAnnouncement.spec.ts
  playwright/e2e/spaces/threads-activity-centre/threadsActivityCentre.spec.ts
  playwright/snapshots/release-announcement/releaseAnnouncement.spec.ts/release-announcement-All-new-pinned-messages-linux.png
  playwright/snapshots/release-announcement/releaseAnnouncement.spec.ts/release-announcement-Threads-Activity-Centre-linux.png
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentre.tsx
  src/i18n/strings/en_EN.json
  src/stores/ReleaseAnnouncementStore.ts
  test/unit-tests/components/structures/ReleaseAnnouncement-test.tsx
  test/unit-tests/components/views/right_panel/RoomSummaryCard-test.tsx
  test/unit-tests/components/views/spaces/__snapshots__/SpacePanel-test.tsx.snap
  test/unit-tests/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
  test/unit-tests/stores/ReleaseAnnouncementStore-test.tsx
Labels: T-Task

#29895 Add error toast when service worker registration fails
  src/BasePlatform.ts
  src/i18n/strings/en_EN.json
  src/vector/platform/WebPlatform.ts
  test/unit-tests/vector/platform/WebPlatform-test.ts
Labels: T-Defect

#29926 Automate adding crypto team issues to their project based on label
  .github/workflows/triage-labelled.yml
Labels: T-Task

#29925 New room list: fix outdated message preview when space or filter change
  src/components/viewmodels/roomlist/RoomListItemViewModel.tsx
  test/unit-tests/components/viewmodels/roomlist/RoomListItemViewModel-test.tsx
Labels: T-Defect

#29929 Fix go home shortcut on macos and change toggle action events shortcut
  src/accessibility/KeyboardShortcuts.ts
Labels: T-Defect

#29927 Fix flaky jest tests
  src/Lifecycle.ts
  src/utils/StorageManager.ts
  test/unit-tests/components/structures/MatrixChat-test.tsx
Labels: T-Task

#29010 Remove legacy Safari/Firefox/IE compatibility aids
  src/@types/global.d.ts
  src/audio/Playback.ts
  src/audio/compat.ts
  src/components/views/elements/LanguageDropdown.tsx
  src/components/views/elements/SpellCheckLanguagesDropdown.tsx
  src/components/views/voip/LegacyCallView.tsx
  src/languageHandler.tsx
  test/unit-tests/audio/Playback-test.ts
  test/unit-tests/audio/compat-test.ts
  test/unit-tests/components/views/audio_messages/RecordingPlayback-test.tsx
  test/unit-tests/components/views/voip/LegacyCallView-test.tsx
  test/unit-tests/languageHandler-test.tsx
Labels: T-Task

#29934 Element Module API v1.0 support
  package.json
  playwright/e2e/modules/loader.spec.ts
  playwright/sample-files/example-module.js
  src/languageHandler.tsx
  src/modules/Api.ts
  src/modules/ConfigApi.ts
  src/modules/I18nApi.ts
  src/vector/index.ts
  src/vector/init.tsx
  yarn.lock
Labels: T-Task

#29959 Guard against counterpart.translate returning non-string values
  src/languageHandler.tsx
Labels: T-Task

#29960 Update @types/react patch
  patches/@types+react+19.1.4.patch
Labels: T-Task

#29963 Remove old filter test
  test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
Labels: T-Defect

#29778 Don't use the minimised width(68px) on the new room list
  playwright/e2e/left-panel/room-list-panel/room-list-panel.spec.ts
  playwright/snapshots/left-panel/room-list-panel/room-list-panel.spec.ts/room-list-panel-smallscreen-linux.png
  res/css/structures/_LeftPanel.pcss
  res/css/views/rooms/RoomListPanel/_RoomListSearch.pcss
  src/components/structures/LeftPanel.tsx
  src/components/structures/LoggedInView.tsx
  src/components/views/rooms/RoomListPanel/RoomListSearch.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPanel-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListSearch-test.tsx.snap
Labels: T-Enhancement

#29273 Fix extensions panel style
  playwright/e2e/right-panel/right-panel.spec.ts
  playwright/snapshots/right-panel/right-panel.spec.ts/with-extensions-linux.png
  res/css/views/right_panel/_ExtensionsCard.pcss
  src/components/structures/RightPanel.tsx
  test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/unit-tests/components/views/elements/__snapshots__/AppTile-test.tsx.snap
Labels: T-Defect

#29951 Add room list sorting
  package.json
  playwright/e2e/left-panel/room-list-panel/room-list-filter-sort.spec.ts
  src/components/views/rooms/RoomListPanel/RoomListOptionsMenu.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListOptionsMenu-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListOptionsMenu-test.tsx.snap
  yarn.lock
Labels: T-Enhancement

#29964 Fix leaky CSS adding `!` to all H1 elements
  res/welcome.html
Labels: T-Defect

#29933 RLS: Remove forgotten room from skiplist
  src/components/structures/MatrixChat.tsx
  src/dispatcher/actions.ts
  src/dispatcher/payloads/AfterForgetRoomPayload.ts
  src/stores/room-list-v3/RoomListStoreV3.ts
  test/unit-tests/components/structures/MatrixChat-test.tsx
  test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
Labels: T-Enhancement

#29967 Fix broken link in README
  README.md
Labels: T-Task

#29968 Remove the Apple site association for Element X PR
  res/apple-app-site-association
Labels: T-Task

#29674 Mvvm RoomSummaryCard
  src/components/structures/RightPanel.tsx
  src/components/viewmodels/right_panel/RoomSummaryCardViewModel.tsx
  src/components/views/right_panel/RoomSummaryCardView.tsx
  test/unit-tests/components/viewmodels/right_panel/RoomSummaryCardViewModel-test.tsx
  test/unit-tests/components/views/right_panel/RoomSummaryCard-test.tsx
  test/unit-tests/components/views/right_panel/RoomSummaryCardView-test.tsx
  test/unit-tests/components/views/right_panel/__snapshots__/RoomSummaryCardView-test.tsx.snap
Labels: T-Task, Z-Community-PR

#29974 RoomListStoreV3: Only add new rooms that pass `VisibilityProvider` check
  src/stores/room-list-v3/RoomListStoreV3.ts
  test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
Labels: T-Defect

#29983 New room list: move sort menu in room list header
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/room-panel-empty-room-list-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-header.spec.ts/room-list-header-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-header.spec.ts/room-list-space-header-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-panel.spec.ts/room-list-panel-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-panel.spec.ts/room-list-panel-smallscreen-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-more-options-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-selection-linux.png
  res/css/views/rooms/RoomListPanel/_RoomListSecondaryFilters.pcss
  src/components/viewmodels/roomlist/RoomListHeaderViewModel.tsx
  src/components/viewmodels/roomlist/RoomListViewModel.tsx
  src/components/views/rooms/RoomListPanel/RoomListHeaderView.tsx
  src/components/views/rooms/RoomListPanel/RoomListOptionsMenu.tsx
  src/components/views/rooms/RoomListPanel/RoomListSecondaryFilters.tsx
  test/unit-tests/components/viewmodels/roomlist/RoomListHeaderViewModel-test.tsx
  test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/EmptyRoomList-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomList-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListFilterMenu-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListHeaderView-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListOptionsMenu-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListPrimaryFilters-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListSecondaryFilters-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListView-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListHeaderView-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListOptionsMenu-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPanel-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListSecondaryFilters-test.tsx.snap
Labels: T-Enhancement

#29899 Downstream test element-modules in merge queue
  .github/workflows/end-to-end-tests.yaml
Labels: T-Task

#29814 Support build-time specified protocol scheme for oidc callback
  src/@types/global.d.ts
  src/vector/platform/ElectronPlatform.tsx
  test/unit-tests/vector/platform/ElectronPlatform-test.ts
Labels: T-Task

#29997 Clean up some unused code related to calls
  src/models/Call.ts
  test/unit-tests/models/Call-test.ts
Labels: T-Task

#29819 EW: Modernize the recovery key input modal
  playwright/e2e/crypto/device-verification.spec.ts
  playwright/e2e/crypto/utils.ts
  res/css/_common.pcss
  res/css/views/dialogs/security/_AccessSecretStorageDialog.pcss
  src/components/views/dialogs/security/AccessSecretStorageDialog.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/views/dialogs/AccessSecretStorageDialog-test.tsx
Labels: T-Enhancement

#29874 /share?msg=foo endpoint using forward message dialog
  playwright/e2e/share-dialog/share-by-url.spec.ts
  src/components/structures/MatrixChat.tsx
  src/dispatcher/actions.ts
  src/dispatcher/payloads/SharePayload.ts
  test/unit-tests/components/structures/MatrixChat-test.tsx
Labels: T-Enhancement

#29721 New room list: remove color gradient in space panel
  playwright/snapshots/left-panel/room-list-panel/room-list-panel.spec.ts/room-list-panel-smallscreen-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-more-options-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-selection-linux.png
  res/css/structures/_SpacePanel.pcss
  src/components/structures/LoggedInView.tsx
  src/components/views/spaces/SpacePanel.tsx
Labels: T-Enhancement

#30052 Close call options popup menu when option has been selected
  src/components/views/rooms/RoomHeader/RoomHeader.tsx
Labels: T-Defect, backport staging
