Repository element-hq/element-web, pull requests merged in 2025-08, with the labels that each got.

#30455 Fix: Clicking on an item in the member list causes it to scroll to the top rather than show the profile view
  playwright/e2e/right-panel/memberlist.spec.ts
  src/components/utils/ListView.tsx
  src/components/views/rooms/MemberList/MemberListView.tsx
  src/components/views/rooms/MemberList/tiles/RoomMemberTileView.tsx
  src/components/views/rooms/MemberList/tiles/ThreePidInviteTileView.tsx
  src/components/views/rooms/MemberList/tiles/common/MemberTileView.tsx
  test/unit-tests/components/views/rooms/memberlist/MemberTileView-test.tsx
  test/unit-tests/components/views/utils/ListView-test.tsx
Labels: T-Defect

#30479 Fix race condition in flaky reply chain test
  playwright/e2e/audio-player/audio-player.spec.ts
Labels: T-Task

#30471 Hide recovery key when prompting for verification
  playwright/e2e/crypto/device-verification.spec.ts
  playwright/e2e/crypto/utils.ts
  res/css/views/dialogs/security/_AccessSecretStorageDialog.pcss
  src/components/views/dialogs/security/AccessSecretStorageDialog.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/views/dialogs/AccessSecretStorageDialog-test.tsx
Labels: T-Task

#30480 Move `clock` into shared components
  playwright/shared-component-snapshots/audio-clock--default-linux.png
  playwright/shared-component-snapshots/audio-clock--lot-of-seconds-linux.png
  src/DateUtils.ts
  src/components/views/audio_messages/DurationClock.tsx
  src/components/views/audio_messages/LiveRecordingClock.tsx
  src/components/views/audio_messages/PlaybackClock.tsx
  src/components/views/messages/LegacyCallEvent.tsx
  src/shared-components/audio/Clock/Clock.stories.tsx
  src/shared-components/audio/Clock/Clock.test.tsx
  src/shared-components/audio/Clock/Clock.tsx
  src/shared-components/audio/Clock/__snapshots__/Clock.test.tsx.snap
  src/shared-components/audio/Clock/index.tsx
  src/shared-components/utils/DateUtils.ts
Labels: T-Task

#30463 Fix widget initialization in React development mode
  src/components/views/elements/AppTile.tsx
  src/stores/widgets/StopGapWidget.ts
Labels: T-Defect

#30398 MVVM - Introduce some helpers for snapshot management
  src/events/EventTileFactory.tsx
  src/shared-components/event-tiles/TextualEventView/TextualEventView.stories.tsx
  src/shared-components/event-tiles/TextualEventView/TextualEventView.test.tsx
  src/shared-components/event-tiles/TextualEventView/TextualEventView.tsx
  src/shared-components/event-tiles/TextualEventView/__snapshots__/TextualEventView.test.tsx.snap
  src/shared-components/event-tiles/TextualEventView/index.ts
  src/viewmodels/base/BaseViewModel.ts
  src/viewmodels/base/Snapshot.ts
  src/viewmodels/base/ViewModelSubscriptions.ts
  src/viewmodels/event-tiles/TextualEventViewModel.ts
  test/viewmodels/base/Snapshot-test.ts
  test/viewmodels/event-tiles/TextualEventViewModel-test.ts
Labels: T-Enhancement

#30509 Fix widget persistence in React development mode
  src/components/views/elements/AppTile.tsx
Labels: T-Defect

#30500 Refactor MultiInviter
  src/RoomInvite.tsx
  src/utils/MultiInviter.ts
Labels: T-Task

#30459 Fix issue of new room list taking up the full width
  src/components/structures/LoggedInView.tsx
  test/unit-tests/components/structures/LoggedInView-test.tsx
Labels: T-Defect

#30523 Fix line wrap around emoji verification
  res/css/views/verification/_VerificationShowSas.pcss
Labels: T-Defect

#30440 Show a blue lock for unencrypted rooms and hide the grey shield for encrypted rooms
  playwright/e2e/crypto/crypto.spec.ts
  playwright/snapshots/crypto/crypto.spec.ts/composer-e2e-icon-normal-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-selection-linux.png
  playwright/snapshots/polls/polls.spec.ts/ThreadView-with-a-poll-on-bubble-layout-linux.png
  playwright/snapshots/polls/polls.spec.ts/ThreadView-with-a-poll-on-group-layout-linux.png
  playwright/snapshots/release-announcement/releaseAnnouncement.spec.ts/release-announcement-All-new-pinned-messages-linux.png
  playwright/snapshots/threads/threads.spec.ts/Initial-ThreadView-on-bubble-layout-linux.png
  playwright/snapshots/threads/threads.spec.ts/Initial-ThreadView-on-group-layout-linux.png
  playwright/snapshots/threads/threads.spec.ts/Reply-to-the-location-on-ThreadView-linux.png
  playwright/snapshots/threads/threads.spec.ts/ThreadView-with-reaction-and-a-hidden-event-on-bubble-layout-linux.png
  playwright/snapshots/threads/threads.spec.ts/ThreadView-with-reaction-and-a-hidden-event-on-group-layout-linux.png
  playwright/snapshots/threads/threads.spec.ts/ThreadView-with-redacted-messages-on-bubble-layout-linux.png
  playwright/snapshots/threads/threads.spec.ts/ThreadView-with-redacted-messages-on-group-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/collapsed-gels-and-messages-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/collapsed-gels-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/configured-room-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-line-inline-start-margin-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tiles-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tiles-compact-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tiles-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tiles-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-and-messages-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-emote-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-redaction-placeholder-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/hidden-event-line-padding-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/hidden-event-line-zero-padding-irc-layout-linux.png
  src/components/views/rooms/E2EIcon.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/wysiwyg_composer/SendWysiwygComposer.tsx
  test/unit-tests/components/structures/RoomView-test.tsx
  test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/unit-tests/components/views/dialogs/__snapshots__/UntrustedDeviceDialog-test.tsx.snap
  test/unit-tests/components/views/rooms/wysiwyg_composer/SendWysiwygComposer-test.tsx
Labels: T-Enhancement

#30520 Fix downloading files with authenticated media API
  playwright/e2e/right-panel/file-panel.spec.ts
  src/components/views/messages/MFileBody.tsx
  test/unit-tests/components/views/messages/__snapshots__/MFileBody-test.tsx.snap
Labels: T-Defect

#30521 Fix call permissions check confusion around element call
  src/hooks/room/useRoomCall.tsx
Labels: T-Defect

#30542 Move test files into `test/unit-tests`
  test/unit-tests/components/views/dialogs/ModalWidgetDialog-test.tsx
  test/unit-tests/components/views/dialogs/security/InitialCryptoSetupDialog-test.tsx
  test/unit-tests/components/views/dialogs/security/ResetIdentityDialog-test.tsx
  test/unit-tests/components/views/dialogs/security/SetupEncryptionDialog-test.tsx
Labels: T-Task

#30550 Fix e2e test: share-by-url flakiness
  playwright/e2e/share-dialog/share-by-url.spec.ts
Labels: T-Task

#30552 Stop using deprecated js-sdk fields
  test/test-utils/client.ts
  test/unit-tests/DecryptionFailureTracker-test.ts
  test/unit-tests/components/structures/UserMenu-test.tsx
Labels: T-Task

#30541 Update `MultiInviter` to take an options object
  src/RoomInvite.tsx
  src/utils/MultiInviter.ts
  src/utils/RoomUpgrade.ts
  test/unit-tests/RoomInvite-test.ts
Labels: T-Task

#30553 A11y: move focus to right panel when opened
  playwright/snapshots/user-view/user-view.spec.ts/user-info-linux.png
  src/components/structures/RightPanel.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/unit-tests/components/views/elements/__snapshots__/AppTile-test.tsx.snap
Labels: T-Defect, A11y

#30563 Add some comments in `_font-sizes.pcss`
  res/css/_font-sizes.pcss
Labels: T-Task

#30566 Element Call widget driver: allow state keys to have a `_m.call` suffix
  src/stores/widgets/StopGapWidgetDriver.ts
  test/unit-tests/stores/widgets/StopGapWidgetDriver-test.ts
Labels: T-Task

#30601 Remove onSelectItem and space/enter handing from ListView
  src/components/utils/ListView.tsx
  src/components/viewmodels/memberlist/MemberListViewModel.tsx
  src/components/views/rooms/MemberList/MemberListView.tsx
  test/unit-tests/components/views/utils/ListView-test.tsx
Labels: T-Task

#30515 Move the room list to the new ListView(backed by react-virtuoso)
  package.json
  playwright/e2e/left-panel/room-list-panel/room-list-filter-sort.spec.ts
  playwright/e2e/left-panel/room-list-panel/room-list-panel.spec.ts
  playwright/e2e/left-panel/room-list-panel/room-list.spec.ts
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/unread-dm-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-panel.spec.ts/room-list-panel-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-panel.spec.ts/room-list-panel-smallscreen-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-activity-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-hover-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-hover-silent-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-invited-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-low-priority-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-mark-as-unread-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-mention-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-message-preview-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-notification-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-more-options-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-selection-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-public-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-silent-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-video-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-scrolled-linux.png
  res/css/views/rooms/RoomListPanel/_RoomListItemView.pcss
  src/Keyboard.ts
  src/components/utils/ListView.tsx
  src/components/viewmodels/roomlist/RoomListViewModel.tsx
  src/components/viewmodels/roomlist/useFilteredRooms.tsx
  src/components/viewmodels/roomlist/useStickyRoomList.tsx
  src/components/views/rooms/RoomListPanel/RoomList.tsx
  src/components/views/rooms/RoomListPanel/RoomListItemMenuView.tsx
  src/components/views/rooms/RoomListPanel/RoomListItemView.tsx
  src/components/views/rooms/RoomListPanel/RoomListView.tsx
  src/stores/room-list-v3/RoomListStoreV3.ts
  test/unit-tests/components/viewmodels/roomlist/RoomListHeaderViewModel-test.tsx
  test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/EmptyRoomList-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomList-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListItemView-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListView-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomList-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListItemMenuView-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListItemView-test.tsx.snap
  test/unit-tests/components/views/rooms/memberlist/MemberListHeaderView-test.tsx
  test/unit-tests/components/views/rooms/memberlist/MemberListView-test.tsx
  test/unit-tests/components/views/rooms/memberlist/common.tsx
  test/unit-tests/components/views/utils/ListView-test.tsx
  test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
  yarn.lock
Labels: T-Enhancement

#30565 Fix minor type setting issue in `README.md` (missing space)
  README.md
Labels: T-Task, Z-Community-PR

#30623 Fix: add missing tooltip and aria-label to lock icon next to composer
  src/components/views/rooms/MessageComposer.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap
Labels: T-Defect

#30634 Fix flakey e2e test: should select the next unread room -
  playwright/e2e/left-panel/room-list-panel/room-list.spec.ts
Labels: T-Task

#30636 Fix Jest test: Mock CallStore.getCall rather than individual hooks like useParticipants
  test/unit-tests/components/views/rooms/RoomHeader/RoomHeader-test.tsx
Labels: T-Task

#30646 Fix i18n of message when a setting is disabled
  src/settings/SettingsStore.ts
  src/settings/controllers/ServerSupportUnstableFeatureController.ts
Labels: T-Defect
