Repository element-hq/element-web, pull requests merged in 2025-10, with the labels that each got.

#30936 Add compound web storybook to EW storybook
  .storybook/main.ts
Labels: T-Task

#30908 Fix jitsi widget popout
  playwright/e2e/widgets/jitsi.spec.ts
  src/components/views/elements/AppTile.tsx
Labels: T-Defect

#30932 Improve handling of animated images, add support for AVIF animations
  src/ContentMessages.ts
  src/components/views/messages/MImageBody.tsx
  src/utils/Image.ts
  src/utils/MediaEventHelper.ts
  test/unit-tests/Image-test.ts
  test/unit-tests/utils/MediaEventHelper-test.ts
Labels: T-Defect

#30816 Hide calling buttons in room header before a room is created
  playwright/e2e/invite/invite-dialog.spec.ts
  playwright/snapshots/invite/invite-dialog.spec.ts/send-your-first-message-view-linux.png
  src/components/views/rooms/RoomHeader/RoomHeader.tsx
  src/hooks/room/useRoomCall.tsx
  test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap
Labels: T-Enhancement

#30867 Room List: Extend the viewport to avoid so many black spots when scrolling the room list
  src/components/views/rooms/RoomListPanel/RoomList.tsx
Labels: T-Enhancement

#30976 Remove console log from onEventSentinelUpdated
  src/components/views/elements/EventListSummary.tsx
Labels: T-Task
