Repository element-hq/element-web, pull requests merged in 2025-01, with the labels that each got.

#28838 Update matrix-wysiwyg to consume WASM asset
  package.json
  test/unit-tests/components/views/elements/SyntaxHighlight-test.tsx
  test/unit-tests/components/views/rooms/MessageComposer-test.tsx
  test/unit-tests/components/views/rooms/wysiwyg_composer/EditWysiwygComposer-test.tsx
  test/unit-tests/components/views/rooms/wysiwyg_composer/SendWysiwygComposer-test.tsx
  test/unit-tests/components/views/rooms/wysiwyg_composer/components/PlainTextComposer-test.tsx
  test/unit-tests/components/views/rooms/wysiwyg_composer/components/WysiwygAutocomplete-test.tsx
  test/unit-tests/components/views/rooms/wysiwyg_composer/components/WysiwygComposer-test.tsx
  test/unit-tests/components/views/rooms/wysiwyg_composer/utils/createMessageContent-test.ts
  yarn.lock
Labels: T-Enhancement

#28839 Docker: remove redundant dos2unix calls
  Dockerfile
Labels: T-Task

#28802 Stabilise playwright tests using createRoom util
  playwright/e2e/pinned-messages/index.ts
  playwright/e2e/read-receipts/high-level.spec.ts
  playwright/e2e/read-receipts/index.ts
  playwright/e2e/read-receipts/new-messages-in-threads.spec.ts
  playwright/e2e/read-receipts/new-messages-main-timeline.spec.ts
  playwright/e2e/read-receipts/new-messages-thread-roots.spec.ts
  playwright/e2e/read-receipts/read-receipts.spec.ts
  playwright/e2e/spaces/threads-activity-centre/index.ts
  playwright/pages/client.ts
Labels: T-Task

#28809 Fix and stabilise sliding sync playwright tests
  playwright/e2e/crypto/event-shields.spec.ts
  playwright/e2e/lazy-loading/lazy-loading.spec.ts
  playwright/e2e/sliding-sync/sliding-sync.spec.ts
  playwright/element-web-test.ts
  playwright/pages/ElementAppPage.ts
  playwright/pages/client.ts
  playwright/pages/network.ts
  playwright/plugins/sliding-sync-proxy/index.ts
Labels: T-Task

#28840 Docker: allow configuration of HTTP listen port via env var
  Dockerfile
  docker/nginx-templates/default.conf.template
  docs/install.md
Labels: T-Enhancement

#28853 Fix pill rendering in dev mode
  src/utils/pillify.tsx
  src/utils/react.tsx
  src/utils/tooltipify.tsx
Labels: T-Task

#28849 Docker: run as non-root
  Dockerfile
  docs/install.md
Labels: T-Enhancement

#28855 Fix some flaky playwright tests
  playwright/e2e/audio-player/audio-player.spec.ts
  playwright/e2e/composer/RTE.spec.ts
  playwright/e2e/login/soft_logout.spec.ts
  playwright/e2e/read-receipts/high-level.spec.ts
  playwright/e2e/settings/roles-permissions-room-settings-tab.spec.ts
  playwright/e2e/spotlight/spotlight.spec.ts
Labels: T-Task

#28858 Add a playwright test for backup reset / deleted
  playwright/e2e/crypto/backups.spec.ts
  playwright/e2e/csAPI.ts
Labels: T-Task

#28876 Update matrix-authentication-service in Playwright tests
  playwright/e2e/crypto/backups.spec.ts
  playwright/e2e/oidc/oidc-native.spec.ts
  playwright/plugins/homeserver/synapse/templates/mas-oidc/homeserver.yaml
  playwright/plugins/matrix-authentication-service/config.yaml
  playwright/plugins/matrix-authentication-service/index.ts
Labels: T-Task

#28881 Fix building the automations mermaid diagram
  scripts/gen-workflow-mermaid.ts
Labels: T-Defect

#28880 Prepare for switch to testcontainers in playwright
  playwright/e2e/app-loading/guest-registration.spec.ts
  playwright/e2e/crypto/complete-security.spec.ts
  playwright/e2e/crypto/decryption-failure-messages.spec.ts
  playwright/e2e/crypto/dehydration.spec.ts
  playwright/e2e/crypto/device-verification.spec.ts
  playwright/e2e/crypto/event-shields.spec.ts
  playwright/e2e/crypto/logout.spec.ts
  playwright/e2e/crypto/utils.ts
  playwright/e2e/csAPI.ts
  playwright/e2e/forgot-password/forgot-password.spec.ts
  playwright/e2e/login/login.spec.ts
  playwright/e2e/login/overwrite_login.spec.ts
  playwright/e2e/login/soft_logout.spec.ts
  playwright/e2e/login/utils.ts
  playwright/e2e/oidc/index.ts
  playwright/e2e/register/email.spec.ts
  playwright/e2e/register/register.spec.ts
  playwright/element-web-test.ts
  playwright/pages/bot.ts
  playwright/pages/crypto.ts
  playwright/plugins/homeserver/index.ts
  playwright/plugins/homeserver/synapse/index.ts
Labels: T-Task

#28878 Speed up Netlify CI/CD
  .github/workflows/build.yml
  .github/workflows/netlify.yaml
Labels: T-Task

#28879 Stabilise sliding sync playwright test
  playwright/e2e/sliding-sync/sliding-sync.spec.ts
  playwright/element-web-test.ts
Labels: T-Task

#28925 Playwright fixes and improvements
  .github/CODEOWNERS
  .github/labels.yml
  .github/workflows/end-to-end-tests.yaml
  .github/workflows/playwright-image-updates.yaml
  docs/playwright.md
  playwright/stale-screenshot-reporter.ts
Labels: T-Task

#28848 Use homeserver in a worker-scoped fixture
  playwright/e2e/crypto/backups-mas.spec.ts
  playwright/e2e/crypto/backups.spec.ts
  playwright/e2e/crypto/dehydration.spec.ts
  playwright/e2e/forgot-password/forgot-password.spec.ts
  playwright/e2e/login/consent.spec.ts
  playwright/e2e/login/login-consent.spec.ts
  playwright/e2e/login/login-sso.spec.ts
  playwright/e2e/login/logout_redirect_url.spec.ts
  playwright/e2e/login/soft_logout.spec.ts
  playwright/e2e/login/soft_logout_oauth.spec.ts
  playwright/e2e/login/utils.ts
  playwright/e2e/oidc/oidc-native.spec.ts
  playwright/e2e/register/email.spec.ts
  playwright/e2e/register/register.spec.ts
  playwright/e2e/spaces/threads-activity-centre/index.ts
  playwright/e2e/spaces/threads-activity-centre/threadsActivityCentre.spec.ts
  playwright/element-web-test.ts
  playwright/plugins/homeserver/dendrite/index.ts
  playwright/plugins/homeserver/index.ts
  playwright/plugins/homeserver/synapse/consentHomeserver.ts
  playwright/plugins/homeserver/synapse/emailHomeserver.ts
  playwright/plugins/homeserver/synapse/legacyOAuthHomeserver.ts
  playwright/plugins/homeserver/synapse/masHomeserver.ts
  playwright/services.ts
  playwright/snapshots/chat-export/html-export.spec.ts/html-export-linux.png
  playwright/snapshots/invite/invite-dialog.spec.ts/invite-dialog-dm-with-user-pill-linux.png
  playwright/snapshots/invite/invite-dialog.spec.ts/invite-dialog-dm-without-user-linux.png
  playwright/snapshots/invite/invite-dialog.spec.ts/invite-dialog-room-with-user-pill-linux.png
  playwright/snapshots/invite/invite-dialog.spec.ts/invite-dialog-room-without-user-linux.png
  playwright/snapshots/settings/account-user-settings-tab.spec.ts/account-linux.png
  playwright/snapshots/settings/account-user-settings-tab.spec.ts/account-smallscreen-linux.png
  playwright/snapshots/share-dialog/share-dialog.spec.ts/share-dialog-user-linux.png
  playwright/snapshots/user-menu/user-menu.spec.ts/user-menu-linux.png
  playwright/testcontainers/HomeserverContainer.ts
  playwright/testcontainers/dendrite.ts
  playwright/testcontainers/synapse.ts
  playwright/testcontainers/utils.ts
  yarn.lock
Labels: T-Task

#28944 Improve playwright docs
  docs/playwright.md
Labels: T-Task

#28874 Implement new memberlist design with MVVM architecture
  package.json
  playwright/e2e/crypto/dehydration.spec.ts
  playwright/e2e/lazy-loading/lazy-loading.spec.ts
  playwright/e2e/right-panel/memberlist.spec.ts
  playwright/e2e/right-panel/right-panel.spec.ts
  playwright/element-web-test.ts
  playwright/pages/ElementAppPage.ts
  playwright/snapshots/right-panel/memberlist.spec.ts/with-four-members-linux.png
  playwright/testcontainers/synapse.ts
  res/css/_components.pcss
  res/css/views/messages/_DisambiguatedProfile.pcss
  res/css/views/rooms/_E2EIconView.pcss
  res/css/views/rooms/_EntityTile.pcss
  res/css/views/rooms/_MemberList.pcss
  res/css/views/rooms/_MemberListHeaderView.pcss
  res/css/views/rooms/_MemberListView.pcss
  res/css/views/rooms/_MemberTileView.pcss
  res/css/views/rooms/_OverflowTile.pcss
  res/css/views/rooms/_PresenceIconView.pcss
  src/components/structures/MainSplit.tsx
  src/components/structures/RightPanel.tsx
  src/components/viewmodels/memberlist/MemberListViewModel.tsx
  src/components/viewmodels/memberlist/tiles/MemberTileViewModel.tsx
  src/components/viewmodels/memberlist/tiles/ThreePidTileViewModel.tsx
  src/components/views/dialogs/ForwardDialog.tsx
  src/components/views/messages/DisambiguatedProfile.tsx
  src/components/views/rooms/E2EIcon.tsx
  src/components/views/rooms/EntityTile.tsx
  src/components/views/rooms/MemberList.tsx
  src/components/views/rooms/MemberList/MemberListHeaderView.tsx
  src/components/views/rooms/MemberList/MemberListView.tsx
  src/components/views/rooms/MemberList/tiles/RoomMemberTileView.tsx
  src/components/views/rooms/MemberList/tiles/ThreePidInviteTileView.tsx
  src/components/views/rooms/MemberList/tiles/common/E2EIconView.tsx
  src/components/views/rooms/MemberList/tiles/common/MemberTileLayout.tsx
  src/components/views/rooms/MemberList/tiles/common/PresenceIconView.tsx
  src/components/views/rooms/MemberTile.tsx
  src/components/views/rooms/OverflowTileView.tsx
  src/i18n/strings/en_EN.json
  src/models/rooms/PresenceState.ts
  src/models/rooms/RoomMember.ts
  src/models/rooms/ThreePIDInvite.ts
  test/test-utils/test-utils.ts
  test/unit-tests/components/structures/RightPanel-test.tsx
  test/unit-tests/components/structures/__snapshots__/MainSplit-test.tsx.snap
  test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/unit-tests/components/views/rooms/MemberList-test.tsx
  test/unit-tests/components/views/rooms/MemberTile-test.tsx
  test/unit-tests/components/views/rooms/__snapshots__/MemberTile-test.tsx.snap
  test/unit-tests/components/views/rooms/memberlist/MemberListHeaderView-test.tsx
  test/unit-tests/components/views/rooms/memberlist/MemberListView-test.tsx
  test/unit-tests/components/views/rooms/memberlist/MemberTileView-test.tsx
  test/unit-tests/components/views/rooms/memberlist/PresenceIconView-test.tsx
  test/unit-tests/components/views/rooms/memberlist/__snapshots__/MemberTileView-test.tsx.snap
  test/unit-tests/components/views/rooms/memberlist/__snapshots__/PresenceIconView-test.tsx.snap
  test/unit-tests/components/views/rooms/memberlist/common.tsx
  yarn.lock
Labels: T-Enhancement

#28954 Remove ts-prune as it has been archived over a year ago
  .github/workflows/static_analysis.yaml
  knip.ts
  package.json
  src/Lifecycle.ts
  src/utils/arrays.ts
Labels: T-Task

#28947 React to MatrixEvent sender/target being updated for rendering state events
  src/components/views/elements/EventListSummary.tsx
  src/components/views/messages/TextualEvent.tsx
  src/hooks/usePinnedEvents.ts
  src/utils/exportUtils/Exporter.ts
  test/unit-tests/components/views/right_panel/__snapshots__/PinnedMessagesCard-test.tsx.snap
Labels: T-Defect

#28959 Fix flaky playwright tests
  docs/playwright.md
  playwright/e2e/forgot-password/forgot-password.spec.ts
  playwright/e2e/login/login-consent.spec.ts
  playwright/e2e/oidc/index.ts
  playwright/e2e/oidc/oidc-native.spec.ts
  playwright/e2e/one-to-one-chat/one-to-one-chat.spec.ts
  playwright/e2e/share-dialog/share-dialog.spec.ts
  playwright/e2e/sliding-sync/sliding-sync.spec.ts
  playwright/services.ts
  playwright/snapshots/share-dialog/share-dialog.spec.ts/share-dialog-event-linux.png
  playwright/testcontainers/mailhog.ts
Labels: T-Task

#28972 Playwright: get console logs without trace
  playwright/logger.ts
  playwright/services.ts
  playwright/testcontainers/utils.ts
Labels: T-Task

#28980 Add flaky test labels for playwright projects
  .github/labels.yml
  playwright/flaky-reporter.ts
Labels: T-Task

#28978 Speed up Netlify further
  .github/workflows/build.yml
Labels: T-Task

#28976 Enable previously disabled Playwright tests
  playwright/e2e/read-receipts/read-receipts.spec.ts
  playwright/e2e/threads/threads.spec.ts
  playwright/e2e/timeline/timeline.spec.ts
  playwright/snapshots/threads/threads.spec.ts/Initial-ThreadView-on-bubble-layout-linux.png
  playwright/snapshots/threads/threads.spec.ts/Initial-ThreadView-on-group-layout-linux.png
  playwright/snapshots/threads/threads.spec.ts/ThreadView-with-reaction-and-a-hidden-event-on-bubble-layout-linux.png
  playwright/snapshots/threads/threads.spec.ts/ThreadView-with-reaction-and-a-hidden-event-on-group-layout-linux.png
  playwright/snapshots/threads/threads.spec.ts/ThreadView-with-redacted-messages-on-bubble-layout-linux.png
  playwright/snapshots/threads/threads.spec.ts/ThreadView-with-redacted-messages-on-group-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/hidden-event-line-padding-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/hidden-event-line-zero-padding-irc-layout-linux.png
Labels: T-Task

#28975 Fix flaky playwright tests
  playwright/e2e/crypto/backups-mas.spec.ts
  playwright/e2e/login/login-consent.spec.ts
  playwright/e2e/right-panel/right-panel.spec.ts
  playwright/e2e/room-directory/room-directory.spec.ts
  playwright/e2e/settings/general-room-settings-tab.spec.ts
  playwright/pages/client.ts
  playwright/services.ts
  playwright/stale-screenshot-reporter.ts
  playwright/testcontainers/mas.ts
  playwright/testcontainers/synapse.ts
Labels: T-Task

#28984 Fix flaky playwright tests
  playwright/e2e/crypto/backups-mas.spec.ts
  playwright/e2e/login/login-sso.spec.ts
  playwright/e2e/login/soft_logout_oauth.spec.ts
  playwright/e2e/login/utils.ts
  playwright/plugins/homeserver/synapse/legacyOAuthHomeserver.ts
  playwright/plugins/oauth_server/index.ts
  playwright/services.ts
Labels: T-Task

#28988 Simplify playwright
  playwright/e2e/app-loading/guest-registration.spec.ts
  playwright/e2e/crypto/backups-mas.spec.ts
  playwright/e2e/crypto/dehydration.spec.ts
  playwright/e2e/right-panel/memberlist.spec.ts
  playwright/element-web-test.ts
  playwright/pages/bot.ts
  playwright/plugins/homeserver/dendrite/index.ts
  playwright/plugins/homeserver/synapse/consentHomeserver.ts
  playwright/plugins/homeserver/synapse/emailHomeserver.ts
  playwright/plugins/homeserver/synapse/legacyOAuthHomeserver.ts
  playwright/plugins/homeserver/synapse/masHomeserver.ts
  playwright/plugins/homeserver/synapse/uiaLongSessionTimeoutHomeserver.ts
  playwright/services.ts
  playwright/testcontainers/synapse.ts
Labels: T-Task

#28989 Fix flaky playwright tests
  playwright/e2e/crypto/invisible-crypto.spec.ts
  playwright/e2e/integration-manager/kick.spec.ts
  playwright/e2e/read-receipts/reactions-in-threads.spec.ts
  playwright/e2e/timeline/timeline.spec.ts
  playwright/services.ts
  playwright/testcontainers/synapse.ts
Labels: T-Task

#28957 Fix flaky playwright tests
  playwright/e2e/csAPI.ts
  playwright/e2e/spotlight/spotlight.spec.ts
  playwright/element-web-test.ts
  playwright/plugins/homeserver/index.ts
  playwright/plugins/utils/api.ts
  playwright/services.ts
  playwright/testcontainers/HomeserverContainer.ts
  playwright/testcontainers/dendrite.ts
  playwright/testcontainers/mas.ts
  playwright/testcontainers/synapse.ts
Labels: T-Task

#28888 Run Playwright tests against Dendrite & Pinecone periodically
  .github/workflows/end-to-end-tests.yaml
  docs/playwright.md
  playwright.config.ts
  playwright/e2e/create-room/create-room.spec.ts
  playwright/e2e/crypto/backups.spec.ts
  playwright/e2e/crypto/complete-security.spec.ts
  playwright/e2e/crypto/crypto.spec.ts
  playwright/e2e/crypto/decryption-failure-messages.spec.ts
  playwright/e2e/crypto/device-verification.spec.ts
  playwright/e2e/crypto/logout.spec.ts
  playwright/e2e/editing/editing.spec.ts
  playwright/e2e/knock/create-knock-room.spec.ts
  playwright/e2e/knock/knock-into-room.spec.ts
  playwright/e2e/knock/manage-knocks.spec.ts
  playwright/e2e/lazy-loading/lazy-loading.spec.ts
  playwright/e2e/login/login-consent.spec.ts
  playwright/e2e/oidc/oidc-native.spec.ts
  playwright/e2e/one-to-one-chat/one-to-one-chat.spec.ts
  playwright/e2e/permalinks/permalinks.spec.ts
  playwright/e2e/polls/polls.spec.ts
  playwright/e2e/read-receipts/editing-messages-in-threads.spec.ts
  playwright/e2e/read-receipts/editing-messages-main-timeline.spec.ts
  playwright/e2e/read-receipts/editing-messages-thread-roots.spec.ts
  playwright/e2e/read-receipts/high-level.spec.ts
  playwright/e2e/read-receipts/new-messages-in-threads.spec.ts
  playwright/e2e/read-receipts/new-messages-main-timeline.spec.ts
  playwright/e2e/read-receipts/new-messages-thread-roots.spec.ts
  playwright/e2e/read-receipts/reactions-in-threads.spec.ts
  playwright/e2e/read-receipts/reactions-main-timeline.spec.ts
  playwright/e2e/read-receipts/reactions-thread-roots.spec.ts
  playwright/e2e/read-receipts/read-receipts.spec.ts
  playwright/e2e/read-receipts/redactions-in-threads.spec.ts
  playwright/e2e/read-receipts/redactions-main-timeline.spec.ts
  playwright/e2e/read-receipts/redactions-thread-roots.spec.ts
  playwright/e2e/register/register.spec.ts
  playwright/e2e/right-panel/file-panel.spec.ts
  playwright/e2e/right-panel/right-panel.spec.ts
  playwright/e2e/room-directory/room-directory.spec.ts
  playwright/e2e/room_options/marked_unread.spec.ts
  playwright/e2e/settings/general-room-settings-tab.spec.ts
  playwright/e2e/sliding-sync/sliding-sync.spec.ts
  playwright/e2e/spaces/spaces.spec.ts
  playwright/e2e/spaces/threads-activity-centre/threadsActivityCentre.spec.ts
  playwright/e2e/spotlight/spotlight.spec.ts
  playwright/e2e/threads/threads.spec.ts
  playwright/e2e/widgets/stickers.spec.ts
  playwright/flaky-reporter.ts
  playwright/plugins/homeserver/dendrite/index.ts
  playwright/plugins/homeserver/index.ts
  playwright/plugins/homeserver/synapse/consentHomeserver.ts
  playwright/plugins/homeserver/synapse/emailHomeserver.ts
  playwright/plugins/homeserver/synapse/legacyOAuthHomeserver.ts
  playwright/plugins/homeserver/synapse/masHomeserver.ts
  playwright/services.ts
  playwright/testcontainers/dendrite.ts
Labels: T-Task

#29001 Retry loading chunks to make the app more resilient
  package.json
  src/components/views/rooms/wysiwyg_composer/DynamicImportWysiwygComposer.tsx
  webpack.config.js
  yarn.lock
Labels: T-Enhancement

#28673 Add `Recovery` section in the new user settings `Encryption` tab
  .github/CODEOWNERS
  playwright/e2e/crypto/device-verification.spec.ts
  playwright/e2e/crypto/utils.ts
  playwright/e2e/settings/encryption-user-tab/index.ts
  playwright/e2e/settings/encryption-user-tab/recovery.spec.ts
  playwright/snapshots/settings/account-user-settings-tab.spec.ts/account-linux.png
  playwright/snapshots/settings/account-user-settings-tab.spec.ts/account-smallscreen-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/appearance-tab-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/window-12px-linux.png
  playwright/snapshots/settings/encryption-user-tab/recovery.spec.ts/change-key-1-encryption-tab-linux.png
  playwright/snapshots/settings/encryption-user-tab/recovery.spec.ts/change-key-2-encryption-tab-linux.png
  playwright/snapshots/settings/encryption-user-tab/recovery.spec.ts/default-recovery-linux.png
  playwright/snapshots/settings/encryption-user-tab/recovery.spec.ts/out-of-sync-recovery-linux.png
  playwright/snapshots/settings/encryption-user-tab/recovery.spec.ts/set-up-key-1-encryption-tab-linux.png
  playwright/snapshots/settings/encryption-user-tab/recovery.spec.ts/set-up-key-2-encryption-tab-linux.png
  playwright/snapshots/settings/encryption-user-tab/recovery.spec.ts/set-up-key-3-encryption-tab-linux.png
  playwright/snapshots/settings/encryption-user-tab/recovery.spec.ts/set-up-recovery-linux.png
  playwright/snapshots/settings/encryption-user-tab/recovery.spec.ts/verify-device-encryption-tab-linux.png
  playwright/snapshots/settings/preferences-user-settings-tab.spec.ts/Preferences-user-settings-tab-should-be-rendered-properly-1-linux.png
  res/css/_common.pcss
  res/css/_components.pcss
  res/css/views/settings/_SettingsHeader.pcss
  res/css/views/settings/_SettingsSubheader.pcss
  res/css/views/settings/encryption/_ChangeRecoveryKey.pcss
  res/css/views/settings/encryption/_EncryptionCard.pcss
  res/css/views/settings/tabs/_SettingsSection.pcss
  res/css/views/settings/tabs/_SettingsTab.pcss
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/dialogs/UserTab.ts
  src/components/views/settings/SettingsHeader.tsx
  src/components/views/settings/SettingsSubheader.tsx
  src/components/views/settings/encryption/ChangeRecoveryKey.tsx
  src/components/views/settings/encryption/EncryptionCard.tsx
  src/components/views/settings/encryption/RecoveryPanel.tsx
  src/components/views/settings/shared/SettingsSection.tsx
  src/components/views/settings/tabs/SettingsTab.tsx
  src/components/views/settings/tabs/user/EncryptionUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/test-utils/test-utils.ts
  test/unit-tests/components/views/dialogs/__snapshots__/UserSettingsDialog-test.tsx.snap
  test/unit-tests/components/views/dialogs/security/__snapshots__/CreateSecretStorageDialog-test.tsx.snap
  test/unit-tests/components/views/settings/SettingsHeader-test.tsx
  test/unit-tests/components/views/settings/SettingsSubheader-test.tsx
  test/unit-tests/components/views/settings/__snapshots__/SettingsHeader-test.tsx.snap
  test/unit-tests/components/views/settings/__snapshots__/SettingsSubheader-test.tsx.snap
  test/unit-tests/components/views/settings/encryption/ChangeRecoveryKey-test.tsx
  test/unit-tests/components/views/settings/encryption/EncryptionCard-test.tsx
  test/unit-tests/components/views/settings/encryption/RecoveryPanel-test.tsx
  test/unit-tests/components/views/settings/encryption/__snapshots__/ChangeRecoveryKey-test.tsx.snap
  test/unit-tests/components/views/settings/encryption/__snapshots__/EncryptionCard-test.tsx.snap
  test/unit-tests/components/views/settings/encryption/__snapshots__/RecoveryPanel-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/user/EncryptionUserSettingsTab-test.tsx
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/EncryptionUserSettingsTab-test.tsx.snap
Labels: T-Enhancement

#29008 Refactor LegacyCallHandler event emitter to use TypedEventEmitter
  playwright/e2e/voip/pstn.spec.ts
  playwright/snapshots/voip/pstn.spec.ts/dialpad-linux.png
  playwright/snapshots/voip/pstn.spec.ts/dialpad-trigger-linux.png
  src/LegacyCallHandler.tsx
  src/components/structures/LeftPanel.tsx
  src/components/structures/RoomView.tsx
  src/components/views/rooms/RoomList.tsx
  src/dispatcher/actions.ts
Labels: T-Enhancement

#28652 Enable react-compiler eslint to spot antipatterns
  .eslintrc.js
  __mocks__/maplibre-gl.js
  package.json
  src/accessibility/RovingTabIndex.tsx
  src/components/structures/AutocompleteInput.tsx
  src/components/structures/ContextMenu.tsx
  src/components/structures/FilePanel.tsx
  src/components/structures/NotificationPanel.tsx
  src/components/structures/RoomSearchView.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/ThreadPanel.tsx
  src/components/structures/ThreadView.tsx
  src/components/utils/Box.tsx
  src/components/utils/Flex.tsx
  src/components/viewmodels/memberlist/MemberListViewModel.tsx
  src/components/views/elements/EffectsOverlay.tsx
  src/components/views/elements/Measured.tsx
  src/components/views/right_panel/TimelineCard.tsx
  src/components/views/rooms/ReadReceiptGroup.tsx
  src/components/views/rooms/UserIdentityWarning.tsx
  src/components/views/rooms/wysiwyg_composer/EditWysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/SendWysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/useComposerFunctions.ts
  src/components/views/rooms/wysiwyg_composer/hooks/usePlainTextInitialization.ts
  src/components/views/settings/ThemeChoicePanel.tsx
  src/components/views/settings/tabs/room/VoipRoomSettingsTab.tsx
  src/components/views/spaces/QuickThemeSwitcher.tsx
  src/components/views/spaces/threads-activity-centre/useUnreadThreadRooms.ts
  src/contexts/ScopedRoomContext.tsx
  src/contexts/ToastContext.tsx
  src/hooks/useAsyncRefreshMemo.ts
  src/hooks/useRoomNotificationState.ts
  src/hooks/useTransition.ts
  src/utils/location/useMap.ts
  yarn.lock
Labels: T-Task

#28946 Add toast for recovery keys being out of sync
  playwright/e2e/crypto/event-shields.spec.ts
  playwright/e2e/crypto/utils.ts
  playwright/e2e/room/room-header.spec.ts
  playwright/e2e/settings/encryption-user-tab/recovery.spec.ts
  playwright/snapshots/crypto/toasts.spec.ts/key-storage-out-of-sync-toast-linux.png
  src/DeviceListener.ts
  src/components/views/toasts/GenericToast.tsx
  src/i18n/strings/en_EN.json
  src/toasts/SetupEncryptionToast.ts
  src/utils/login.ts
  test/unit-tests/DeviceListener-test.ts
  test/unit-tests/toasts/SetupEncryptionToast-test.tsx
  test/unit-tests/utils/login-test.ts
Labels: T-Enhancement, X-Run-All-Tests

#29007 Fix more flaky playwright tests
  playwright/e2e/audio-player/audio-player.spec.ts
  playwright/e2e/knock/create-knock-room.spec.ts
  playwright/e2e/knock/knock-into-room.spec.ts
  playwright/e2e/messages/messages.spec.ts
  playwright/e2e/pinned-messages/pinned-messages.spec.ts
  playwright/e2e/settings/encryption-user-tab/index.ts
  playwright/e2e/settings/encryption-user-tab/recovery.spec.ts
  playwright/e2e/spaces/spaces.spec.ts
  playwright/e2e/spaces/threads-activity-centre/index.ts
  playwright/e2e/timeline/timeline.spec.ts
  playwright/flaky-reporter.ts
  playwright/pages/ElementAppPage.ts
  playwright/pages/client.ts
  playwright/services.ts
Labels: T-Task

#29029 Implement changes to memberlist from feedback
  playwright/snapshots/right-panel/memberlist.spec.ts/with-four-members-linux.png
  res/css/_components.pcss
  res/css/views/rooms/_InvitedIconView.pcss
  res/css/views/rooms/_MemberListView.pcss
  res/css/views/rooms/_MemberTileView.pcss
  src/components/viewmodels/memberlist/MemberListViewModel.tsx
  src/components/viewmodels/memberlist/tiles/ThreePidTileViewModel.tsx
  src/components/views/rooms/MemberList/MemberListHeaderView.tsx
  src/components/views/rooms/MemberList/MemberListView.tsx
  src/components/views/rooms/MemberList/tiles/RoomMemberTileView.tsx
  src/components/views/rooms/MemberList/tiles/ThreePidInviteTileView.tsx
  src/components/views/rooms/MemberList/tiles/common/InvitedIconView.tsx
  src/components/views/rooms/MemberList/tiles/common/MemberTileView.tsx
  test/unit-tests/components/views/rooms/memberlist/__snapshots__/MemberTileView-test.tsx.snap
Labels: T-Enhancement

#29013 Switch to secure random strings
  src/components/views/elements/LabelledToggleSwitch.tsx
  src/components/views/elements/SettingsFlag.tsx
  src/components/views/elements/StyledCheckbox.tsx
  src/components/views/messages/MBeaconBody.tsx
  src/components/views/messages/MLocationBody.tsx
  src/models/Call.ts
  src/rageshake/rageshake.ts
  src/utils/WidgetUtils.ts
  src/utils/oidc/authorize.ts
  src/vector/platform/ElectronPlatform.tsx
  test/setupTests.ts
  test/test-utils/poll.ts
  test/unit-tests/components/views/settings/Notifications-test.tsx
  test/unit-tests/components/views/spaces/SpaceSettingsVisibilityTab-test.tsx
  test/unit-tests/utils/oidc/authorize-test.ts
Labels: T-Defect

#29038 Improve release documentation for staging.element.io deployments
  docs/release.md
Labels: T-Task

#29074 Remove unused toast screenshot
  playwright/snapshots/crypto/toasts.spec.ts/key-storage-out-of-sync-toast-linux.png
Labels: T-Task

#28270 Fix outstanding UX issues with replies/mentions/keyword notifs
  res/css/views/elements/_Pill.pcss
  res/css/views/rooms/_EventTile.pcss
  src/components/views/elements/Pill.tsx
  src/components/views/messages/TextualBody.tsx
  test/unit-tests/components/views/messages/TextualBody-test.tsx
Labels: T-Enhancement, Z-Community-PR

#29083 Fix identity server settings visibility
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/SecurityUserSettingsTab-test.tsx.snap
Labels: T-Defect

#29073 Add cryptography information in devtools
  .github/CODEOWNERS
  res/css/_components.pcss
  res/css/views/dialogs/_Crypto.pcss
  src/components/views/dialogs/DevtoolsDialog.tsx
  src/components/views/dialogs/devtools/Crypto.tsx
  src/i18n/strings/en_EN.json
  test/test-utils/test-utils.ts
  test/unit-tests/components/views/dialogs/__snapshots__/DevtoolsDialog-test.tsx.snap
  test/unit-tests/components/views/dialogs/devtools/Crypto-test.tsx
  test/unit-tests/components/views/dialogs/devtools/__snapshots__/Crypto-test.tsx.snap
Labels: T-Task

#29066 e2e test: Check key backup with js-sdk api instead of relying of `Security & Privacy` tab
  playwright/e2e/crypto/device-verification.spec.ts
  playwright/e2e/crypto/utils.ts
  playwright/e2e/settings/encryption-user-tab/recovery.spec.ts
Labels: T-Task

#29087 Tidy up unused classes & icons in UserMenu styles
  res/css/structures/_UserMenu.pcss
  res/img/element-icons/roomlist/dnd-cross.svg
  res/img/element-icons/roomlist/dnd.svg
Labels: T-Task

#29090 e2e test: Verify session with the encryption tab instead of the security & privacy tab
  playwright/e2e/crypto/utils.ts
Labels: T-Defect

#28969 Move threads header below base card header
  res/css/views/right_panel/_ThreadPanel.pcss
  src/components/structures/ThreadPanel.tsx
  test/unit-tests/components/structures/__snapshots__/ThreadPanel-test.tsx.snap
Labels: T-Enhancement

#29100 support non-VS16 emoji ligatures in TwemojiMozilla
  res/fonts/Twemoji_Mozilla/TwemojiMozilla-colr.woff2
Labels: T-Defect

#28949 Allow navigating through the memberlist using up/down keys
  src/components/utils/Flex.tsx
  src/components/views/rooms/MemberList/MemberListView.tsx
  src/components/views/rooms/MemberList/tiles/common/MemberTileView.tsx
  test/unit-tests/components/views/rooms/memberlist/__snapshots__/MemberTileView-test.tsx.snap
Labels: T-Enhancement

#28968 Style room header icons and facepile for toggled state
  res/css/views/rooms/_RoomHeader.pcss
  src/components/structures/RoomView.tsx
  src/components/structures/WaitingForThirdPartyRoomView.tsx
  src/components/views/elements/FacePile.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomHeader/RoomHeader.tsx
  src/components/views/rooms/RoomHeader/VideoRoomChatButton.tsx
  src/components/views/rooms/RoomHeader/toggle/ToggleableIcon.tsx
  src/components/views/rooms/RoomHeader/toggle/useToggled.tsx
  src/contexts/CurrentRightPanelPhaseContext.tsx
  src/hooks/right-panel/useCurrentPhase.ts
  src/stores/right-panel/RightPanelStore.ts
  test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomHeader/RoomHeader-test.tsx
  test/unit-tests/components/views/rooms/RoomHeader/__snapshots__/RoomHeader-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomHeader/__snapshots__/VideoRoomChatButton-test.tsx.snap
Labels: T-Enhancement

#29112 Update matrix-widget-api
  yarn.lock
Labels: A-VoIP, A-Widgets, T-Enhancement, A-Element-Call

#28342 Make themed widgets reflect the effective theme
  src/components/structures/MatrixChat.tsx
  src/components/views/dialogs/ModalWidgetDialog.tsx
  src/settings/watchers/ThemeWatcher.ts
  src/stores/widgets/StopGapWidget.ts
  test/components/views/dialogs/ModalWidgetDialog-test.tsx
  test/unit-tests/stores/widgets/StopGapWidget-test.ts
Labels: T-Defect

#29115 update to twemoji 15.1.0
  res/fonts/Twemoji_Mozilla/TwemojiMozilla-colr.woff2
Labels: T-Enhancement

#29134 Remove call to `MatrixClient.setGlobalErrorOnUnknownDevices`
  playwright/pages/bot.ts
  src/components/structures/MatrixChat.tsx
  test/unit-tests/components/structures/MatrixChat-test.tsx
Labels: T-Task

#29132 Bump emojibase_bindings to include emoji 15.1
  package.json
  yarn.lock
Labels: T-Task

#29143 Stop showing a dialog prompting the user to enter an old recovery key
  playwright/e2e/crypto/backups.spec.ts
  playwright/e2e/crypto/crypto.spec.ts
  playwright/e2e/crypto/dehydration.spec.ts
  playwright/e2e/crypto/utils.ts
  src/SecurityManager.ts
  test/unit-tests/SecurityManager-test.ts
Labels: T-Defect

#29067 feat(crypto): Support verification violation composer banner
  res/css/views/rooms/_UserIdentityWarning.pcss
  src/components/viewmodels/rooms/UserIdentityWarningViewModel.tsx
  src/components/views/rooms/UserIdentityWarning.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/structures/RoomView-test.tsx
  test/unit-tests/components/views/rooms/UserIdentityWarning-test.tsx
Labels: T-Task

#29153 Ensure switching rooms does not wrongly focus timeline search
  src/stores/right-panel/RightPanelStoreIPanelState.ts
Labels: T-Defect

#29021 Schedule dehydration on reload if the dehydration key is already cached locally
  src/MatrixClientPeg.ts
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/utils/device/dehydration.ts
  test/unit-tests/MatrixClientPeg-test.ts
  test/unit-tests/components/structures/MatrixChat-test.tsx
Labels: T-Enhancement
