Repository element-hq/element-web, pull requests merged in 2025-06, with the labels that each got.

#30060 Add low priority filter pill to the room list UI
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/room-panel-empty-room-list-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/unread-primary-filters-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/unselected-primary-filters-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-panel.spec.ts/room-list-panel-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-panel.spec.ts/room-list-panel-smallscreen-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-hover-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-more-options-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-selection-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-public-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-silent-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-video-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-scrolled-linux.png
  src/components/viewmodels/roomlist/useFilteredRooms.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPanel-test.tsx.snap
Labels: T-Enhancement

#30067 Fix flaky OIDC test by matching text exactly
  playwright/e2e/oidc/oidc-native.spec.ts
Labels: T-Task

#30079 Add sanity checks to prevent users from ignoring themselves
  src/components/structures/RoomView.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/structures/RoomView-test.tsx
  test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap
Labels: T-Defect

#30066 Cherry pick fix for oidc failures in playwright
  playwright/e2e/crypto/backups-mas.spec.ts
  playwright/e2e/oidc/oidc-native.spec.ts
Labels: T-Task

#30070 RoomListStore: Sort low priority rooms to the bottom of the list
  src/stores/room-list-v3/skip-list/sorters/RecencySorter.ts
  test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
Labels: T-Enhancement

#30071 Low priority menu item should be a toggle
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-more-options-linux.png
  src/components/viewmodels/roomlist/RoomListItemMenuViewModel.tsx
  src/components/views/rooms/RoomListPanel/RoomListItemMenuView.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListItemMenuView-test.tsx
Labels: T-Defect

#30029 New room list: change room options icon
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/room-panel-empty-room-list-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-header.spec.ts/room-list-header-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-header.spec.ts/room-list-space-header-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-panel.spec.ts/room-list-panel-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-panel.spec.ts/room-list-panel-smallscreen-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-more-options-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-selection-linux.png
  src/components/views/rooms/RoomListPanel/RoomListOptionsMenu.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListHeaderView-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListOptionsMenu-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPanel-test.tsx.snap
Labels: T-Enhancement

#30098 Add ability to prevent window content being captured by other apps (Desktop)
  src/@types/global.d.ts
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/vector/platform/ElectronPlatform.tsx
  test/test-utils/test-utils.ts
  test/unit-tests/vector/platform/ElectronPlatform-test.ts
Labels: T-Enhancement

#30065 Add low priority avatar decoration to room tile
  playwright/e2e/left-panel/room-list-panel/room-list.spec.ts
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-low-priority-linux.png
  src/components/viewmodels/avatars/RoomAvatarViewModel.tsx
  src/components/views/avatars/RoomAvatarView.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/viewmodels/avatars/RoomAvatarViewModel-test.tsx
  test/unit-tests/components/views/avatars/RoomAvatarView-test.tsx
  test/unit-tests/components/views/avatars/__snapshots__/RoomAvatarView-test.tsx.snap
Labels: T-Enhancement

#30094 Provide a devtool for manually verifying other devices
  src/SlashCommands.tsx
  src/components/views/dialogs/ManualDeviceKeyVerificationDialog.tsx
  src/components/views/dialogs/devtools/Crypto.tsx
  src/i18n/strings/en_EN.json
  test/test-utils/test-utils.ts
  test/unit-tests/SlashCommands-test.tsx
  test/unit-tests/components/views/dialogs/ManualDeviceKeyVerificationDialog-test.tsx
  test/unit-tests/components/views/dialogs/__snapshots__/ManualDeviceKeyVerificationDialog-test.tsx.snap
Labels: T-Enhancement

#30102 Warn user before doing a manual verification via slash command
  src/SlashCommands.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/SlashCommands-test.tsx
Labels: T-Task

#29992 New room list: filter list can be collapsed
  playwright/e2e/left-panel/room-list-panel/room-list-filter-sort.spec.ts
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/Favourite-empty-room-list-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/Invites-empty-room-list-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/Mentions-empty-room-list-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/People-empty-room-list-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/Rooms-empty-room-list-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/Unreads-empty-room-list-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/default-empty-room-list-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/room-panel-empty-room-list-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/unread-dm-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/unread-primary-filters-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/unselected-primary-filters-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-header.spec.ts/room-list-header-space-menu-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-panel.spec.ts/room-list-panel-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-panel.spec.ts/room-list-panel-smallscreen-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-activity-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-hover-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-hover-silent-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-invited-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-low-priority-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-mark-as-unread-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-mention-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-message-preview-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-notification-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-more-options-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-notification-options-selection-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-public-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-silent-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-video-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-scrolled-linux.png
  res/css/views/rooms/RoomListPanel/_RoomListPrimaryFilters.pcss
  src/components/views/rooms/RoomListPanel/RoomListPrimaryFilters.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListPanel-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListPrimaryFilters-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPanel-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPrimaryFilters-test.tsx.snap
Labels: T-Enhancement

#30131 Fix #30118 - TypeError in manual verify - by using MatrixClientPeg
  src/components/views/dialogs/ManualDeviceKeyVerificationDialog.tsx
  test/unit-tests/components/views/dialogs/ManualDeviceKeyVerificationDialog-test.tsx
Labels: T-Task

#30132 Spacestore should emit event after rebuilding home space
  src/stores/spaces/SpaceStore.ts
Labels: T-Defect

#30134 Use nav for new room list and label sections
  playwright/e2e/left-panel/room-list-panel/room-list-filter-sort.spec.ts
  playwright/e2e/left-panel/room-list-panel/room-list-panel.spec.ts
  playwright/e2e/left-panel/room-list-panel/room-list.spec.ts
  src/components/structures/RoomView.tsx
  src/components/views/rooms/RoomListPanel/RoomListPanel.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap
Labels: T-Defect

#29808 Mvvm split user info, create userinfoadmintools container component
  src/components/viewmodels/right_panel/user_info/admin/UserInfoAdminToolsContainerViewModel.tsx
  src/components/viewmodels/right_panel/user_info/admin/UserInfoBanButtonViewModel.tsx
  src/components/viewmodels/right_panel/user_info/admin/UserInfoKickButtonViewModel.tsx
  src/components/viewmodels/right_panel/user_info/admin/UserInfoMuteButtonViewModel.tsx
  src/components/viewmodels/right_panel/user_info/admin/UserInfoRedactButtonViewModel.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/right_panel/user_info/UserInfoAdminToolsContainer.tsx
  test/unit-tests/components/viewmodels/right_panel/user_info/admin/UserInfoAdminToolsContainerViewModel-test.tsx
  test/unit-tests/components/viewmodels/right_panel/user_info/admin/UserInfoBanButtonViewModel-test.tsx
  test/unit-tests/components/viewmodels/right_panel/user_info/admin/UserInfoKickButtonViewModel-test.tsx
  test/unit-tests/components/viewmodels/right_panel/user_info/admin/UserInfoMuteButtonViewModel-test.tsx
  test/unit-tests/components/viewmodels/right_panel/user_info/admin/UserInfoRedactButtonViewModel-test.tsx
  test/unit-tests/components/views/right_panel/UserInfo-test.tsx
  test/unit-tests/components/views/right_panel/UserInfoAdminToolsContainer-test.tsx
Labels: T-Task, Z-Community-PR

#30124 Update `IconButton` colors
  package.json
  playwright/snapshots/release-announcement/releaseAnnouncement.spec.ts/release-announcement-All-new-pinned-messages-linux.png
  res/css/structures/_ThreadsActivityCentre.pcss
  res/css/views/rooms/_RoomHeader.pcss
  src/components/views/right_panel/BaseCard.tsx
  src/components/views/rooms/RoomListPanel/RoomListPrimaryFilters.tsx
  test/unit-tests/components/structures/__snapshots__/FilePanel-test.tsx.snap
  test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/unit-tests/components/structures/__snapshots__/ThreadPanel-test.tsx.snap
  test/unit-tests/components/views/elements/__snapshots__/AppTile-test.tsx.snap
  test/unit-tests/components/views/right_panel/__snapshots__/BaseCard-test.tsx.snap
  test/unit-tests/components/views/right_panel/__snapshots__/ExtensionsCard-test.tsx.snap
  test/unit-tests/components/views/right_panel/__snapshots__/PinnedMessagesCard-test.tsx.snap
  test/unit-tests/components/views/right_panel/__snapshots__/RoomSummaryCardView-test.tsx.snap
  test/unit-tests/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomHeader/__snapshots__/RoomHeader-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomHeader/__snapshots__/VideoRoomChatButton-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListHeaderView-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListItemMenuView-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListOptionsMenu-test.tsx.snap
  test/unit-tests/components/views/rooms/__snapshots__/PinnedEventTile-test.tsx.snap
  test/unit-tests/components/views/rooms/__snapshots__/ThirdPartyMemberInfo-test.tsx.snap
  test/unit-tests/components/views/settings/__snapshots__/ThemeChoicePanel-test.tsx.snap
  test/unit-tests/components/views/settings/encryption/__snapshots__/ChangeRecoveryKey-test.tsx.snap
  test/unit-tests/components/views/settings/encryption/__snapshots__/DeleteKeyStoragePanel-test.tsx.snap
  test/unit-tests/components/views/settings/encryption/__snapshots__/ResetIdentityPanel-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/EncryptionUserSettingsTab-test.tsx.snap
  test/unit-tests/components/views/spaces/__snapshots__/SpacePanel-test.tsx.snap
  test/unit-tests/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
  yarn.lock
Labels: T-Enhancement

#30075 Prompt users to set up recovery
  playwright/snapshots/settings/account-user-settings-tab.spec.ts/account-linux.png
  playwright/snapshots/settings/account-user-settings-tab.spec.ts/account-smallscreen-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/appearance-tab-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/window-12px-linux.png
  playwright/snapshots/settings/encryption-user-tab/recovery.spec.ts/set-up-recovery-linux.png
  playwright/snapshots/settings/preferences-user-settings-tab.spec.ts/Preferences-user-settings-tab-should-be-rendered-properly-1-linux.png
  res/css/views/dialogs/_SettingsDialog.pcss
  res/css/views/settings/_SettingsHeader.pcss
  src/@types/matrix-js-sdk.d.ts
  src/DeviceListener.ts
  src/components/structures/TabbedView.tsx
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/settings/SettingsHeader.tsx
  src/components/views/settings/encryption/ChangeRecoveryKey.tsx
  src/hooks/useEventEmitter.ts
  src/i18n/strings/en_EN.json
  src/toasts/SetupEncryptionToast.ts
  test/test-utils/client.ts
  test/unit-tests/DeviceListener-test.ts
  test/unit-tests/components/views/dialogs/UserSettingsDialog-test.tsx
  test/unit-tests/components/views/settings/__snapshots__/SettingsHeader-test.tsx.snap
  test/unit-tests/components/views/settings/encryption/ChangeRecoveryKey-test.tsx
  test/unit-tests/components/views/settings/encryption/__snapshots__/RecoveryPanel-test.tsx.snap
  test/unit-tests/components/views/settings/encryption/__snapshots__/RecoveryPanelOutOfSync-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/EncryptionUserSettingsTab-test.tsx.snap
  test/unit-tests/toasts/SetupEncryptionToast-test.tsx
Labels: T-Enhancement

#30158 docs: Remove scalar for riot.im
  config.sample.json
  docs/config.md
  docs/kubernetes.md
  element.io/app/config.json
  element.io/develop/config.json
Labels: T-Task, Z-Community-PR

#30165 Fix untranslatable string "People" in notifications beta
  src/components/views/settings/notifications/NotificationSettings2.tsx
Labels: T-Defect

#30175 Use stale-screenshot-reporter from playwright-common
  .github/workflows/end-to-end-tests.yaml
  package.json
  playwright/stale-screenshot-reporter.ts
  yarn.lock
Labels: T-Task

#29952 New room list: add context menu to room list item
  package.json
  playwright/e2e/left-panel/room-list-panel/room-list.spec.ts
  src/components/viewmodels/roomlist/RoomListItemViewModel.tsx
  src/components/views/rooms/RoomListPanel/RoomListItemContextMenuView.tsx
  src/components/views/rooms/RoomListPanel/RoomListItemMenuView.tsx
  src/components/views/rooms/RoomListPanel/RoomListItemView.tsx
  test/unit-tests/components/viewmodels/roomlist/RoomListItemViewModel-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomList-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListItemView-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomList-test.tsx.snap
  yarn.lock
Labels: T-Enhancement

#30211 test: use `forceCloseAllModals` instead of `closeCurrentModal`
  test/test-utils/utilities.ts
  test/unit-tests/components/views/settings/AddRemoveThreepids-test.tsx
  test/unit-tests/components/views/settings/__snapshots__/AddRemoveThreepids-test.tsx.snap
Labels: T-Task

#30005 Mvvm split user info, create powerlevels component
  src/components/viewmodels/right_panel/UserInfoPowerlevelViewModel.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/right_panel/user_info/UserInfoPowerLevels.tsx
  test/unit-tests/components/viewmodels/right_panel/user_info/UserInfoPowerLevelsViewModel-test.tsx
  test/unit-tests/components/views/right_panel/UserInfo-test.tsx
  test/unit-tests/components/views/right_panel/user_info/UserInfoPowerLevels-test.tsx
Labels: T-Task, Z-Community-PR

#30231 fix typo in comment and reinstate logging of variables
  src/DeviceListener.ts
Labels: T-Task
