Repository element-hq/element-web, pull requests merged in 2025-03, with the labels that each got.

#29394 Fix edited code block width
  playwright/e2e/timeline/timeline.spec.ts
  playwright/snapshots/timeline/timeline.spec.ts/code-block-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/edited-code-block-linux.png
  res/css/views/rooms/_EventTile.pcss
Labels: T-Defect

#29357 Room List - Implement a minimal view model
  src/components/viewmodels/roomlist/RoomListViewModel.tsx
  src/components/views/rooms/RoomListPanel/RoomListPanel.tsx
  src/stores/room-list-v3/RoomListStoreV3.ts
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPanel-test.tsx.snap
  test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
  test/unit-tests/stores/room-list-v3/skip-list/RoomSkipList-test.ts
  test/unit-tests/stores/room-list-v3/skip-list/getMockedRooms.ts
Labels: T-Enhancement

#29397 Room List - Update the room list store on actions from the dispatcher
  src/stores/room-list-v3/RoomListStoreV3.ts
  test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
Labels: T-Enhancement

#29403 Remove redundant `UserIdentityWarning` test
  test/unit-tests/components/views/rooms/UserIdentityWarning-test.tsx
Labels: T-Task

#29404 Device dehydration: remove .well-known check
  playwright/e2e/crypto/dehydration.spec.ts
  src/utils/device/dehydration.ts
Labels: T-Task, X-Release-Blocker

#29399 Room List Store: Filter rooms by active space
  src/stores/room-list-v3/RoomListStoreV3.ts
  src/stores/room-list-v3/skip-list/RoomNode.ts
  src/stores/room-list-v3/skip-list/RoomSkipList.ts
  src/stores/spaces/SpaceStore.ts
  test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
  test/unit-tests/stores/room-list-v3/skip-list/RoomSkipList-test.ts
Labels: T-Enhancement

#29388 Prevent user from accidentally triggering multiple identity resets
  res/css/_components.pcss
  res/css/views/settings/encryption/_ResetIdentityPanel.pcss
  src/components/views/settings/encryption/ResetIdentityPanel.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/views/settings/encryption/ResetIdentityPanel-test.tsx
  test/unit-tests/components/views/settings/encryption/__snapshots__/ResetIdentityPanel-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/EncryptionUserSettingsTab-test.tsx.snap
Labels: T-Defect

#29402 Add more functionality to the room list vm
  src/components/viewmodels/roomlist/RoomListViewModel.tsx
  test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
Labels: T-Enhancement

#29254 Show error screens in group calls
  src/components/structures/RoomView.tsx
  src/components/views/messages/CallEvent.tsx
  src/components/views/rooms/RoomTileCallSummary.tsx
  src/components/views/voip/CallView.tsx
  src/contexts/RoomContext.ts
  src/createRoom.ts
  src/hooks/useCall.ts
  src/i18n/strings/en_EN.json
  src/models/Call.ts
  src/stores/RoomViewStore.tsx
  src/stores/widgets/ElementWidgetActions.ts
  src/stores/widgets/WidgetMessagingStore.ts
  test/test-utils/call.ts
  test/test-utils/room.ts
  test/unit-tests/components/structures/RoomView-test.tsx
  test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomHeader/RoomHeader-test.tsx
  test/unit-tests/components/views/rooms/RoomHeader/__snapshots__/RoomHeader-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomTile-test.tsx
  test/unit-tests/components/views/rooms/SendMessageComposer-test.tsx
  test/unit-tests/components/views/voip/CallView-test.tsx
  test/unit-tests/models/Call-test.ts
  test/unit-tests/stores/RoomViewStore-test.ts
Labels: T-Defect

#29378 Improve rageshake upload experience by providing useful error information
  src/components/views/dialogs/BugReportDialog.tsx
  src/i18n/strings/en_EN.json
  src/rageshake/submit-rageshake.ts
  test/unit-tests/components/views/dialogs/BugReportDialog-test.tsx
Labels: T-Enhancement

#29368 New room list: basic flat list
  playwright/e2e/left-panel/room-list-panel/room-list-panel.spec.ts
  playwright/e2e/left-panel/room-list-panel/room-list.spec.ts
  playwright/snapshots/left-panel/room-list-panel/room-list-panel.spec.ts/room-list-panel-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-scrolled-linux.png
  res/css/_components.pcss
  res/css/views/rooms/RoomListPanel/_RoomList.pcss
  res/css/views/rooms/RoomListPanel/_RoomListCell.pcss
  res/css/views/rooms/RoomListPanel/_RoomListHeaderView.pcss
  res/css/views/rooms/RoomListPanel/_RoomListSearch.pcss
  src/components/views/rooms/RoomListPanel/RoomList.tsx
  src/components/views/rooms/RoomListPanel/RoomListCell.tsx
  src/components/views/rooms/RoomListPanel/RoomListPanel.tsx
  src/components/views/rooms/RoomListPanel/RoomListView.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/views/rooms/RoomListPanel/RoomList-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListCell-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomList-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListCell-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPanel-test.tsx.snap
Labels: T-Enhancement

#29433 Room List Store: Support filters by implementing just the favourite filter
  src/stores/room-list-v3/RoomListStoreV3.ts
  src/stores/room-list-v3/skip-list/RoomNode.ts
  src/stores/room-list-v3/skip-list/RoomSkipList.ts
  src/stores/room-list-v3/skip-list/filters/FavouriteFilter.ts
  src/stores/room-list-v3/skip-list/filters/index.ts
  src/stores/room-list-v3/skip-list/iterators.ts
  test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
Labels: T-Enhancement

#29444 Room List Store: Implement rest of the primary filters
  src/stores/room-list-v3/RoomListStoreV3.ts
  src/stores/room-list-v3/skip-list/filters/PeopleFilter.ts
  src/stores/room-list-v3/skip-list/filters/RoomsFilter.ts
  src/stores/room-list-v3/skip-list/filters/UnreadFilter.ts
  src/stores/room-list-v3/skip-list/filters/index.ts
  test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
Labels: T-Enhancement

#29458 Room List Store: Implement secondary filters
  src/stores/room-list-v3/RoomListStoreV3.ts
  src/stores/room-list-v3/skip-list/filters/InvitesFilter.ts
  src/stores/room-list-v3/skip-list/filters/LowPriorityFilter.ts
  src/stores/room-list-v3/skip-list/filters/MentionsFilter.ts
  src/stores/room-list-v3/skip-list/filters/index.ts
  test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
Labels: T-Enhancement

#29453 Room List Store: Fetch rooms after space store is ready + attach store to window
  src/@types/global.d.ts
  src/stores/room-list-v3/RoomListStoreV3.ts
Labels: T-Defect

#29454 RoomListViewModel: Support primary filters in the view model
  src/components/viewmodels/roomlist/RoomListViewModel.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomList-test.tsx
Labels: T-Enhancement

#29465 RoomListViewModel: Support secondary filters in the view model
  src/components/viewmodels/roomlist/RoomListViewModel.tsx
  src/components/viewmodels/roomlist/useFilteredRooms.tsx
  test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomList-test.tsx
Labels: T-Enhancement

#29470 White background for 'They do not match' button
  src/components/views/verification/VerificationShowSas.tsx
Labels: T-Enhancement

#29374 Change ToggleHiddenEventVisibility & GoToHome KeyBindingActions
  src/accessibility/KeyboardShortcuts.ts
Labels: T-Defect, Z-Community-PR

#29480 Add wrap props to flex component
  res/css/components/views/utils/_Flex.pcss
  src/components/utils/Flex.tsx
  test/unit-tests/async-components/structures/__snapshots__/ErrorView-test.tsx.snap
  test/unit-tests/components/structures/__snapshots__/FilePanel-test.tsx.snap
  test/unit-tests/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/unit-tests/components/views/auth/__snapshots__/InteractiveAuthEntryComponents-test.tsx.snap
  test/unit-tests/components/views/right_panel/__snapshots__/ExtensionsCard-test.tsx.snap
  test/unit-tests/components/views/right_panel/__snapshots__/PinnedMessagesCard-test.tsx.snap
  test/unit-tests/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/unit-tests/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomHeader/__snapshots__/RoomHeader-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomList-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListCell-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListHeaderView-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPanel-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListSearch-test.tsx.snap
  test/unit-tests/components/views/rooms/__snapshots__/ThirdPartyMemberInfo-test.tsx.snap
  test/unit-tests/components/views/rooms/memberlist/__snapshots__/MemberTileView-test.tsx.snap
  test/unit-tests/components/views/settings/encryption/__snapshots__/ResetIdentityPanel-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/EncryptionUserSettingsTab-test.tsx.snap
  test/unit-tests/vector/__snapshots__/init-test.ts.snap
Labels: T-Task

#29488 Avoid using /tmp/ for bind mounts and non-tmpfs binds
  .github/workflows/docker.yaml
  docker/docker-entrypoint.d/18-load-element-modules.sh
  docker/nginx-templates/default.conf.template
  docs/install.md
Labels: T-Task

#28209 Implement MSC4142: Remove unintentional intentional mentions in replies
  src/components/views/rooms/SendMessageComposer.tsx
  test/unit-tests/components/views/rooms/EditMessageComposer-test.tsx
  test/unit-tests/components/views/rooms/SendMessageComposer-test.tsx
Labels: T-Enhancement, Z-Community-PR

#29481 New room list: add primary filters
  playwright/e2e/left-panel/room-list-panel/room-list-filter-sort.spec.ts
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/unread-primary-filters-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-filter-sort.spec.ts/unselected-primary-filters-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list-panel.spec.ts/room-list-panel-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-scrolled-linux.png
  res/css/_components.pcss
  res/css/views/rooms/RoomListPanel/_RoomListPrimaryFilters.pcss
  src/components/views/rooms/RoomListPanel/RoomListPrimaryFilters.tsx
  src/components/views/rooms/RoomListPanel/RoomListView.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListPrimaryFilters-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPanel-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPrimaryFilters-test.tsx.snap
Labels: T-Enhancement

#29310 Add key storage toggle to Encryption settings
  playwright/e2e/settings/encryption-user-tab/encryption-tab.spec.ts
  playwright/snapshots/settings/encryption-user-tab/advanced.spec.ts/encryption-details-linux.png
  playwright/snapshots/settings/encryption-user-tab/advanced.spec.ts/reset-cryptographic-identity-linux.png
  playwright/snapshots/settings/encryption-user-tab/encryption-tab.spec.ts/default-tab-linux.png
  playwright/snapshots/settings/encryption-user-tab/encryption-tab.spec.ts/delete-key-storage-confirm-linux.png
  playwright/snapshots/settings/encryption-user-tab/recovery.spec.ts/default-recovery-linux.png
  playwright/snapshots/settings/encryption-user-tab/recovery.spec.ts/set-up-recovery-linux.png
  res/css/_components.pcss
  res/css/components/views/settings/encryption/_KeyStoragePanel.pcss
  src/DeviceListener.ts
  src/components/viewmodels/settings/encryption/KeyStoragePanelViewModel.ts
  src/components/views/settings/encryption/DeleteKeyStoragePanel.tsx
  src/components/views/settings/encryption/KeyStoragePanel.tsx
  src/components/views/settings/tabs/user/EncryptionUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/test-utils/test-utils.ts
  test/unit-tests/components/viewmodels/settings/encryption/KeyStoragePanelViewModel-test.ts
  test/unit-tests/components/views/settings/encryption/DeleteKeyStoragePanel-test.tsx
  test/unit-tests/components/views/settings/encryption/__snapshots__/DeleteKeyStoragePanel-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/user/EncryptionUserSettingsTab-test.tsx
Labels: T-Enhancement

#29493 Room List Store: Save preferred sorting algorithm and use that on app launch
  src/settings/Settings.tsx
  src/stores/room-list-v3/RoomListStoreV3.ts
  src/stores/room-list-v3/skip-list/RoomSkipList.ts
  src/stores/room-list-v3/skip-list/sorters/AlphabeticSorter.ts
  src/stores/room-list-v3/skip-list/sorters/RecencySorter.ts
  src/stores/room-list-v3/skip-list/sorters/index.ts
  test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
Labels: T-Enhancement

#29489 Add analytics constant to encryption tab
  package.json
  src/components/views/dialogs/UserSettingsDialog.tsx
  yarn.lock
Labels: T-Task

#29497 Add setting to hide avatars of rooms you have been invited to.
  playwright/snapshots/settings/preferences-user-settings-tab.spec.ts/Preferences-user-settings-tab-should-be-rendered-properly-1-linux.png
  src/components/views/avatars/RoomAvatar.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/unit-tests/components/views/avatars/RoomAvatar-test.tsx
  test/unit-tests/components/views/avatars/__snapshots__/RoomAvatar-test.tsx.snap
  test/unit-tests/components/views/settings/tabs/user/__snapshots__/PreferencesUserSettingsTab-test.tsx.snap
Labels: T-Enhancement

#29499 RoomListViewModel: Provide a way to resort the room list and track the active sort method
  src/components/viewmodels/roomlist/RoomListViewModel.tsx
  src/components/viewmodels/roomlist/useSorter.ts
  test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomList-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListPrimaryFilters-test.tsx
Labels: T-Enhancement

#29500 New room list: fix compose menu action in space
  src/components/viewmodels/roomlist/RoomListHeaderViewModel.tsx
  src/components/views/rooms/RoomListPanel/RoomListHeaderView.tsx
  test/unit-tests/components/viewmodels/roomlist/RoomListHeaderViewModel-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListHeaderView-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListHeaderView-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListPanel-test.tsx.snap
Labels: T-Defect

#29445 New room list: add more options menu on room list item
  package.json
  playwright/e2e/left-panel/room-list-panel/room-list.spec.ts
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-hover-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-more-options-linux.png
  res/css/_components.pcss
  res/css/views/rooms/RoomListPanel/_RoomListItemMenuView.pcss
  res/css/views/rooms/RoomListPanel/_RoomListItemView.pcss
  src/components/viewmodels/roomlist/RoomListItemMenuViewModel.tsx
  src/components/viewmodels/roomlist/RoomListItemViewModel.tsx
  src/components/viewmodels/roomlist/RoomListViewModel.tsx
  src/components/viewmodels/roomlist/utils.ts
  src/components/views/rooms/RoomListPanel/RoomList.tsx
  src/components/views/rooms/RoomListPanel/RoomListCell.tsx
  src/components/views/rooms/RoomListPanel/RoomListItemMenuView.tsx
  src/components/views/rooms/RoomListPanel/RoomListItemView.tsx
  src/i18n/strings/en_EN.json
  test/test-utils/test-utils.ts
  test/unit-tests/components/viewmodels/roomlist/RoomListItemMenuViewModel-test.tsx
  test/unit-tests/components/viewmodels/roomlist/RoomListItemViewModel-test.tsx
  test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomList-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListCell-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListItemMenuView-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListItemView-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListPrimaryFilters-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomList-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListItemMenuView-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListItemView-test.tsx.snap
  yarn.lock
Labels: T-Enhancement

#29510 Do not eslint playwright files.
  .eslintignore
Labels: T-Task

#29477 Move a bunch of shared playwright code into @element-hq/element-web-playwright-common
  package.json
  playwright.config.ts
  playwright/@types/playwright-core.d.ts
  playwright/Dockerfile
  playwright/docker-entrypoint.sh
  playwright/e2e/csAPI.ts
  playwright/e2e/editing/editing.spec.ts
  playwright/e2e/login/login-consent.spec.ts
  playwright/e2e/messages/messages.spec.ts
  playwright/e2e/oidc/index.ts
  playwright/e2e/register/email.spec.ts
  playwright/e2e/register/register.spec.ts
  playwright/e2e/spaces/spaces.spec.ts
  playwright/e2e/timeline/timeline.spec.ts
  playwright/element-web-test.ts
  playwright/logger.ts
  playwright/plugins/homeserver/dendrite/index.ts
  playwright/plugins/homeserver/index.ts
  playwright/plugins/homeserver/synapse/consentHomeserver.ts
  playwright/plugins/homeserver/synapse/masHomeserver.ts
  playwright/plugins/oauth_server/index.ts
  playwright/plugins/utils/api.ts
  playwright/plugins/utils/object.ts
  playwright/plugins/utils/port.ts
  playwright/plugins/utils/rand.ts
  playwright/plugins/webserver/index.ts
  playwright/services.ts
  playwright/snapshots/right-panel/memberlist.spec.ts/with-four-members-linux.png
  playwright/testcontainers/HomeserverContainer.ts
  playwright/testcontainers/dendrite.ts
  playwright/testcontainers/mailpit.ts
  playwright/testcontainers/mas.ts
  playwright/testcontainers/synapse.ts
  yarn.lock
Labels: T-Task

#29511 RoomListViewModel: Add functionality to toggle message preview setting
  src/components/viewmodels/roomlist/RoomListViewModel.tsx
  src/components/viewmodels/roomlist/useMessagePreviewToggle.tsx
  src/settings/Settings.tsx
  test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomList-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListPrimaryFilters-test.tsx
Labels: T-Enhancement

#29514 Implement `MessagePreviewViewModel`
  src/components/viewmodels/roomlist/MessagePreviewViewModel.tsx
  test/unit-tests/components/viewmodels/roomlist/MessagePreviewViewModel-test.tsx
Labels: T-Enhancement

#29519 RoomListViewModel: Track the index of the active room in the list
  src/components/viewmodels/roomlist/RoomListViewModel.tsx
  src/components/viewmodels/roomlist/useIndexForActiveRoom.tsx
  test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/EmptyRoomList-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomList-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListPrimaryFilters-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListView-test.tsx
Labels: T-Enhancement

#29467 Add ability to hide images after clicking "show image"
  playwright/e2e/timeline/timeline.spec.ts
  src/components/views/messages/HideActionButton.tsx
  src/components/views/messages/MFileBody.tsx
  src/components/views/messages/MImageBody.tsx
  src/components/views/messages/MImageReplyBody.tsx
  src/components/views/messages/MStickerBody.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/messages/MessageEvent.tsx
  src/components/views/rooms/ReplyTile.tsx
  src/events/EventTileFactory.tsx
  src/hooks/useMediaVisible.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/SettingsStore.ts
  test/unit-tests/components/views/messages/HideActionButton-test.tsx
  test/unit-tests/components/views/messages/MImageBody-test.tsx
  test/unit-tests/hooks/useMediaVisible-test.tsx
Labels: T-Enhancement

#29503 Doc improvements from #29138
  playwright/e2e/crypto/toasts.spec.ts
  playwright/e2e/crypto/utils.ts
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/settings/encryption/ResetIdentityPanel.tsx
  src/components/views/settings/tabs/user/EncryptionUserSettingsTab.tsx
  src/toasts/SetupEncryptionToast.ts
Labels: T-Task

#28515 Simplified Sliding Sync
  playwright/e2e/sliding-sync/sliding-sync.spec.ts
  src/MatrixClientPeg.ts
  src/SlidingSyncManager.ts
  src/Unread.ts
  src/components/views/rooms/RoomSublist.tsx
  src/hooks/useSlidingSyncRoomSearch.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/controllers/SlidingSyncController.ts
  src/stores/MemberListStore.ts
  src/stores/RoomViewStore.tsx
  src/stores/room-list/RoomListStore.ts
  src/stores/room-list/SlidingRoomListStore.ts
  src/stores/room-list/algorithms/tag-sorting/RecentAlgorithm.ts
  test/test-utils/test-utils.ts
  test/unit-tests/SlidingSyncManager-test.ts
  test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
  test/unit-tests/hooks/useSlidingSyncRoomSearch-test.tsx
  test/unit-tests/stores/MemberListStore-test.ts
  test/unit-tests/stores/RoomViewStore-test.ts
  test/unit-tests/stores/room-list/SlidingRoomListStore-test.ts
Labels: T-Enhancement

#29531 New room list: add selection decoration
  playwright/e2e/left-panel/room-list-panel/room-list.spec.ts
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-hover-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-more-options-linux.png
  res/css/views/rooms/RoomListPanel/_RoomList.pcss
  res/css/views/rooms/RoomListPanel/_RoomListItemView.pcss
  src/components/views/rooms/RoomListPanel/RoomList.tsx
  src/components/views/rooms/RoomListPanel/RoomListItemView.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListItemView-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomList-test.tsx.snap
  test/unit-tests/components/views/rooms/RoomListPanel/__snapshots__/RoomListItemView-test.tsx.snap
Labels: T-Enhancement

#29547 Add title attribute to user identifier
  src/components/structures/UserMenu.tsx
Labels: T-Defect, Z-Community-PR

#29487 In force-verify mode, prevent bypassing by cancelling device verification
  playwright/e2e/login/login-consent.spec.ts
  src/components/structures/MatrixChat.tsx
  test/unit-tests/components/structures/MatrixChat-test.tsx
Labels: T-Defect

#29555 RoomListStore: Unread filter should only filter rooms having unread counts
  playwright/e2e/left-panel/room-list-panel/room-list.spec.ts
  src/stores/room-list-v3/skip-list/filters/UnreadFilter.ts
  test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
Labels: T-Defect

#29562 RoomListViewModel: Reset any primary filter on secondary filter change
  src/components/viewmodels/roomlist/useFilteredRooms.tsx
  test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
Labels: T-Defect

#29561 Reuse PushProcessor from MatrixClient
  src/LegacyCallHandler.tsx
  src/components/views/messages/TextualBody.tsx
  src/settings/controllers/NotificationControllers.ts
  src/utils/pillify.tsx
  src/utils/pushRules/monitorSyncedPushRules.ts
  src/utils/pushRules/updatePushRuleActions.ts
  test/unit-tests/LegacyCallHandler-test.ts
  test/unit-tests/components/structures/LoggedInView-test.tsx
  test/unit-tests/components/views/messages/TextualBody-test.tsx
  test/unit-tests/components/views/settings/Notifications-test.tsx
  test/unit-tests/utils/pillify-test.tsx
Labels: T-Task

#29551 RoomListViewModel: Make the active room sticky in the list
  src/components/viewmodels/roomlist/RoomListViewModel.tsx
  src/components/viewmodels/roomlist/useIndexForActiveRoom.tsx
  src/components/viewmodels/roomlist/useStickyRoomList.tsx
  test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
Labels: T-Enhancement

#29513 Add report room dialog button/dialog.
  playwright/e2e/right-panel/right-panel.spec.ts
  playwright/snapshots/right-panel/right-panel.spec.ts/with-leave-room-linux.png
  res/css/_components.pcss
  res/css/views/dialogs/_ReportRoomDialog.pcss
  res/css/views/right_panel/_RoomSummaryCard.pcss
  src/components/views/dialogs/ReportRoomDialog.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/views/dialogs/ReportRoomDialog-test.tsx
  test/unit-tests/components/views/dialogs/__snapshots__/ReportRoomDialog-test.tsx.snap
  test/unit-tests/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
Labels: T-Enhancement

#29568 Generate/load pickle key on SSO
  src/Lifecycle.ts
Labels: T-Enhancement, Z-Community-PR

#29569 Use 'Dismiss' to close pinned identity changes, instead of 'Ok'
  src/components/views/rooms/UserIdentityWarning.tsx
Labels: T-Task

#29573 Use an outline icon for the report room button
  playwright/snapshots/right-panel/right-panel.spec.ts/with-leave-room-linux.png
  src/components/views/right_panel/RoomSummaryCard.tsx
  test/unit-tests/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
Labels: T-Enhancement

#29496 Add support for hiding videos
  playwright/e2e/timeline/timeline.spec.ts
  playwright/sample-files/5secvid.webm
  res/css/_components.pcss
  res/css/views/messages/_HiddenMediaPlaceholder.pcss
  res/css/views/messages/_MImageBody.pcss
  src/components/views/messages/HiddenMediaPlaceholder.tsx
  src/components/views/messages/MImageBody.tsx
  src/components/views/messages/MVideoBody.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/i18n/strings/en_EN.json
  src/utils/MediaEventHelper.ts
  test/unit-tests/components/views/messages/MImageBody-test.tsx
  test/unit-tests/components/views/messages/MVideoBody-test.tsx
  test/unit-tests/components/views/messages/__snapshots__/MImageBody-test.tsx.snap
Labels: T-Enhancement

#29564 Room notification state: add clearer methods, documentation and deprecation
  src/RoomNotifs.ts
  src/stores/notifications/NotificationState.ts
  src/stores/notifications/RoomNotificationState.ts
  test/unit-tests/stores/notifications/RoomNotificationState-test.ts
  test/unit-tests/stores/room-list/algorithms/list-ordering/ImportanceAlgorithm-test.ts
  test/unit-tests/stores/room-list/algorithms/list-ordering/NaturalAlgorithm-test.ts
Labels: T-Task

#29558 Fix bug which caused startup to hang if the clock was wound back since a previous session
  src/utils/SessionLock.ts
  test/unit-tests/utils/SessionLock-test.ts
Labels: T-Defect

#29580 RoomListStore: Unread filter should match rooms that were marked as unread
  src/stores/room-list-v3/RoomListStoreV3.ts
  src/stores/room-list-v3/skip-list/filters/UnreadFilter.ts
  test/unit-tests/stores/room-list-v3/RoomListStoreV3-test.ts
Labels: T-Enhancement

#29566 Fix token expiry racing with login causing wrong error to be shown
  playwright/e2e/oidc/oidc-native.spec.ts
  playwright/snapshots/oidc/oidc-native.spec.ts/token-expired-linux.png
  src/Lifecycle.ts
  src/components/structures/MatrixChat.tsx
  test/unit-tests/Lifecycle-test.ts
Labels: T-Defect

#29584 New Room List: Move tests that are in the wrong location
  playwright/e2e/left-panel/room-list-panel/room-list-filter-sort.spec.ts
  playwright/e2e/left-panel/room-list-panel/room-list.spec.ts
  test/unit-tests/components/viewmodels/roomlist/RoomListViewModel-test.tsx
Labels: T-Task

#29552 New room list: add notification decoration
  package.json
  playwright/e2e/left-panel/room-list-panel/room-list.spec.ts
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-activity-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-invited-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-mark-as-unread-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-mention-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-notification-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-silent-linux.png
  src/components/viewmodels/roomlist/RoomListItemViewModel.tsx
  src/components/views/rooms/NotificationDecoration.tsx
  src/components/views/rooms/RoomListPanel/RoomListItemView.tsx
  src/i18n/strings/en_EN.json
  test/unit-tests/components/viewmodels/roomlist/RoomListItemViewModel-test.tsx
  test/unit-tests/components/views/rooms/NotificationDecoration-test.tsx
  test/unit-tests/components/views/rooms/RoomListPanel/RoomListItemView-test.tsx
  test/unit-tests/components/views/rooms/__snapshots__/NotificationDecoration-test.tsx.snap
  yarn.lock
Labels: T-Enhancement

#29589 Fix MFileBody fileName not considering `filename`
  src/components/views/messages/MFileBody.tsx
Labels: T-Defect

#29586 Switch away from nesting React trees and mangling the DOM
  package.json
  src/HtmlUtils.tsx
  src/Linkify.tsx
  src/components/views/elements/Pill.tsx
  src/components/views/elements/Spoiler.tsx
  src/components/views/messages/CodeBlock.tsx
  src/components/views/messages/EditHistoryMessage.tsx
  src/components/views/messages/EventContentBody.tsx
  src/components/views/messages/TextualBody.tsx
  src/hooks/usePermalinkMember.ts
  src/linkify-matrix.ts
  src/renderer/code-block.tsx
  src/renderer/index.ts
  src/renderer/link-tooltip.tsx
  src/renderer/pill.tsx
  src/renderer/spoiler.tsx
  src/renderer/utils.tsx
  src/utils/pillify.tsx
  src/utils/react.tsx
  src/utils/tooltipify.tsx
  test/test-utils/client.ts
  test/test-utils/test-utils.ts
  test/unit-tests/HtmlUtils-test.tsx
  test/unit-tests/__snapshots__/HtmlUtils-test.tsx.snap
  test/unit-tests/components/structures/MessagePanel-test.tsx
  test/unit-tests/components/structures/TimelinePanel-test.tsx
  test/unit-tests/components/views/elements/Pill-test.tsx
  test/unit-tests/components/views/messages/TextualBody-test.tsx
  test/unit-tests/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
  test/unit-tests/components/views/rooms/SearchResultTile-test.tsx
  test/unit-tests/renderer/__snapshots__/link-tooltip-test.tsx.snap
  test/unit-tests/renderer/__snapshots__/pill-test.tsx.snap
  test/unit-tests/renderer/link-tooltip-test.tsx
  test/unit-tests/renderer/pill-test.tsx
  test/unit-tests/utils/pillify-test.tsx
  test/unit-tests/utils/tooltipify-test.tsx
  yarn.lock
Labels: T-Enhancement

#29593 e2e test: check dehydrated devices with Encryption tab instead of Security & Privacy tab
  playwright/e2e/crypto/dehydration.spec.ts
Labels: T-Task

#29600 test e2e room list: fix flaky test of activity decoration
  playwright/e2e/left-panel/room-list-panel/room-list.spec.ts
Labels: T-Task, Z-Flaky-Test

#29234 e2e test: use encryption tab in `enableKeyBackup` instead of security & settings tab
  playwright/e2e/crypto/crypto.spec.ts
  playwright/e2e/crypto/utils.ts
Labels: T-Task

#29601 Make fetchdep check out matching branch name
  scripts/fetchdep.sh
Labels: T-Defect

#29353 Docker: Use nginx-unprivileged as base image
  Dockerfile
Labels: T-Enhancement

#29605 Hide an event notification if it is redacted
  src/BasePlatform.ts
Labels: T-Enhancement

#29602 Replace onHeightChanged with ResizeObserver
  src/components/structures/MessagePanel.tsx
  src/components/structures/RoomSearchView.tsx
  src/components/views/elements/ReplyChain.tsx
  src/components/views/messages/CodeBlock.tsx
  src/components/views/messages/EventContentBody.tsx
  src/components/views/messages/IBodyProps.ts
  src/components/views/messages/MFileBody.tsx
  src/components/views/messages/MImageBody.tsx
  src/components/views/messages/MVideoBody.tsx
  src/components/views/messages/MessageEvent.tsx
  src/components/views/messages/ReactionsRow.tsx
  src/components/views/messages/TextualBody.tsx
  src/components/views/polls/pollHistory/PollDetail.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/LinkPreviewGroup.tsx
  src/components/views/rooms/PinnedEventTile.tsx
  src/components/views/rooms/ReplyTile.tsx
  src/components/views/rooms/SearchResultTile.tsx
  src/events/EventTileFactory.tsx
  src/renderer/code-block.tsx
  src/renderer/utils.tsx
  test/unit-tests/components/views/messages/MBeaconBody-test.tsx
  test/unit-tests/components/views/messages/MFileBody-test.tsx
  test/unit-tests/components/views/messages/MImageBody-test.tsx
  test/unit-tests/components/views/messages/MLocationBody-test.tsx
  test/unit-tests/components/views/messages/MPollBody-test.tsx
  test/unit-tests/components/views/messages/MPollEndBody-test.tsx
  test/unit-tests/components/views/messages/MStickerBody-test.tsx
  test/unit-tests/components/views/messages/MVideoBody-test.tsx
  test/unit-tests/components/views/messages/MessageEvent-test.tsx
  test/unit-tests/components/views/messages/TextualBody-test.tsx
Labels: T-Task

#29309 Bundle Element Call with Element Web packages
  .github/workflows/static_analysis.yaml
  docs/config.md
  knip.ts
  package.json
  src/IConfigOptions.ts
  src/SdkConfig.ts
  src/components/views/dialogs/DevtoolsDialog.tsx
  src/components/views/elements/SettingsField.tsx
  src/i18n/strings/en_EN.json
  src/models/Call.ts
  src/settings/Settings.tsx
  src/stores/widgets/StopGapWidgetDriver.ts
  test/unit-tests/components/views/dialogs/__snapshots__/DevtoolsDialog-test.tsx.snap
  test/unit-tests/components/views/elements/SettingsField-test.tsx
  test/unit-tests/components/views/elements/__snapshots__/SettingsField-test.tsx.snap
  test/unit-tests/models/Call-test.ts
  test/unit-tests/stores/RoomViewStore-test.ts
  test/unit-tests/stores/widgets/StopGapWidgetDriver-test.ts
  test/unit-tests/stores/widgets/WidgetPermissionStore-test.ts
  test/unit-tests/utils/device/clientInformation-test.ts
  webpack.config.js
  yarn.lock
Labels: T-Enhancement

#29628 e2e test: fix BST/GMT time in preferences
  playwright/e2e/settings/preferences-user-settings-tab.spec.ts
  playwright/snapshots/settings/preferences-user-settings-tab.spec.ts/Preferences-user-settings-tab-should-be-rendered-properly-1-linux.png
Labels: T-Task

#29619 Fix missing ambiguous url tooltips on Element Desktop
  src/components/views/messages/EditHistoryMessage.tsx
  src/components/views/messages/TextualBody.tsx
Labels: T-Defect, X-Release-Blocker

#29612 Prepare for React 19 upgrade
  src/components/structures/AutoHideScrollbar.tsx
  src/components/structures/ContextMenu.tsx
  src/components/views/dialogs/ReportRoomDialog.tsx
  src/components/views/location/MapFallback.tsx
  src/components/views/messages/EventTileBubble.tsx
  src/components/views/room_settings/AliasSettings.tsx
  src/components/views/rooms/RoomContextDetails.tsx
  src/components/views/rooms/RoomKnocksBar.tsx
  src/components/views/settings/tabs/room/PeopleRoomSettingsTab.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
Labels: T-Task

#29627 New room list: add cursor pointer on room list item
  res/css/views/rooms/RoomListPanel/_RoomListItemView.pcss
Labels: T-Defect

#29618 Ensure clicks on spoilers do not get handled by the hidden content
  playwright/e2e/timeline/timeline.spec.ts
  playwright/pages/ElementAppPage.ts
  playwright/snapshots/timeline/timeline.spec.ts/spoiler-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/spoiler-uncovered-linux.png
  res/css/views/rooms/_EventTile.pcss
Labels: T-Defect

#29634 New room list: reduce padding between avatar and room list border
  playwright/snapshots/left-panel/room-list-panel/room-list-panel.spec.ts/room-list-panel-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-activity-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-hover-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-invited-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-mark-as-unread-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-mention-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-notification-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-open-more-options-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-item-silent-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-linux.png
  playwright/snapshots/left-panel/room-list-panel/room-list.spec.ts/room-list-scrolled-linux.png
  res/css/views/rooms/RoomListPanel/_RoomListItemView.pcss
Labels: T-Enhancement
